### ISSUE TITLE
Managed licensing device test uses unmanaged API

### ISSUE THREAD

**Issue by mindw** [F5Networks/f5-common-python#1108]
https://github.com/F5Networks/f5-common-python/blob/development/f5/bigiq/cm/device/licensing/pool/regkey/test/functional/test_licenses.py#L111
Tests TestDeviceLicensing.test_license_unmanaged_device & TestDeviceLicensing.test_license_managed_device have identical implementation.

**Comment by wojtek0806** [comment]
@mindw i believe this is now resolved with #1328, closing
