### ISSUE TITLE
RPM Build is failing

### ISSUE THREAD

**Issue by ssorenso** [F5Networks/f5-common-python#1116]
in this latest release, we're seeing a failure in builds:
Agent Version

f5-openstack-agent-9.3.0-1.el7.noarch.rpm

Operating System

RHEL 7.3

OpenStack Release

RHEL OSP v9 (mitaka)

Description

SDK RPM fails to install due to dependency issue.

[root@isft502 9.3.0]# rpm -qa | grep six
python-six-1.9.0-2.el7.noarch

[root@isft502 9.3.0]# rpm -ivh f5-icontrol-rest-1.3.0-1.el7.noarch.rpm
Preparing... ################################# [100%]
package f5-icontrol-rest-1.3.0-1.noarch is already installed

[root@isft502 9.3.0]# rpm -ivh f5-sdk-2.3.1-1.el7.noarch.rpm
error: Failed dependencies:
f5-icontrol-rest<2.0.0 is needed by f5-sdk-2.3.1-1.noarch
f5-icontrol-rest>=1.3.0 is needed by f5-sdk-2.3.1-1.noarch
six<2.0.0 is needed by f5-sdk-2.3.1-1.noarch
six>=1.9.0 is needed by f5-sdk-2.3.1-1.noarch

Please fix RPM issue. Thanks!

**Comment by ssorenso** [comment]
The overall issue is that the format for RPM's spec file is:
Requires: python-six >= 1.9.0, python-six < 2.0.0, f5-icontrol-rest >= 1.3.0, f5-icontrol-rest < 2.0.0

Instead, the formatting schema that I put into place last February puts this into the format:
Requires: six>=1.9.0 six<2.0.0 ...

Which is not applicable to what we need for RPM packages to work.  The reason why this did not outright fail is that the CLI exit status when we issued:
rpm -i <package>
was not raising for a non-zero exit status.  This also has to be fixed for the Debian side for the non-zero exit status.  It is properly handling its dependencies, though.

**Comment by jgruber** [comment]
Added critical tag as it is a blocking issue for private cloud use cases A2 and A3. 

It also blocks ESD release for OpenStack LBaaSv2.
