### ISSUE TITLE
Get pool member  

### ISSUE THREAD

**Issue by lilongabc** [F5Networks/f5-common-python#1118]
Hi Everyone
I use the following code to find that the print  "get_member_conn" of each cycle is the same value.
How can I get the number of connections( get_member_conn ) in real time during each cycle.
Many Thans

my python code is below:
#############################
while True
 get_member_conn = get_info.get('entries')\
 .get('https://localhost/mgmt/tm/ltm/pool/~Common~my_pool/members/~Common~172.16.0.30:80/~Common~172.16.0.30:80/stats')\
 .get('nestedStats')\
 .get('entries')\
 .get('serverside.curConns')\
 .get('value')
     if get_member_conn == 0:
       print "my session static is 0";
       break;
     else:
       time.sleep(5);
       print("member conn State is: session=%s"  % (get_member_conn));
#####################################

**Comment by caphrim007** [comment]
@lilongabc you need to refresh or load the object to change the values of the stats. For example, here is code that I use in some of the ansible modules.

```
    def _wait_for_state_to_activate(self, resource):
        # Wait no more than half an hour
        for x in range(1, 180):
            resource.refresh()
            try:
                stats = resource.stats.load()
                attrs = stats.attrs
                if int(attrs['entries']['health.placement']['value']) == 1:
                    break
            except Exception:
                pass
            time.sleep(10)
```

I may or may not need that first refresh as the load should take care of getting the new values. I'll need to check on that.

**Comment by caphrim007** [comment]
@lilongabc does this answer your question?

**Comment by wojtek0806** [comment]
closing as answered
