### ISSUE TITLE
Add mgmt/tm/auth provider endpoints

### ISSUE THREAD

**Issue by jasonrahm** [F5Networks/f5-common-python#1120]
radius, ldap, tacacs all missing

**Comment by Sakorah** [comment]
Does this mean implementation of token based auth? I'm in need of this :)

**Comment by jasonrahm** [comment]
token-based auth is already implemented, this is just for implementing the configuration of remote auth endpoints. To use a token..

b = ManagementRoot('host', 'username', 'password', token=True)

**Comment by Sakorah** [comment]
ah :) thanks! 
saw some other closed issues regarding the token auth, but no way of how to use it. I will give it a try! :)
