### ISSUE TITLE
Automated tests failed, but a false positive was reported to github during the 2.3.2 release

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-common-python#1131]
During the PR for the v2.3.2 bugfix release 177 tests were reported as "FAILED" by the automated build system, but the github build indicator remained green.

This false positive results eliminates one of the most valuable features of our test harness.
We need to find the root cause and fix it ASAP!

**Comment by zancas** [comment]
I think this #1137 bug would not have gotten through to consumers (it affected the `f5-openstack-agent`) if this #1131 bug were fixed.

**Comment by wojtek0806** [comment]
this is now resolved
