### ISSUE TITLE
The negative (invalid "`patch['session']`) cases are exercised in `test_pool.py`

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-common-python#1140]
In `/f5/bigip/tm/ltm/test/functional/test_pool.py::TestPoolMembersCollection.test_session_modify`

we should add assertions about (at least) two more cases:

1.  "`patch['session'] = 'NOTAVALIDSTRING'`"
and
2.   "`patch['session'] = ''"

**Comment by wojtek0806** [comment]
this has been merged
