### ISSUE TITLE
Add support for 3 options of LTM Profile HTTP

### ISSUE THREAD

**Issue by gabrielfortin** [F5Networks/f5-common-python#1145]
There are three options in LTM Profile HTTP that are not supported and I would like to be able to load and update : enforcement, explicit_proxy and sflow.

enforcement {
excess-client-headers [disabled | enabled]
excess-server-headers [disabled | enabled]
max-header-size [integer]
max-header-count [integer]
max-requests [integer]
oversize-client-headers [disabled | enabled]
oversize-server-headers [disabled | enabled]
pipeline [allow | pass-through | reject]
truncated-redirects [disabled | enabled]
unknown-method [allow | pass-through | reject]
}

explicit-proxy {
enabled [no | yes]
dns-resolver [dns-resolver]
tunnel-name [tunnel]
route-domain [route-domain]
default-connect-handling [deny | allow]
connect-error-message ["string"]
dns-error-message ["string"]
bad-request-message ["string"]
bad-response-message ["string"]
}

sflow {
poll-interval [integer]
poll-interval-global [no | yes]
sampling-rate [integer]
sampling-rate-global [no | yes]
}

**Comment by caphrim007** [comment]
@GabrielFortin options are automatically supported once the resource itself is part of the API.

So, for the collection "HTTPs" (plural, NOT secure HTTP) there is this

https://github.com/F5Networks/f5-common-python/blob/development/f5/bigip/tm/ltm/profile.py#L441

And for the resources in that collection, there is the HTTP resource here

https://github.com/F5Networks/f5-common-python/blob/development/f5/bigip/tm/ltm/profile.py#L450

So, by convention, this means that you automatically already have access to all the mentioned options you're looking for.

Here is the payload for enforcement

```
      "enforcement": {
        "excessClientHeaders": "reject",
        "excessServerHeaders": "reject",
        "knownMethods": [
          "CONNECT",
          "DELETE",
          "GET",
          "HEAD",
          "LOCK",
          "OPTIONS",
          "POST",
          "PROPFIND",
          "PUT",
          "TRACE",
          "UNLOCK"
        ],
        "maxHeaderCount": 64,
        "maxHeaderSize": 32768,
        "maxRequests": 0,
        "oversizeClientHeaders": "reject",
        "oversizeServerHeaders": "reject",
        "pipeline": "allow",
        "truncatedRedirects": "disabled",
        "unknownMethod": "allow"
      },
```

which can be represented as a python `dict` like so

`profile.https.http.create(enforcement=dict(maxHeaderCount=100))`

Here is the payload for explicit-proxy

```
      "explicitProxy": {
        "defaultConnectHandling": "deny"
      },
```

which can be represented as a python `dict` also like so

`profile.https.http.create(explicitProxy=dict(defaultConnectHandling="deny"))

Here is the payload for sflow.

```
      "sflow": {
        "pollInterval": 0,
        "pollIntervalGlobal": "yes",
        "samplingRate": 0,
        "samplingRateGlobal": "yes"
      },
```

which can be represented as a python `dict` also like so

`profile.https.http.create(sflow=dict(pollInterval=0))`

**Comment by gabrielfortin** [comment]
Ok, thank you very much!

**Comment by caphrim007** [comment]
@GabrielFortin closing this as I think you have what you need. if not, let us know
