### ISSUE TITLE
Typo(s)/missing code in monitor.py

### ISSUE THREAD

**Issue by mikejoh** [F5Networks/f5-common-python#1147]
Hi,

The class `Https` in `/f5-common-python/f5/bigip/tm/ltm/monitor.py` seems to have the wrong name, shouldn't it be called `Http_s` and reference `Http` instead of `Https` in the `super()`-call?

Also Http attributes are missing in the `self._meta_data['allowed_lazy_attributes']` of the `Monitor` class.

**Comment by caphrim007** [comment]
@mikejoh it has the correct name. The _s thing is reserved for collections that already end with an 's'.

Using your example, Http is "Https" like a plural http, and Https is Https_s.

I'd have to look at the allowed attr thing.

**Comment by mikejoh** [comment]
@caphrim007 OK, thanks for the clarification!
