### ISSUE TITLE
I want to modify the node status and get the Current Connections data

### ISSUE THREAD

**Issue by opsconquer** [F5Networks/f5-common-python#1148]
Hello,

I want to modify the node status and get the Current Connections data。
But the node state is readable。

n=mgmt.tm.ltm.nodes.node.load(name='pooltest', partition='Common')
print(n.state)
n.state = 'Disable'  #invalid property value
n.update()

And current Connections does not have that attribute
what should I do？

Thanks.

**Comment by wojtek0806** [comment]
You can only set the following states manually: user-up, user-down

This applies to both modify() and update() methods:

https://github.com/F5Networks/f5-common-python/blob/development/f5/bigip/tm/ltm/node.py#L107

This applies to both: REST and TMSH:
```
root@(ltm3restlab)(cfg-sync Standalone)(ModuleNotLicensed:Active)(/Common)(tmos)# modify ltm 
node 192.168.15.15 state
Values:
  user-down   user-up
```

**Comment by opsconquer** [comment]
hello

@wojtek0806 Thanks！

n=mgmt.tm.ltm.nodes.node.load(name='pooltest', partition='Common')
print n.raw

{u'kind': u'tm:ltm:node:nodestate', u'logging': u'disabled', u'name': u'pooltest', u'state': u'user-down', u'generation': 43, u'partition': u'Common', u'monitor': u'default', u'rateLimit': u'disabled', u'session': u'user-enabled', u'dynamicRatio': 1, '_meta_data': {'reduction_forcing_pairs': [('enabled', 'disabled'), ('online', 'offline'), ('vlansEnabled', 'vlansDisabled')], 'container': <f5.bigip.tm.ltm.node.Nodes object at 0xf4a5d0>, 'exclusive_attributes': [], 'allowed_commands': [], 'read_only_attributes': ['ephemeral', 'address'], 'allowed_lazy_attributes': [<class 'f5.bigip.resource.Stats'>], 'uri': u'https://172.16.139.111:443/mgmt/tm/ltm/node/~Common~pooltest/', 'required_json_kind': 'tm:ltm:node:nodestate', 'bigip': <f5.bigip.ManagementRoot object at 0x7f86065e54d0>, 'icontrol_version': '', 'required_command_parameters': set([]), 'icr_session': <icontrol.session.iControlRESTSession object at 0x7e2390>, 'required_load_parameters': set(['name']), 'required_creation_parameters': set(['partition', 'name', 'address']), 'creation_uri_frag': '', 'object_has_stats': True, 'creation_uri_qargs': {u'ver': [u'11.5.4']}, 'minimum_version': '11.5.0'}, u'connectionLimit': 0, u'address': u'11.1.1.1', u'ratio': 1, u'fullPath': u'/Common/pooltest', u'selfLink': u'https://localhost/mgmt/tm/ltm/node/~Common~pooltest?ver=11.5.4', u'description': u'new description'}

But does not get the current number of connections for that node！
Current Connections?
what should I do？

**Comment by wojtek0806** [comment]
You are probably looking for stats endpoint, the below will get you a raw stats output:

For example:
```
https://yourltm/mgmt/tm/ltm/node/~Common~192.168.15.15/stats
```
This can be achieved in SDK with:

````
from f5.bigip import ManagementRoot
mr = ManagementRoot('yourltm', 'user', 'pass')
node = mr.tm.ltm.nodes.node.load(name='192.168.15.15', partition='Common')
stats = node.stats.load()

The above will give you raw stats in a json blob.

````
If you want to access those using dot notation you can use the utility I have built, please bear in mind as it is a very early release of that so some endpoints might not work, the more people use it and report issues etc, the better i can make it:

https://github.com/F5Networks/f5-common-python/blob/development/f5/utils/responses/test/functional/test_handlers.py

In the SDK this will work like so:
````
from f5.utils.responses.handlers import Stats
from f5.bigip import ManagementRoot

mr = ManagementRoot('yourltm', 'user', 'pass')
node = mr.tm.ltm.nodes.node.load(name='192.168.15.15', partition='Common')

node_stat = Stats(node.stats.load())

>>> node_stat.stat.curSessions.value
Out[10]: 2

>>> node_stat.stat.serverside_curConns.value
Out[10]: 10

````
In case i misunderstood you and you want connection table output we do not have this endpoint in the SDK yet, in REST it is accessible under:

``
https://yourltm/mgmt/tm/sys/performance/connections

``
Probably you can work around this by using TMSH over REST and issuing TMSH commands but it depends if this is what you want.

**Comment by opsconquer** [comment]
@wojtek0806  Thanks very much ! :+1:

**Comment by caphrim007** [comment]
@opsconquer did @wojtek0806's answer satisfy? or did you want us to create an issue to add the /mgmt/tm/sys/performance/connections API?

**Comment by rathid** [comment]
when will bw stats will be available for all end points like pool members. if it available kindly some one direct me

**Comment by wojtek0806** [comment]
you can use stats for pools too, most of endpoints have this enabled.
