### ISSUE TITLE
Return an empty list rather than AttributeError (class 'f5.bigip.tm.ltm.virtual.Virtual.rules')

### ISSUE THREAD

**Issue by ghost** [F5Networks/f5-common-python#1170]
Hello pyGurus!

Originating from answer at DevCentral (https://devcentral.f5.com/questions/need-help-on-f5-automation-to-read-the-irules-attached-t-all-the-virtual-servers-55140). Accepted answer contains a code sample.

When Virtual Server has no iRules attached to it, an empty list should be returned when 'vserver.rules' is called. Today it returns `AttributeError: '<class 'f5.bigip.tm.ltm.virtual.Virtual'>' object has no attribute 'rules'`.

This is problematic in for-cycle iterations. If one Virtual Server happens to have no iRules, then script work is prematurely terminated

Regards,

**Comment by caphrim007** [comment]
@hannesrapp ahh. seems like another API-ism that needs to be covered.

**Comment by caphrim007** [comment]
proposed fix is here https://github.com/F5Networks/f5-common-python/pull/1195
