### ISSUE TITLE
Example code in README doesn't work.

### ISSUE THREAD

**Issue by zlesnr** [F5Networks/f5-common-python#1276]
I've copy and pasted the example in the README and updated the `print` statements for python3 compatibility.  I get the following.

```
Traceback (most recent call last):
  File "first.py", line 1, in <module>
    from f5.bigip import ManagementRoot
  File "/Users/zleslie/.pyenv/versions/3.6.1/lib/python3.6/site-packages/f5/bigip/__init__.py", line 20, in <module>
    from icontrol.session import iControlRESTSession
ModuleNotFoundError: No module named 'icontrol'
```

**Comment by zlesnr** [comment]
Seems like a dependency issue with the pip package.

**Comment by jasonrahm** [comment]
I just installed python 3.6.2, created a virtual environment with that version, installed the sdk via pip, and ran the example code just fine. The icontrol module is in the setup requirements. Can you try again?

**Comment by caphrim007** [comment]
@jasonrahm it used to not be there (a problem with our packaging that fixed when I did the 3.x work). It should be fixed now. If @zlesnr doesn't have any issue in the next couple hours, I think it's acceptable to close this by end-of-day

**Comment by zlesnr** [comment]
If the dependencies have been sorted out, sounds like this is done.  Thanks.
