### ISSUE TITLE
Is the REST API available for version 11.4?

### ISSUE THREAD

**Issue by opsconquer** [F5Networks/f5-common-python#1281]
https://devcentral.f5.com/articles/demystifying-icontrol-rest-part-6-token-based-authentication

Introduced back in TMOS version 11.4 as an early access feature but released fully in version 11.5.

Text: u'{"code":404,"message":"http://localhost:8100/mgmt/tm/sys/","restOperationId":64681129,"errorStack":["com.f5.rest.common.RestWorkerUriNotFoundException: http://localhost:8100/mgmt/tm/sys/","at com.f5.rest.common.RestServer.trySendInProcess(RestServer.java:126)","at com.f5.rest.common.RestRequestReceiver.dispatchToService(RestRequestReceiver.java:93)","at com.f5.rest.common.RestRequestReceiver.processNext(RestRequestReceiver.java:57)","at com.f5.rest.common.RestHelper$2.run(RestHelper.java:1480)","at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)","at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)","at java.lang.Thread.run(Unknown Source)\\n"]}'

If 11.4 is available using the REST API, what should I do?

**Comment by wojtek0806** [comment]
This library is only tested to be working in 11.5 x and up maintenance releases. So in short the answer is use at your own peril. Also 11.4.x is out of support in general so we will never backport.
