### ISSUE TITLE
I need help to connect the this sdk to my Application

### ISSUE THREAD

**Issue by Ironman-india** [F5Networks/f5-common-python#1282]
Hi All,

I plan to use a application, where i can graphical window can open and create the VIP, POOL , Node and all 
I have done some basic codes and dont know how to sent the codes to F5 API rest control with libery
" Request' with json format
 
https://github.com/Ironman-india/F5-SDK-Python

I need codes for all this codes to mingle with my codes , when i click on create vip ,
it should create new VIP in f5 box

**Comment by caphrim007** [comment]
@Ironman-india I think you're on your own with this request.

There are many examples of using the f5-sdk included in this repository here in the various `test/` directories. If you want to use python requests, then you should get a tool like Postman and explore the F5 API by navigating to the /mgmt/ API endpoint; eg: https://bigip.org.com/mgmt/
