### ISSUE TITLE
When i run the setup.py , i am getting below error?

### ISSUE THREAD

**Issue by Ironman-india** [F5Networks/f5-common-python#1285]
>>> 
 RESTART: C:\Users\krissara\Documents\Python\f5-common-python-development\f5-common-python-development\setup.py 
install_requires <map object at 0x02F05D70>
>>> >>>
 RESTART: C:\Users\krissara\Documents\Python\f5-common-python-development\f5-common-python-development\setup.py
install_requires <map object at 0x02F05D70>

**Comment by wojtek0806** [comment]
we need full error trace, please retest with 3.0.1 release first tho

**Comment by wojtek0806** [comment]
@Ironman-india closing as inactive feel free to reopen if issue persists
