### ISSUE TITLE
Exists on profiles under a virtual server seems to always return True

### ISSUE THREAD

**Issue by pffs** [F5Networks/f5-common-python#1286]
When testing to see if a particular profile is attached to a virtual server, it seems to return true regardless of whether or not the profile is attached, or even if it exists at all. 

```python
>>> mr = ManagementRoot(f5_host, f5_user, f5_password)
>>> v = mr.tm.ltm.virtuals.virtual.load(name='https', partition='Common')
>>> [x.name for x in v.profiles_s.get_collection()]
[u'cssl.app', u'cssl.home', u'http', u'cssl.pr', u'tcp']
>>> v.profiles_s.profiles.exists(name='cssl.app', partition='Common')
True
>>> v.profiles_s.profiles.exists(name='cssl.unknown', partition='Common')
True
```
Works just fine on checking if the profile itself exists, though.
```python
>>> mr.tm.ltm.profile.client_ssls.client_ssl.exists(name='cssl.app', partition='Common')
True
>>> mr.tm.ltm.profile.client_ssls.client_ssl.exists(name='cssl.unknown', partition='Common')
False
```
Current versions:
``` bash
$ pip freeze | grep f5
f5-icontrol-rest==1.3.0
f5-sdk==2.3.3
```
```
Python 2.7.9 (default, Jun 29 2016, 13:08:31)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by caphrim007** [comment]
@pffs what version of bigip? I'm not getting the same result with 13.0

**Comment by pffs** [comment]
Currently testing against 11.6

**Comment by caphrim007** [comment]
.0 or .1 or a hotfix?

tmsh show sys software would be helpful.

**Comment by pffs** [comment]
```
---------------------------------------------------
Sys::Software Status
Volume  Product  Version    Build  Active    Status
---------------------------------------------------
HD1.1    BIG-IP   11.6.0  0.0.401     yes  complete
HD1.2      none     none     none      no  complete
```

**Comment by caphrim007** [comment]
ok, just plain `.0`

**Comment by caphrim007** [comment]
ok, i can verify this is the case. I suppose its some bug in 11.6.0 that is being reflected by the sdk

**Comment by caphrim007** [comment]
geez, 11.6.0 will return a valid request regardless of what you send in a payload. cmon 11.6.....

**Comment by pffs** [comment]
For what it's worth, I upgraded the vm to 11.6.1 (no hotfix) and it responds as expected.

**Comment by caphrim007** [comment]
@pffs ok. presumably it's a bug somewhere in 11.6.0. I have a fix incoming

**Comment by caphrim007** [comment]
@pffs fix is in devel if you want to install that. otherwise, will be released in next patch release

**Comment by chango73** [comment]
Hello,
just an information... How can I get the http profile (client) and SSL profile (client) from virtual server?
