### ISSUE TITLE
Object is not in a folder: type: devicegroup id: ","errorStack":[]} - fetching device groups

### ISSUE THREAD

**Issue by ghost** [F5Networks/f5-common-python#1295]
Hi,

I might have found a potential bug in F5-bigip.

When I try to list all the device-group objects through 
GET https://IP/mgmt/tm/cm/device-group/

I get:
{"code":400,"message":"01070712:3: Internal error, object is not in a folder: type: devicegroup id: ","errorStack":[]}

Going through the CLI yields the same results:
(tmos)# list cm device-group 
01070712:3: Internal error, object is not in a folder: type: devicegroup id: 

But listing individual device-group objects works fine:
GET https://IP/mgmt/tm/cm/device-group/devGroup1
(tmos)# list cm device-group devGroup1

In my use case I do not know the name of the device-groups at the F5-bigip device beforehand. So I need a way to list all the device-groups. 

How do you recommend me to proceed?

Best Regards,
Hoa

**Comment by caphrim007** [comment]
@hoa047 what version of bigip are you using? This works without issue (for me) on 13.0.0.

Perhaps you can elaborate on your configuration?

**Comment by wojtek0806** [comment]
@hoa047 closing as inactive, feel free to reopen if this is still an isue
