### ISSUE TITLE
How to add an existing node to a pool?

### ISSUE THREAD

**Issue by zlesnr** [F5Networks/f5-common-python#1297]
I've been able to create a few nodes, but now how do I add those nodes to a pool as members?

**Comment by jasonrahm** [comment]
a node by definition is an ip address, a poolmember is an ip+port.  So first, load the pool you want to add a pool member to, then create the member:

```
>>> pool = b.tm.ltm.pools.pool.load(name='testpool')
>>> pm = pool.members_s.members.create(name='10.10.10.100:80', partition='Common')
```

**Comment by zlesnr** [comment]
Thank you for the response.  That seems different than what exists in the UI, when you create a node, then select a node from a list of existing nodes to add to a pool.  I'll give it a test.  My goal is to use a node multiple times on different ports.

**Comment by jasonrahm** [comment]
you can absolutely have multiple services on a node, you just don't technically add a node to a pool, you add a pool member, which is that node+service port. This is the same behavior in the UI, though perhaps a little more ambiguous as there is additional node work you CAN (but don't have to) do.

**Comment by zlesnr** [comment]
I've had a chance to test.  The `create()` was able to add the member, but now I'm looking at modifying certain aspects after creation.  How do I map the code in this repo to what is in the API, or the LTM command, for that matter?  I'd like to be able to get a list of the members that are already present, for example to ensure that I don't try to add a node that already exists as a member on a pool.

**Comment by jasonrahm** [comment]
the get_collection method works on a collection and subcollection. So at the level of pool, you use it like:

b.tm.ltm.pools.get_collection()

and with pool members, after you have loaded a pool with the load() method to a variable (assume mypool), you can collect the members like:

mypool.members_s.get_collection()

You can also use the exists() method to test for presence before trying to create.

It sounds like we need to do a much better job documenting the sdk.

**Comment by zlesnr** [comment]
Yes, documentation would be appreciated.  I've got a pile of items I'd like to automate, which are quite common for our use.

**Comment by jasonrahm** [comment]
Ok, we'll work to improve the documentation. Closing this issue as it is unrelated to that work.
