### ISSUE TITLE
Add /mgmt/tm/ltm/node endpoints

### ISSUE THREAD

**Issue by wilpig** [F5Networks/f5-common-python#1302]
It would be nice to have a quick way to list all of the nodes that are present on the system to use when hunting for IPs that haven't been removed after a system has been decommissioned, etc.

**Comment by caphrim007** [comment]
@wilpig does `mgmt.tm.ltm.nodes.get_collection()` not do this?

**Comment by wilpig** [comment]
Yes it is and I somehow over looked it when I listed out the methods.

**Comment by caphrim007** [comment]
@wilpig enjoy
