### ISSUE TITLE
The coding example for the User Guide is misleading

### ISSUE THREAD

**Issue by penghon** [F5Networks/f5-common-python#1303]
https://f5-sdk.readthedocs.io/en/latest/userguide/ltm_pools_members_code_example.html

"#Create members on pool_1
members = pool_1.members_s
member = pool_1.members_s.members

m1 = pool_1.members_s.members.create(partition='Common', name='m1:80')
m2 = pool_1.members_s.members.create(partition='Common', name='m2:80')"

The above would only work if the node m1 or m2 were previously created. 
Please change either the above comment or add in the addresses for node m1 or m2.

**Comment by jasonrahm** [comment]
I am working on some documentation updates this month, I will update this example when I do

**Comment by jasonrahm** [comment]
This coding example has been updated to be more clear.
