### ISSUE TITLE
Dict comprehension prevents library usage on Centos6.9 (python 2.6)

### ISSUE THREAD

**Issue by broferek** [F5Networks/f5-common-python#1304]
Hi,

There is a dict comprehension used here : 
File "/usr/lib/python2.6/site-packages/f5/bigip/resource.py", line 724
no_meta_dict = {k: v for k, v in iteritems(self.__dict__)

This prevents the library from being used on Centos6.9 with Python 2.6.

This is a big issue for us as since Ansible 2.4 update, all BigIP modules uses f5-sdk library and we can not use them anymore on our Centos6.9 servers.

I have opened this issue on Ansible side : https://github.com/ansible/ansible/issues/31341 which was closed as this is an issue on this side.

Is Python 2.6 still supported? If yes, dict comprehension should not be used

Thanks,

Ludo

**Comment by caphrim007** [comment]
@broferek, we can fix this, but to answer your question, "no" 2.6 is not supported

**Comment by broferek** [comment]
Cool, the fix would be really appreciated as centos6.9 is still active for a while

Thanks

Ludo

**Comment by caphrim007** [comment]
@broferek fixing that wont guarantee that the rest of the sdk will work. We're not going to support 2.6, but changing that dict comprehension to something else is possible.

**Comment by wojtek0806** [comment]
@caphrim007 @broferek  Let me jump in here and say that i am against changing code which is perfectly readable.  First reason is already mentioned( no support or 2.6)second reason is that we also have changed set declarations (using curly bracers only rather than set()) which are not compatibile with 2.6. There are some other changes i made i do not remeber now but yeah this code will not run on 2.6.

**Comment by wojtek0806** [comment]
Closing as wont fix

**Comment by chen23** [comment]
@broferek @caphrim007 @wojtek0806   if you are stuck on CentOS 6.9 you may want to try SCL: https://wiki.centos.org/AdditionalResources/Repositories/SCL 

Provides python 2.7 that does not conflict with the system python.  It does require that go through some extra steps to load the environment.

https://www.softwarecollections.org/en/scls/rhscl/python27/

I've used this before in the past.

**Comment by wojtek0806** [comment]
good call @chen23

**Comment by broferek** [comment]
thanks @chen23 we are not really stuck on Centos6.9 and we actually need to go forward and that issue could be the good starting point to migrate to Centos7.

@wojtek0806 I have just installed a test VM with Centos7 but now we get an issue with BigIP authentication. It returns the following issue.
Our BigIP is running version 11.5 with icrd started.

We have looked at many threads but could not find the root cause yet.

The full traceback is:
  File "/tmp/ansible_6irdDl/ansible_modlib.zip/ansible/module_utils/f5_utils.py", line 237, in __init__
    f5_product_name, **self._connect_params
  File "/tmp/ansible_6irdDl/ansible_modlib.zip/ansible/module_utils/f5_utils.py", line 262, in _get_mgmt_root
    token='tmos'
  File "/usr/lib/python2.7/site-packages/f5/bigip/__init__.py", line 124, in __init__
    self.post_configuration_setup()
  File "/usr/lib/python2.7/site-packages/f5/bigip/__init__.py", line 91, in post_configuration_setup
    self._get_tmos_version()
  File "/usr/lib/python2.7/site-packages/f5/bigip/__init__.py", line 96, in _get_tmos_version
    response = connect.get(base_uri)
  File "/usr/lib/python2.7/site-packages/icontrol/session.py", line 258, in wrapper
    response = method(self, REST_uri, **kwargs)
  File "/usr/lib/python2.7/site-packages/icontrol/session.py", line 427, in get
    return self.session.get(uri, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 450, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 381, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 308, in prepare
    self.prepare_auth(auth, url)
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 495, in prepare_auth
    r = auth(self)
  File "/usr/lib/python2.7/site-packages/icontrol/authtoken.py", line 203, in __call__
    self.get_new_token(netloc)
  File "/usr/lib/python2.7/site-packages/icontrol/authtoken.py", line 109, in get_new_token
    response=response)

MSG:

404 Unexpected Error: Not Found for uri: https://dc1-net-prod-lb-03.prod.dc1.kelkoo.net:443/mgmt/shared/authn/login
Text: u'{"code":404,"message":"http://localhost:8100/mgmt/shared/authn/login","restOperationId":890460,"errorStack":["com.f5.rest.common.RestWorkerUriNotFoundException: http://localhost:8100/mgmt/shared/authn/login","at com.f5.rest.common.RestServer.trySendInProcess(RestServer.java:231)","at com.f5.rest.common.RestRequestReceiver.dispatchToService(RestRequestReceiver.java:93)","at com.f5.rest.common.RestRequestReceiver.processNext(RestRequestReceiver.java:57)","at com.f5.rest.common.RestHelper$2.run(RestHelper.java:1910)","at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)","at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)","at java.lang.Thread.run(Thread.java:745)\\n"]}'

**Comment by wojtek0806** [comment]
Reopening for this discussion, I noticed you are using ansible modules which are guaranteed to work on 12.x. From the traceback it seems we are using tokens, which were introduced in 12.x. Can you put some more information on what ansible module/playbook you are using? I suspect this discussion would have to be moved to f5_ansible github but let me verify this first. @broferek

**Comment by broferek** [comment]
Yes, this is affecting the module bigip_pool http://docs.ansible.com/ansible/latest/bigip_pool_module.html
The requirement on this page is bigip >=11 . Maybe outdated?

**Comment by wojtek0806** [comment]
Yeah i think this needs updated. what do you think @caphrim007 ?

**Comment by broferek** [comment]
Other Ansible modules require BigIP > 12.0.0 such as http://docs.ansible.com/ansible/latest/bigip_sys_db_module.html
So I think this is a doc issue on Ansible side. 

On our side, we will upgrade our BigIP to 12.0.0 tomorrow.

I'll let you know once we can test.

**Comment by caphrim007** [comment]
@wojtek0806 broferek was using 11.5, not 12. It's YMMV on versions less than 12.

**Comment by wojtek0806** [comment]
i know he was i was asking if this is a case of docs mistake :)

**Comment by wojtek0806** [comment]
if you run into ansible issues, please open on ansible github, i will close this one @broferek

**Comment by caphrim007** [comment]
open an issue for ansible at the **F5 Ansible** github, not the "Ansible" github.

the correct link is here
https://github.com/F5Networks/f5-ansible/issues

**Comment by wojtek0806** [comment]
yea that is what i meant :) typing on the phone sorry :)
