### ISSUE TITLE
Create draft policy error

### ISSUE THREAD

**Issue by hygorxxx** [F5Networks/f5-common-python#1312]
When i'm trying to create a draft policy i'm receiving the following message

`>>> x = mgmt.tm.ltm.policys.policy.draft(name='policy_docker',partition='Common', subPath='Drafts', strategy='Common/first-match')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/f5/bigip/tm/ltm/policy.py", line 171, in draft
    super(Policy, self)._modify(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/f5/bigip/resource.py", line 393, in _modify
    self._prepare_put_or_patch(patch)
  File "/usr/local/lib/python2.7/dist-packages/f5/bigip/resource.py", line 427, in _prepare_put_or_patch
    update_uri = self._meta_data['uri']
KeyError: 'uri'
`

i'm using tmos 13.0 and tried also in 12.1

**Comment by caphrim007** [comment]
@hygorxxx does the policy exist before you attempt to draft it?

**Comment by hygorxxx** [comment]
@caphrim007 Yes, the policy is already published.

**Comment by caphrim007** [comment]
@hygorxxx ok, then to use it, the methods like draft and publish require that the resource be `load`ed first.

so first do a

`policy = tm.ltm.policys.policy.load(name='policy_docker', partition='Common')`

and from there do

`policy.draft()`

**Comment by hygorxxx** [comment]
@caphrim007 Great. You're right, i did the load first and it worked. Thanks.
