### ISSUE TITLE
Add records subcollection for fdb tunnels

### ISSUE THREAD

**Issue by jlongstaf** [F5Networks/f5-common-python#1348]
I need to use the SDK to work with the records subcollection of tm/net/fdb/tunnel. I need to:

Create a single record:
POST to tm/net/fdb/tunnel/<my tunnel name>/records/

and delete a single record:
DELETE tm/net/fdb/tunnel/<my tunnel name>/records/<name>

iControl REST supports these operations, but the SDK does not appear to have records subcollection.

**Comment by jasonrahm** [comment]
Hi @jlongstaf, what's the priority for you on this? I have a couple other things I was going to add and test, but can prioritize this if it's important.

**Comment by jlongstaf** [comment]
@jasonrahm: Thanks for your quick response. This is a relatively high priority for us, as we need this to resolve an SR opened by an OpenStack customer (SR 1-3607037061 ). That said, we can work within your schedule. Just let me know when you think it can get scheduled and I'll update our customer.

Thanks for your help.

**Comment by jasonrahm** [comment]
I'll try to knock this out for Friday's release

**Comment by jlongstaf** [comment]
Thanks!

**Comment by jasonrahm** [comment]
@jlongstaf, do you have an example record I can work with?

**Comment by jlongstaf** [comment]
@jasonrahm 
From Scott Peters:
POST (CREATE) to the sub-collection of records associated with the FDB Tunnel.
`tm/net/fdb/tunnel/<my tunnel name>/records/`

If you POST to an already existing item you will get an error stating it already exists: 
“01020066:3: The requested L2 forward tunnel (/Common/mytunnel 11:11:11:11:11:22) already exists in partition Common.”

`DELETE tm/net/fdb/tunnel/<my tunnel name>/records/<name field>`

For my testing I used this record:
`{"name":"02:47:14:a8:82:0b","endpoint":"192.168.130.11"}`

For create, POST above record in body to :
`https://10.128.1.136:443/mgmt/tm/net/fdb/tunnel/~Common~http-tunnel/records`

For delete, use the name field (02:47:14:a8:82:0b):
`https://10.128.1.136:443/mgmt/tm/net/fdb/tunnel/~Common~http-tunnel/records/02:47:14:a8:82:0b`
 
Let me know if you need more information.

**Comment by jlongstaf** [comment]
@jasonrahm 
My original DELETE statement was not correct (sorry). It should read:


`DELETE tm/net/fdb/tunnel/<my tunnel name>/records/<name field>`

Corrected above comment.

**Comment by jasonrahm** [comment]
this has been merged to development and will be included in Friday's release. Closing this issue.
