### ISSUE TITLE
Enhancement: support for revoke license

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-common-python#1357]
TMOS 13.1.x supports revoking a license via iControl REST.

https://support.f5.com/kb/en-us/products/big-ip_ltm/releasenotes/product/relnote-bigip-ve-13-1-0.html#unique_656977381

tmsh: revoke sys license

**Comment by chen23** [comment]
iControl REST:
```
curl -v -k -s -u admin:admin -H "Content-Type: application/json" -d '{"command":"revoke"}' -X POST https://192.168.1.245/mgmt/tm/sys/license
```

**Comment by jasonrahm** [comment]
can you point me to the documentation for this endpoint @chen23? Is revoke the only option? I'd like to get this built and merged by Friday's release.

**Comment by jasonrahm** [comment]
do you know what a successful result should be @chen23? I'm getting:

"commandResult": "Unknown exception during ping ://:8080\n"

I am seeing the tmsh command executed appropriately in the audit log, but I'm not sure what (if anything) it actually did. Do you know the specifics of what kinds of licenses it revokes? And what that means to the operational state of the BIG-IP?

**Comment by jasonrahm** [comment]
this has been merged to development @chen23, can you test and confirm before I close this issue?

**Comment by chen23** [comment]
Yes, this works.  Thanks.

**Comment by jasonrahm** [comment]
good deal, closing this out.
