### ISSUE TITLE
atribute error when no description provided

### ISSUE THREAD

**Issue by wdauchy** [F5Networks/f5-common-python#1360]
I am getting attributeError when trying to access description for a server which has no description.
> AttributeError: '<class 'f5.bigip.tm.ltm.pool.Members'>' object has no attribute 'description'

Is there a way to avoid this and make sure all attributes are created (maybe return None if empty?); so we can access them in a unified way.

Thanks

**Comment by jasonrahm** [comment]
This isn’t likely. Your best option is to test for the attribute before accessing:

hasattr(obj, ‘attr’)
