### ISSUE TITLE
Need an unnamed resource to tet the version details of a bigip.

### ISSUE THREAD

**Issue by Preyansh91** [F5Networks/f5-common-python#1386]
There is a  method to get the version running on bigip where we can use tmos_version, but there is no option in the source code to get the version details which we get from /mgmt/tm/sys/version. Sometimes details like build, product  etc are required, like for automating oprofiles for performance tests.

**Comment by caphrim007** [comment]
@Preyansh91 so you're asking for an SDK API to /mgmt/tm/sys/version?

**Comment by Preyansh91** [comment]
yes just like we have to /mgmt/tm/sys/dns....I checked it out in the code. We have a class Dns in dns.py under the f5/bigip/tm/sys/ folder which inherits from the Unnamed resource. If we can add a file like version.py it would be great because we need those stats for our oprofiles automation. If you permit I can submit the code for the same with unit and functional tests.
