### ISSUE TITLE
uptime endpoint?

### ISSUE THREAD

**Issue by vsnine** [F5Networks/f5-common-python#1399]
Noticed Jason's sys/clock updates and was reminded of this thread I made a few years ago on a way to query the uptime of a BIG-IP system over REST: https://devcentral.f5.com/questions/get-uptime-of-a-system-over-rest

Would this be something that could get added to the API? Do newer versions of REST API have a feasible way to obtain the uptime? Would it make sense to get it over the SOAP API?

Thanks.

**Comment by caphrim007** [comment]
@vsnine I'm not aware of such an endpoint. The method you have there would be the recommended way

**Comment by wojtek0806** [comment]
@vsnine the endpoint for that does not exist as far as I can see, so using tmsh over rest would be your best bet here. closing
