### ISSUE TITLE
ValueError: signal only works in main thread

### ISSUE THREAD

**Issue by vvoody** [F5Networks/f5-common-python#1433]
Hi, I used in Django runserver (dev) and uwsgi (production), same exception raised. It's due to signal cannot be used in non-main thread.

Currently I have to monkey-patch `HAS_SIGNAL = True` to `HAS_SIGNAL = False` in `f5/bigip/__init__.py`. Hope there will be an option to disable signal use. Thanks.

```
File "/usr/local/lib/python2.7/site-packages/f5/bigip/__init__.py", line 114, in post_configuration_setup
   self._get_tmos_version()
 File "/usr/local/lib/python2.7/site-packages/f5/bigip/__init__.py", line 120, in _get_tmos_version
   signal.signal(SIGALRM, timeout_handler)
ValueError: signal only works in main thread
```

I put my code in Django views to get results from my GTM. It only works when I pass `--noload --nothreading` to Django runserver.

Django:
```
django-admin runserver
```

uwsgi:
```
uwsgi --ini uwsgi-docker.ini

#######################
# content of uwsgi-docker.ini
#######################
[uwsgi]
projectname = xxx
base = /home/user/xxx


# Django-related settings
# the base directory (full path)
chdir           = %(base)
# Django's wsgi file
module          = xxx.wsgi:application

master          = true
processes       = 8
threads         = 2
enable-threads  = true
socket          = 0.0.0.0:8000
vacuum          = true

env = DJANGO_SETTINGS_MODULE=%(projectname).settings_env.prod
pythonpath = %(base)
pythonpath = %(base)/common_libs
pythonpath = %(base)/xxx
logto = %(base)/logs/uwsgi.log
buffer-size = 32768
# set max log file to about 100MB
log-maxsize = 100000000
log-backupname = %(base)/logs/uwsgi.log.last
```

**Comment by rcarpa** [comment]
Had a similar problem in a multi-threaded application. Gave a quick look to the source code. 

Signals are used only in one place: to timeout an API call to the load balancer during the object initialization. In meantime it introduces a lot of complications:
- The signal handler raises an exception and complicates any soft error handling (retry / graceful shutdown).
- Blocks usage in multi-threaded applications. 

Seems like the "requests" library used internally by the f5 library natively supports timeouts.  May be interesting to strip out any code related to signals and rely on timeouts provided by the "requests" library when doing this API call at initialization.

**Comment by caphrim007** [comment]
@At0mik the timeout in the requests library is not a hard timeout, it is a connect timeout The timeout in the sdk is a "give up" timeout.

The difference is that if you can connect at all, but the rest API hangs, you will never timeout with requests. Likewise, if reads are slow, you will also hang forever.

The sdk enforces a hard timeout so that the script is killed if it exceeds the timeout.

**Comment by rcarpa** [comment]
@caphrim007, thanks for the information. 
However, I'm still confused. This hard timeout is used by a single rest call in the entire library.  Is it a workaround for a bug in the API for the  "GET /tm/sys/" call?

**Comment by caphrim007** [comment]
It's used for that call because that call is the first call made when connecting to the device for the first time. The majority of the time out problems occur upon first connection. They almost never occur afterwards

**Comment by rcarpa** [comment]
You cited slow reads and API hangs. Are you aware of practical cases when API hanged while the F5 remained healthy at the routing/load balancing part? Seems like problems would mainly happen if the F5 is overloaded (CPU or network wise). Is my assumption true? Are you aware of other cases when sigalarm can be triggered? 

We consider disabling the signal related code because multi-threading is critical in our application. I try to asses the risk which comes with this change.

**Comment by wojtek0806** [comment]
@At0mik coming from F5 support background I have only seen API hangs when there was a CPU/Memory issue (leaning towards CPU consumption) so the unit overall would have to be in bad shape for the API not be responsive completely, and like @caphrim007 said you would know at first connection that something is up. There are also some other circumstances where API could hang, for example java Out of memory but this was more common in old version of TMOS: https://support.f5.com/csp/article/K38134424 

Have we answered your question sufficiently? if so are we ok to close this issue ?

**Comment by jobec** [comment]
I bumped into the same thing.

This effectively makes this library useless in multi-threaded environments without doing dirty hacks like monkey patching.

**Comment by caphrim007** [comment]
@jobec this has already been fixed in https://github.com/F5Networks/f5-common-python/commit/a97a2ef2abb9114a2152453671dee0ac2ae70d1f it is waiting for a release window to be released to the public. you can install the ff5-sdk from github here to get it now

**Comment by jobec** [comment]
When would that release window be?

**Comment by caphrim007** [comment]
@jobec this friday

**Comment by rcarpa** [comment]
@wojtek0806, thank you for the answer. It's exactly what I hoped to learn.

**Comment by jobec** [comment]
Looks like the release window was missed?

**Comment by caphrim007** [comment]
@jobec thanks for the reminder. F5's Agility conference was this last weekend so the devs were tied up in that. Releasing now.

**Comment by caphrim007** [comment]
@jobec this is now available
