### ISSUE TITLE
CPU, memory, disk usage and http profile using the BIG-IP Python SDK

### ISSUE THREAD

**Issue by Mike997** [F5Networks/f5-common-python#1436]
It seems like the following endpoints are missing from the SDK, is that indeed the case or are they placed somewhere else? If not, would it be possible to add them unless there was a reason not to?
Statistics for:
CPU
Memory
Disk
Http profiles
The REST endpoints are: mgmt/tm/sys/hostInfo (for CPU and memory) mgmt/tm/sys/disk/logical-disk (for disks) mgmt/tm/ltm/profile/http/stats (for http profile)

**Comment by wojtek0806** [comment]
@Mike997  the http profile stats just need to be enabled on the collection, but the other 3 listed are not there, when do you need this by ?

**Comment by Mike997** [comment]
The sooner the better, I can work around it by creating an ugly workaround and poll the rest interface directly for some metrics, but I'd be grateful with whatever you can do :)

**Comment by Mike997** [comment]
Based on the release schedule 3.0.15 will be out soon'ish, right? Do you think that it'll be possible to have the profile stats and the three missing ones available in that release?

**Comment by wojtek0806** [comment]
@Mike997 I cannot make any promises as this depends if the tests pass on the new code, I will paste a link to my repository that has the untested code so you can take it for a spin in the meantime, i hope this helps. 

It is worth mentioning that hostInfo endpoint presents data the same way /stats/ endpoints do. In short term it will not be pretty, but given that we have another endpoint like this /sys/memory/ I think it will be worthwhile having this streamlined and making the output better. 

There is an utility that attempts to do this which I wrote but it needs some testing to catch various edge cases, but it is a start:  

https://github.com/F5Networks/f5-common-python/tree/development/f5/utils/responses

**Comment by Mike997** [comment]
Awesome, you're the best!

**Comment by Mike997** [comment]
Any idea of when 3.0.15 will be released? Last 10 versions was released every 8-15 days, but it's now been almost 2 months.

**Comment by caphrim007** [comment]
@Mike997 we release versions if and only if there are changes during the 2 week dev cycle. The last 2 months there have not been changes.

The last 2 weeks have seen several changes, so a release is being cut right now.

Generally speaking we release every 2 weeks on a Friday (or the coming weekend). This last friday was one of those dates. So feel free to add that cycle to your own calendar if need-be

**Comment by Mike997** [comment]
Great, thanks! So it should be on the 8th or so?

**Comment by caphrim007** [comment]
@Mike997 should be available now

**Comment by caphrim007** [comment]
if there are changes between this last friday and 2 weeks from this last friday, then there will be another release on the 8th. otherwise, we skip a date and wait for the next 2 week period to expire

**Comment by Mike997** [comment]
Thanks @caphrim007 ! You guys are awesome
