### ISSUE TITLE
Add security/nat endpoints (Firewall NAT)

### ISSUE THREAD

**Issue by bobyaaaaw** [F5Networks/f5-common-python#1445]
BigIP 12.1.0 added support for AFM Firewall NAT features.

related endpoints needed are:
 security/nat/source-translation
 security/nat/destination-translation
 security/nat/policy

**Comment by bobyaaaaw** [comment]
Please assign this to me. I've got this started, pull request coming soon.

**Comment by abhishekthukaram** [comment]
Hi Bob
This has already been written and submitted , in local repository of gitswarm
