### ISSUE TITLE
unable to pull wide-ip gtm irules

### ISSUE THREAD

**Issue by rduchez** [F5Networks/f5-common-python#1446]
Greetings

Thanks for the bang-up job on this sdk.  I ve been trying to figure out how to pull irules information from the wideip configuration. This is for inventory purposes.  

wideips = mgmt.tm.gtm.wideip.a_s.get_collection() 
for wideip in wideips:
     print wideip.name <--works
     print wideip.enabled <--works
     print wideip.poolLbMode <--works
     print wideip.rules <--Does not work 

can this be added to the sdk? 
Also was not able to figure out how to print pool members "elegantly"  is there a sub-collection to get? 

Thanks,

Romain

**Comment by jasonrahm** [comment]
Hi @rduchez, this works fine for me on BIG-IP 13.1.0.5 and sdk version 3.0.15:

```
>>> wideips = b.tm.gtm.wideips.a_s.get_collection()
>>> for wideip in wideips:
...     print wideip.rules
...     
[u'/Common/gtmtest']
```

What version fo SDK and BIG-IP are you using?

**Comment by jasonrahm** [comment]
ah...could be that some of your wideip's do not have rules associated? That attribute is missing on those if so. I added a second wideip to my box with no iRule and get error:

```
>>> wideips = b.tm.gtm.wideips.a_s.get_collection()
>>> for wideip in wideips:
...     print wideip.rules
...     
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "/Users/rahm/PycharmProjects/f5-common-python/f5/bigip/mixins.py", line 102, in __getattr__
    raise AttributeError(error_message)
AttributeError: '<class 'f5.bigip.tm.gtm.wideip.A'>' object has no attribute 'rules'
```

But if I check for the attribute before printing it works fine:

```
>>> for wideip in wideips:
...     print wideip.name
...     if hasattr(wideip, 'rules'):
...         print wideip.rules
...     print "\n\n" 
...     
test2.gtm.local



test.gtm.local
[u'/Common/gtmtest']
```

**Comment by wojtek0806** [comment]
@rduchez closing this issue at it seems @jasonrahm answered your question
