### ISSUE TITLE
Ability to load the examples

### ISSUE THREAD

**Issue by jasonrahm** [F5Networks/f5-common-python#1457]
Trying to load the example virtual, pool is met with a KindTypeMismatch due to the example being returned as a collection type:

KindTypeMismatch: For instances of type ''Virtual'' the corresponding kind must be ''tm:ltm:virtual:virtualstate'' but creation returned JSON with kind: u'tm:ltm:virtual:virtualcollectionstate'

**Comment by jasonrahm** [comment]
It feels kind of hacky, but I can change this:

```
        if new_instance.kind != new_instance._meta_data['required_json_kind'] \
           and new_instance.kind != "tm:transaction:commandsstate":
```

to this:

```
        if new_instance.kind != new_instance._meta_data['required_json_kind'] \
           and new_instance.kind != "tm:transaction:commandsstate" \
           and 'example' not in new_instance.selfLink.split('/')[-1]:
```

Thoughts @caphrim007?

**Comment by wojtek0806** [comment]
merged
