### ISSUE TITLE
Allow delete method on collections

### ISSUE THREAD

**Issue by jasonrahm** [F5Networks/f5-common-python#1463]
Those wanting to use odata with request parameters, which is valid via the REST interface, cannot do this in the sdk because we limit the delete method to a resource. Need to allow the delete method on collections as well.

**Comment by wojtek0806** [comment]
Some examples of this via POSTMAN would be useful to asses feasibility, as this would be a major change

**Comment by wojtek0806** [comment]
I would not enable this on all collections just yet but do this on those that we know this will be used imo, same as we do with Stats

**Comment by jasonrahm** [comment]
FYI you get an error if you just send a DELETE command on the collection without options request parameter, and the system will give an error for any pattern matching default resources.

**Comment by jasonrahm** [comment]
Merged to development, closing issue
