### ISSUE TITLE
Add license installation

### ISSUE THREAD

**Issue by drenout** [F5Networks/f5-common-python#1483]
Add license installation command similar to the revoking the license: 

Code snippet for the revoking the license:
```python
mgnt = ManagementRoot(bigip_mgnt, user, pass)
mgnt.tm.sys.license.exec_cmd('revoke')`
```
Code snippet for the license installation:
```python
mgnt = ManagementRoot(bigip_mgnt, user, pass)
mgnt.tm.sys.license.exec_cmd('install', registrationKey=regkey)
```

**Comment by jasonrahm** [comment]
we can merge yours. @drenout but can you first change the two append statements tp a single extend as in my PR submitted for the same.
