### ISSUE TITLE
How can I get the network map collection through f5 sdk for python

### ISSUE THREAD

**Issue by owainxd** [F5Networks/f5-common-python#1503]
I am working with F5 sdk for python,
On F5 UI: Local Traffic > Network Map,  I can set 'Type field' to 'Nodes', in search field I provide 'my_node_name'. By updating the map, I can have details about pools that use  'my_node_name'.

**Are there some ways to retrieve that details using  f5 api for python ?** 

**How can I load node collection belonging to a specfic partition ?** 
_I tried this : f5_connection.tm.ltm.nodes.get_collection(partition='my_partition')_
_but still having all partition_

**How can I get pools where a specific Node has child(chidrens) ?** 

Thanks advance for any answers

**Comment by jasonrahm** [comment]
Hi @knightRainbow, sorry I missed this inquiry. For your first question, this is done by passing request parameters and using the odata filter property:

`x = b.tm.ltm.nodes.get_collection(requests_params={'params': '$filter=partition eq bc'})`

Please clarify your second question.

**Comment by CyrilKuzmin** [comment]
Hi,
I have the same question "**How can I get pools where a specific Node has child(chidrens) ?**"
My aim is getting of "network map" for IP address. This IP can be VIP or its member (node). Search provided by UI (Local Traffic -> Network Map) works exactly like I want.
It's pretty easy to search by Virtual IP, but I cannot find an optimal way to search by Member IP. For example, I can check every VIP and their pools, but I will make a lot of pool.members_s.get_collection() requests to LB . In my case it will be ~500 requests... So, is it possible to get the pool by node IP where this node is used as member?

**Comment by owainxd** [comment]
@jasonrahm I have found  alternantives for my needs. 
Thanks for your answer anyway ;)
