### ISSUE TITLE
Unable access to ltm via http proxy

### ISSUE THREAD

**Issue by noby24** [F5Networks/f5-common-python#1508]
Can I use f5-sdk to access the management address of Big-ip LTM via HTTP proxy? 
I would like to use a proxy as follows.

from f5.bigip import ManagementRoot

proxies = {"http": "http://proxy_ip:port", "https": "https://proxy_ip:port"}
mgmt = ManagementRoot(big_ip, big_ip_user, big_ip_pass, proxies=proxies)

**Comment by renatocmaia** [comment]
I have the same problem.

**Comment by jasonrahm** [comment]
@noby24 and @renatocmaia, this feature is now merged to the development branch and will release on or before this Friday in version 3.0.21.
