### ISSUE TITLE
f5-sdk 3.0.20: add_to_trust() complains about LazyAttributesRequired in commandOutput

### ISSUE THREAD

**Issue by eest** [F5Networks/f5-common-python#1512]
Hello,

I am trying to setup a HA cluster, starting with adding a trusted member. It looks like this:
```
>>> from f5.bigip import ManagementRoot
>>> mgmt = ManagementRoot('lb1.example.com', 'admin', 'xxxxxxxxxx')
>>> trust = mgmt.tm.cm.add_to_trust.exec_cmd('run', name='Root', device='10.0.0.10', deviceName='lb2.example.com', username='admin', caDevice=True, password='xxxxxxxxxx')
>>>
```

As can be seen no exception is thrown, but inspecting trust.commandOutput shows a problem:
```
>>> trust.commandOutput
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/py3_virtualenv_f5/f5_virtualenv/lib/python3.5/site-packages/f5/bigip/mixins.py", line 95, in __getattr__
    raise LazyAttributesRequired(error_message)
f5.sdk_exception.LazyAttributesRequired: ('"allowed_lazy_attributes" not in', 'container._meta_data for class Add_To_Trust')
```

Is there something missing to make this work as expected? I ran into https://github.com/F5Networks/f5-common-python/issues/1301 and based this on the linked test code.

**Comment by vsnine** [comment]
We've been using this method which seems to work well. This particular snippet hasn't been tested, though i picked it out of some working code we're using to bootstrap new pairs of F5. Sorry its not a direct answer to your particular question.

```
from f5.bigip import ManagementRoot
from f5.multi_device.cluster import DeviceGroup, ClusterManager
mgmt1 = ManagementRoot(mgmtIp1, username, password, debug=True)
mgmt2 = ManagementRoot(mgmtIp2, username, password, debug=True)
bigip_list = [mgmt1, mgmt2]

cluster_mgr = ClusterManager()
cluster_mgr.create(
        devices=bigip_list,
        device_group_name = "MyDscName",
        device_group_type = 'sync-failover',
        device_group_partition = 'Common'
)
device_group = DeviceGroup( devices = bigip_list, device_group_name="MyDscName",
        device_group_type='sync-failover', device_group_partition='Common')
print(device_group.ensure_all_devices_in_sync())
```

**Comment by wojtek0806** [comment]
@eest The correct property name of the object you should be accessing is commandResult, which is what is the key under which REST sends command results. If ever in doubt, I suggest using 'raw' property of the objects to see what properties it carries, the example below is a different endpoint but the principle is the same:

```
>>> from f5.bigip import ManagementRoot
>>> mr = ManagementRoot('10.145.117.205', 'admin', 'admin')
>>> time = mr.tm.util.bash.exec_cmd('run', utilCmdArgs="-c time")
>>> time.commandResult
'\nreal\t0m0.000s\nuser\t0m0.000s\nsys\t0m0.000s\n'
>>> time.raw
{'kind': 'tm:util:bash:runstate', 'utilCmdArgs': '-c time', 'command': 'run', 'commandResult': '\nreal\t0m0.000s\nuser\t0m0.000s\nsys\t0m0.000s\n', '_meta_data': {'container': <f5.bigip.tm.util.Util object at 0x10d794320>, 'bigip': <f5.bigip.ManagementRoot object at 0x10c8b0da0>, 'icr_session': <icontrol.session.iControlRESTSession object at 0x10cd4d6d8>, 'icontrol_version': '', 'uri': 'https://10.145.117.205:443/mgmt/tm/util/bash/', 'minimum_version': '11.5.0', 'allowed_commands': ['run'], 'required_command_parameters': {'utilCmdArgs'}, 'exclusive_attributes': [], 'object_has_stats': True, 'minimum_additional_parameters': set(), 'required_json_kind': 'tm:util:bash:runstate'}}
```

**Comment by wojtek0806** [comment]
if there are any issues feel free to reopen

**Comment by eest** [comment]
@wojtek0806 To be clear the initial reason i opened this issue was that even after running the above mentioned trust establishment command there would not appear a node in the Device Trust ->  Peer List page in the GUI. Finding the error message in commandOutput was a side effect of me trying to debug that.

I have now tested this some more and the reason it didn't work was that the node being joined already had an entry for the first node from a previous setup. In this case nothing happened. It did however work if both Peer lists were empty, or if it existed only in the node being part of the mgmt connection.

The be specific, given:
```
>>> from f5.bigip import ManagementRoot
>>> mgmt = ManagementRoot('lb1.example.com', 'admin', 'xxxxxxxxxx')
>>> trust = mgmt.tm.cm.add_to_trust.exec_cmd('run', name='Root', device='10.0.0.10', deviceName='lb2.example.com', username='admin', caDevice=True, password='xxxxxxxxxx')
```
Setting up a trust works in some scenarios but no all:
- [x] Peer list is empty in both nodes
- [x] Peer list entry only exists in `lb1.example.com`
- [ ] Peer list entry only exists in `lb2.example.com`

I happened to be in the last situation, where a lingering trust from a previous example was still there.

From what I can tell, the content of `commandOutput` and `commandResult` is identical when it comes to my error:
```
>>> trust.commandOutput
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/f5_virtualenv/f5_virtualenv/lib/python3.7/site-packages/f5/bigip/mixins.py", line 95, in __getattr__
    raise LazyAttributesRequired(error_message)
f5.sdk_exception.LazyAttributesRequired: ('"allowed_lazy_attributes" not in', 'container._meta_data for class Add_To_Trust')
>>> trust.commandResult
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/f5_virtualenv/f5_virtualenv/lib/python3.7/site-packages/f5/bigip/mixins.py", line 95, in __getattr__
    raise LazyAttributesRequired(error_message)
f5.sdk_exception.LazyAttributesRequired: ('"allowed_lazy_attributes" not in', 'container._meta_data for class Add_To_Trust')
>>> 
```
... what is even more interesting is that even when the trust is missing in both devices and the command succeeds in adding it, the above error messages are still there. Not sure why that is.

Except for the unclear state of the error message I also notice the add_to_trust invocation does not appear to care about any of the SSL verification properties listed in the API documentation like `sha1Fingerprint`, (requires login, sorry): https://devcentral.f5.com/wiki/iControlREST.APIRef_tm_cm_add-to-trust.ashx maby this is an oversight?

@vsnine Thanks a lot for showing an example of how you are doing things, it is very helpful! Your example seems to reflect the documented approaches seen in the comments under f5/multi_device that I found just now when investigating your example code.

Maby this is the preferred approach over manually creating trusts like I have been trying to do. While that code does not seem to validate any SSL fingerprints either I guess it might no be as important given that you can create the two `ManagementRoot` instances with `verify=True` for overall certificate verification of the nodes.
