### ISSUE TITLE
Remove SIGALRM signal

### ISSUE THREAD

**Issue by jobec** [F5Networks/f5-common-python#1517]
Related to issue #1433 (closed)

The F5 module raises the SIGALRM signal which interferes with the rest of a python program. **Remove it and let the requests module do it's job.**

Using this module inside Gunicorn causes its worker to exit, instead of letting, for example, Django properly handle the timeout exception and display a proper message to the user. The below traceback should cause an internal server error, not a gunicorn worker restarting (which is a DoS attack surface).

```
[2019-02-07 16:45:32 +0100] [3295] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/vagrant/.venv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/vagrant/.venv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.run()
  File "/home/vagrant/.venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 124, in run
    self.run_for_one(timeout)
  File "/home/vagrant/.venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 83, in run_for_one
    self.wait(timeout)
  File "/home/vagrant/.venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 35, in wait
    ret = select.select(self.wait_fds, [], [], timeout)
  File "/vagrant/django/apps/test/views.py", line 86, in timeout_handler
    raise TimeoutError("Timed out waiting for response")
TimeoutError: Timed out waiting for response
[2019-02-07 16:45:32 +0100] [3295] [INFO] Worker exiting (pid: 3295)
```

This module makes the incorrect assumption it will always run in the main thread, which is far from true. IMHO, using things like signals is not the responsibility of a module and is instead the responsibility of the main program it is part of. It's like hijacking the entire python logging subsytem in the assumption that nothing else will need it.

From the [python docs](https://docs.python.org/3/library/signal.html#signals-and-threads):
> Python signal handlers are always executed in the main Python thread, even if the signal was received in another thread. This means that signals can’t be used as a means of inter-thread communication. You can use the synchronization primitives from the threading module instead.
> 
> Besides, only the main thread is allowed to set a new signal handler.

#1433 also makes the statement that the underlying requests library would block forever if a connection can be made but if there's never a response form the server. This is not true and is even documented in the requests library's docs: http://docs.python-requests.org/en/master/user/advanced/#timeouts

I tested this with a webserver blocking for 120 sec before it returns a response and requests library handles this just fine.

```python
>>> import requests
>>> r = requests.get("http://localhost:8080/tes", timeout=10)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=10)
```

**Comment by jasonrahm** [comment]
@jobec take a look at the PR I submitted and see if this works for you. I can merge next week after I fix a couple more bugs sitting out there.

**Comment by jobec** [comment]
Yes, that works and is about the same as how I monkey 🐒 patched it.

**Comment by jasonrahm** [comment]
closing issue, merged to development and will release in next version.
