### ISSUE TITLE
Complete Support for External Monitors

### ISSUE THREAD

**Issue by jesmith18** [F5Networks/f5-common-python#1521]
Currently, the implementation of tm/sys/file.py does not contain support for external monitors.

So while the external monitor LTM object can be created & managed via the SDK, the underlying file in the filestore cannot be.

This is as compared to external data-groups & iFiles where both the LTM object & the file in the filestore can be managed via the SDK.

**Comment by jasonrahm** [comment]
on vacation currently, but will take a look at this next week

**Comment by jasonrahm** [comment]
Hi @jesmith18, got sidetracked on another underlying issue. I'll dig into this on Monday. Sorry for the delay.

**Comment by jesmith18** [comment]
No problem

**Comment by jasonrahm** [comment]
This has been merged to development and will release on or before Friday in 3.0.21.

**Comment by jesmith18** [comment]
Thanks!!

If you have not, you may want to reach out to Wojciech Wypior. He maintains the F5 ansible tasks.

There currently is an ansible task for external monitors (bigip_monitor_external) that could be made simpler now that the SDK directly supports external monitors.

**Comment by wojtek0806** [comment]
SDK has been removed and no longer a part of Ansible

**Comment by jesmith18** [comment]
Do you know as of which version? The current version (2.7.6) does.

**Comment by jesmith18** [comment]
This release has been labeled "3.0.21". Shouldn't that be "v3.0.21"?

**Comment by jasonrahm** [comment]
yep, that's my bad. Updated
