### ISSUE TITLE
further reading links 404 api docs

### ISSUE THREAD

**Issue by jlosito** [F5Networks/f5-common-python#1527]
There's a couple of links on the docs which get a 404. For instance, [F5 iControl REST API Reference (PDF)](https://devcentral.f5.com/s/d/icontrol-rest-api-reference-version-120).

**Comment by jasonrahm** [comment]
I'll get these cleaned up.

**Comment by jlosito** [comment]
I'm closing it due to inactivity. I'm getting 404s from that page anyway. Things have probably changes within the last couple of years.
