### ISSUE TITLE
Missing six.py ???

### ISSUE THREAD

**Issue by pmkerin** [F5Networks/f5-common-python#1529]
Was trying to use the Bash.py functionality and ran into problems within f5-common-python/f5/bigip/mixins.py.

within mixins.py -> from six import iteritems

I need access to "six" as the function iteritems is needed.

Cheers for your help.

**Comment by vsnine** [comment]
You should just be able to install six using either your package manager or pip. More info about it is available here: https://pypi.org/project/six/

**Comment by pmkerin** [comment]
Cheers !
