### ISSUE TITLE
icontrol.exceptions.InvalidInstanceNameOrFolder: instance names and partitions cannot contain '/'

### ISSUE THREAD

**Issue by kc8iqw** [F5Networks/f5-common-python#1530]
This may not be a bug, but perhaps a lack of documentation.  When trying to access Pool information when the pool is within an iApp, I get the above error.  When using a direct REST call, it parses as `~Common~SOMEAPP.app~SOMEPOOL?ver=12.1.3.3`

Given the `/Common/SOME.app/SOMEPOOL `is what is being returned by mgmt.tm.ltm.virtuals.pool I would expect to be able to use the / in the path for iApp pools, stats, etc.

**Comment by jasonrahm** [comment]
Try adding the kwarg `transform_name: True`

You might need `transform_subpath: True` in addition to or in place of, I'm a little sketchy with how iApps present.

**Comment by kc8iqw** [comment]
WONDERFUL.  after some trial and error (I'm new to python), I was able to do the call like such:  `pool = mgmt.tm.ltm.pools.pool.load(transform_name=True, partition=lpool[1], name=lpool[2]+'/'+lpool[3])`

I theorize I could change that to `.load({transform_name: True, partition=lpool[1], name=lpool[2]+'/'+lpool[3]})` just as well.

**Comment by jasonrahm** [comment]
the former will work, the latter will likely fail. The load method is looking for arguments, not a dictionary of arguments. Welcome to python, it's by far my favorite language to work in.
