### ISSUE TITLE
Remove the SOAP api code from the repo (pycontrol)

### ISSUE THREAD

**Issue by swormke** [F5Networks/f5-common-python#154]
The current library has a pycontrol module in it that manages a connection to the SOAP interface of the BigIP.  After talking with @jgruber he sees no reason for us to keep it given the new object/manager direction for the library.  We should be able to accomplish everything we need to with the REST API.

We should remove this code and if we need a SOAP session manager we should create an f5-icontrol-soap library like the [f5-icontrol-rest](https://github.com/F5Networks/f5-icontrol-rest-python) library.

I did some looking around at the library and it doesn't appear that anything really uses this except for SSL certificates, but after discussion we can do this with the REST API and a `SSLManager` to be written in the future.

**Comment by zancas** [comment]
@swormke I think I can wrap this up too.

**Comment by zancas** [comment]
Unless sys/system.py and/or cm/cluster.py are tricky.
