### ISSUE TITLE
How can I get CPU usage via sdk

### ISSUE THREAD

**Issue by q2807c** [F5Networks/f5-common-python#1552]
When I am using curl command to fetch CPU info from /mgmt/tm/sys/CPU, I can get the CPU related info.

curl -sku admin:admin https://10.1.1.133//mgmt/tm/sys/cpu | more
{"kind":"tm:sys:cpu:cpustats","selfLink":"https://localhost/mgmt/tm/sys/cpu?ver=11.5.9","entries":{"https://localhost/mgmt/tm/sys/cpu/0":{"nestedStats":{"entries":{"https://localhost/mgmt/tm/sys/cpu/0/cpuInfo":{"nestedStats":{"entries":{"https://localhost/mgmt/tm/sys/cpu/0/cpuInfo/0":{"nestedStats":{"entries":{"cpuId":{"value":0},"fiveMinAvgIdle":{"value":97},

But the f5-sdk reports no such class. The simple script is like below:

from f5.bigip import ManagementRoot

# Connect to the BigIP
mgmt = ManagementRoot("10.1.1.133", "admin", "admin")
cpus = mgmt.tm.sys.cpu.get_collection()

The link never includes python file for cpu. https://github.com/F5Networks/f5-common-python/tree/development/f5/bigip/tm/sys

**Comment by harrywangaa** [comment]
tmplist = []
                host_info = self.mgmt.tm.sys.host_info.load()
                cpu_info = host_info.raw.get('entries').get("https://localhost/mgmt/tm/sys/host-info/0").get(
                    "nestedStats").get(
                    "entries").get("https://localhost/mgmt/tm/sys/hostInfo/0/cpuInfo") \
                    .get("nestedStats").get("entries")
                for key, value in cpu_info.items():
                    tmplist.append(value.get("nestedStats").get("entries").get("oneMinAvgIdle").get("value"))
                value = 100 - min(tmplist)
