### ISSUE TITLE
how to replace vserver's profiles?

### ISSUE THREAD

**Issue by yangmingbai** [F5Networks/f5-common-python#1573]
hello : 
 i want to replace a server's profile, 
example:
the vserver has profile named "/Common/security-fastL4"; but now i want to replace it's profiles use this ['/Common/fastL4', "/Common/http"]
but I don't know how to use this API  "vc1.update()" to replace it 
thanks!

**Comment by f5-rahm** [comment]
HI @yangmingbai, you should use modify for this:

```
vip = b.tm.ltm.virtuals.virtual.load(name='viptest1')
vip_profiles = vip.profiles_s.get_collection()
for profile in vip_profiles:
    print(profile.name)
    
security-fastL4
vip.modify(profiles=['fastL4', 'http'])
vip_profiles = vip.profiles_s.get_collection()
for profile in vip_profiles:
    print(profile.name)
    
fastL4
http

```

**Comment by yangmingbai** [comment]
thanks!
