### ISSUE TITLE
Call Application under partition

### ISSUE THREAD

**Issue by tifa2100** [F5Networks/f5-common-python#1574]
I am trying to load virtual server as below
`vip = ltm.virtuals.virtual.load(name="vs_name", partition="Common/partition.one")`
it give me this error
`instance names and partitions cannot contain '/', but it's: Common/partition.one`

my virtual server output like below:
`# tmsh list /ltm virtual /Common/partition.one/vs_name`
it gives me below output
`ltm virtual partition.one/vs_name { ......`

how to load the virtual server in this case?

**Comment by f5-rahm** [comment]
you will need to add the transform_name as a kwarg and set it to True and that should help. [example](https://github.com/F5Networks/f5-common-python/issues/1530#issuecomment-500600245)

**Comment by tifa2100** [comment]
@f5-rahm  Thanks for your prompt support
