### ISSUE TITLE
We need a utility to traverse the server published URIs

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-common-python#158]
This issue is complete when we have a REST walker.

**Comment by wojtek0806** [comment]
Issue Review: I believe we have beginnings of it in our Code generator tool.

**Comment by wojtek0806** [comment]
Are we dropping this tool? Or whats the deal?

**Comment by wojtek0806** [comment]
what is the status ? @caphrim007 @zancas

**Comment by caphrim007** [comment]
i havent done any work on this yet

**Comment by caphrim007** [comment]
i'm closing because imho this is not necessary
