### ISSUE TITLE
Verify subset of f5-common modules needed by LBaaSv2 and Heat projects

### ISSUE THREAD

**Issue by jlongstaf** [F5Networks/f5-common-python#197]
Verify that f5-common-python modules can be used by other projects:

The following modules are needed by LBaaSv2 (f5-openstack-agent):

cm:
  cluster.py
  device.py

ltm:
  ~~monitor.py~~
  ~~pool.py~~
  ~~rule.py~~
  ~~snat.py~~
  ssl.py
  ~~virtual.py~~

net:
  arp.py
  interface.py
  l2gre.py
  route.py
  ~~selfip.py~~
  ~~vlan.py~~
  vxlan.py

sys:
  stat.py
  system.py

**Comment by swormke** [comment]
The `l2gre.py` and `vxlan.py` are actually Sub-collections under `net/tunnel/`

**Comment by swormke** [comment]
It looks like in older versions the tunnels are part of `net/fdb/tunnel` and changed 11.6+.  Need to verify with @jgruber and we may need to add this in after the fact.

**Comment by swormke** [comment]
Inside of `system.py` there are many different kinds of things going on.  We need to implement the following things to support it.  Some of which are done via icontrol SOAP and we may need to figure out the right way to do it via REST.

```python
        self.mgmt_folder = self.bigip.icontrol.Management.Folder
        self.sys_session = self.bigip.icontrol.System.Session
        self.sys_info = self.bigip.icontrol.System.SystemInfo
        self.sys_swmgmt = self.bigip.icontrol.System.SoftwareManagement
        self.sys_config_sync = self.bigip.icontrol.System.ConfigSync
        self.sys_vcmp = self.bigip.icontrol.System.VCMP
```
* `sys/global-settings`
* `sys/ntp`
* `cm/device` (this is probably the same code as the device.py in the description)
* `sys/db`  (@szakeri is working on this I think)
* `sys/failover`

**Comment by swormke** [comment]
I found the following references in the LBaaSv1 implementation for the SOAP helpers.  Maybe the others are used by the ODK or Onboard that are now going to be part of the heat library when we have clustering complete?

```
agent/f5/oslbaasv1agent/drivers/bigip/vcmp.py:            system_info = bigip.system.sys_info.get_system_information()
agent/f5/oslbaasv1agent/drivers/bigip/l2.py:            vlan_list = vcmp_host['bigip'].system.sys_vcmp.get_vlan(
agent/f5/oslbaasv1agent/drivers/bigip/l2.py:            vlan_seq = vcmp_host['bigip'].system.sys_vcmp.typefactory.\
agent/f5/oslbaasv1agent/drivers/bigip/l2.py:            vlan_seq_seq = vcmp_host['bigip'].system.sys_vcmp.typefactory.\
agent/f5/oslbaasv1agent/drivers/bigip/l2.py:            vcmp_host['bigip'].system.sys_vcmp.add_vlan([vcmp_guest['name']],
agent/f5/oslbaasv1agent/drivers/bigip/l2.py:            vlan_seq = vcmp_host['bigip'].system.sys_vcmp.typefactory.\
agent/f5/oslbaasv1agent/drivers/bigip/l2.py:            vlan_seq_seq = vcmp_host['bigip'].system.sys_vcmp.typefactory.\
agent/f5/oslbaasv1agent/drivers/bigip/l2.py:            vcmp_host['bigip'].system.sys_vcmp.remove_vlan(
agent/f5/oslbaasv1agent/drivers/bigip/vcmp.py:            guest_names = vcmp_host['bigip'].system.sys_vcmp.get_list()
agent/f5/oslbaasv1agent/drivers/bigip/vcmp.py:                system.sys_vcmp.get_management_address(guest_names)
agent/f5/oslbaasv1agent/drivers/bigip/vcmp.py:            vlan_list = vcmp_host['bigip'].system.sys_vcmp.get_vlan(
```

**Comment by swormke** [comment]
The same is going on in cluster.py.  There are multiple objects in there we need to create.

* `cm/` - Which looks like it has a new method called `sync()` that we will need to support in addition to `CURDL` methods.
* `cm/device`
* `cm/device-group`
* `cm/traffic-group`

There is also this SOAP helper, that we need to figure out if we can have equivalent functionality in REST.
```python
self.mgmt_trust = self.bigip.icontrol.Management.Trust
```
