### ISSUE TITLE
Refactor cluster.py

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-common-python#208]
The cluster.py module in interfaces/ in the master branch needs refactoring to work with refactored f5-common-python code. It should be ported over wherever makes sense in the new common python structure.

**Comment by pjbreaux** [comment]
Below are notes from @swormke relating to this module:

```
There are multiple objects in there we need to create.

  • `cm/` - Which looks like it has a new method called `sync()` that we will need to support in addition to `CURDL` methods.
  • `cm/device`
  • `cm/device-group`
  • `cm/traffic-group`

There is also this SOAP helper, that we need to figure out if we can have equivalent functionality in REST.
self.mgmt_trust = self.bigip.icontrol.Management.Trust
```

**Comment by wojtek0806** [comment]
In v12 we now have the ability to set and reset device trusts. Requests would be sent to the following 2 URIs:

/mgmt/tm/cm/addToTrust
/mgmt/tm/cm/removeFromTrust

Resource links only support POST,OPTIONS.

I have attached some examples of the REST calls in python to this comment (it will contain my additional observations that may/may not be helpful)
[example.py.txt](https://github.com/F5Networks/f5-common-python/files/193304/example.py.txt)

Additionally  the v12 REST API reference indicates that we should also support configuring of custom cert/key pairs to be used with trust setup, as well as whole trust domains. The certificate files need obviously need to be present in file store first. Rest endpoints for this are as follows:

/mgmt/tm/cm/cert
/mgmt/tm/cm/key
/mgmt/tm/cm/trustDomain

**Comment by wojtek0806** [comment]
One other thing of note, in regards to the closed Issue #302. It seems the following REST endpoint provides much more information regarding failover status,  it actually shows the unit's fail-over state per traffic-group, which could be useful with N+1 cluster deployments. Might be worthwhile looking at implementing this, while reworking CM module:

/mgmt/tm/cm/failoverStatus

**Comment by zancas** [comment]
I think this is in the scope of @pjbreaux 's current effort.

**Comment by wojtek0806** [comment]
Issue Review: I believe this can be closed as most of the above has been addressed and rest is worked via #400

**Comment by pjbreaux** [comment]
Another duplicate of #400.

**Comment by zancas** [comment]
Agreed commenting in #400, and closing.
