### ISSUE TITLE
class StatsMixin(UnnamedResourceMixin):

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-common-python#214]
If tm:FOO:SPAM:SPAMstats are just like UnnameResources but they ALSO don't support 'update' then this is probably the right thing to do.    We should be careful to think about whether the class should be "StatsMixin" or something more generic if the 'updateless-and-nameless-resource' pattern is wider than just stats.

I think the right answer is to start with them name "StatsMixin" and then rename later if we see that there's a more general pattern.

**Comment by swormke** [comment]
For example the kind `tm:sys:failover:failoverstats` allows a post to force the system to standby.

Take a look at this:
https://github.com/F5Networks/f5-common-python/blob/master/f5/bigip/interfaces/system.py#L519

**Comment by swormke** [comment]
Maybe a new resource type of `Stat` or something here is appropriate, with special methods for things like failover that do the `POST` thing.

**Comment by zancas** [comment]
Whether or not to implement this is something we need more data one.  I'm closing this to be possibly replaced by some other future issue.

**Comment by zancas** [comment]
That is, until we have more experience we won't know if there's a general pattern that uses POSTs to implement functions like failover.  (That specific case is now our for review.)
