### ISSUE TITLE
Add "load" as an Unsupported operation to UnnamedResourceMixin

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-common-python#215]
I think "`load`" like "`create`" and "`delete`" should only be invocable on classes that expect unique components to their "`self._meta_data['uri']`".

**Comment by swormke** [comment]
I am fine either way, but it seems more intuitive to me to `load()` a resource the first time.

**Comment by zancas** [comment]
Load is already implemented for this, it's fine for it to stay implemented.
