### ISSUE TITLE
docstring for inherited methods are incorrect

### ISSUE THREAD

**Issue by b225ccc** [F5Networks/f5-common-python#227]
@pjbreaux 

http://f5-sdk.readthedocs.org/en/latest/apidoc/f5.bigip.sys.html#f5.bigip.sys.folder.Folder

Appears that method documentation are just inheriting from Resource

**Comment by b225ccc** [comment]
Actually it looks like documentation exists n __init__(), but this string doesn't appear in read the docs.

**Comment by pjbreaux** [comment]
I think @zancas is sorely, sorely mistaken. This was not done by me, but by @swormke. Reassigning to the guilty party.

**Comment by swormke** [comment]
Actually it was @zancas in commit 68d677724fd96c7cecdf7608cafb2b1333bfe50a that caused this by adding the `inherited-members` option to the `docs/conf.py` file.  I will take this bug though and we need to fix the documentation of the Resource and other Base classes to reflect proper documentation for the classes.
