### ISSUE TITLE
Use refresh() in application.services.service _create() instead of load()

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-common-python#233]
The load operation can fail after a create is done, because load uses kwargs and those kwargs may cause the BigIP get request to fail. We can populate the object with refresh instead.

**Comment by zancas** [comment]
I don't understand the failure mode here.   Do we have a test demonstrating that load fails?   How can "loads" kwargs cause the bigip's get request to fail?

**Comment by pjbreaux** [comment]
The sys.application.services.service overrides _create and _load. If kwargs are passed to _create, those are also given to _load (https://github.com/F5Networks/f5-common-python/blob/0.1/f5/bigip/sys/application.py#L128), and in the case of kwargs['trafficGroup'] being given to _load, it causes the get request there to fail. But instead of doing a _load in the _create of that resource, @swormke suggested doing a refresh().

**Comment by zancas** [comment]
See PR #248
