### ISSUE TITLE
iApp create_template and template_exists function arguments inconsistent

### ISSUE THREAD

**Issue by cmutzel** [F5Networks/f5-common-python#245]
The following behavior is confusing:
1) User deploys an iApp template onto BIG-IP using the create_template() method in f5.bigip.interfaces.iapp using parameter name='foo_name', with name='foo_name' in the JSON body
2) User checks to see whether the template exists using method template_exists from same interface (i.e. they check for existence of using parameter name='foo_name')

Above fails unless they have set the name of the template in JSON payload to 'uuid_foo_name'.

**Example below....**

```
import logging
logging.basicConfig(level=logging.DEBUG)

import json, requests
iapp_template = json.loads(requests.get("https://s3.amazonaws.com/custom-cfn-ex-bigip-cluster/http_backport_template.json").text)

from f5.bigip.bigip import BigIP
bigip = BigIP("52.3.11.221", "admin", "GoF5!")

# attempt 1 - name argument is not consistent between create_template and template_exists APIs, due to appending of 'uuid' string in front
name = iapp_template["name"]
print "Template has name: %s " % name
print "iApp template '%s' exists : %s " % (name, bigip.iapp.template_exists(name=name))

# try creating the template
print "Creating template '%s': %s" % (name, bigip.iapp.create_template(name=name, template=iapp_template))
print "iApp template '%s' exists : %s " % (name, bigip.iapp.template_exists(name=name))

## attempt 2 - getting it to work....append uuid to the value for key 'name' in the template JSON payload
name = iapp_template["name"] = 'uuid_%s' % iapp_template["name"]

print "Template has name: %s " % name
print "iApp template '%s' exists : %s " % (name, bigip.iapp.template_exists(name=name))

# try creating the template
print "Creating template '%s': %s" % (name, bigip.iapp.create_template(name=name, template=iapp_template))
print "iApp template '%s' exists : %s " % (name, bigip.iapp.template_exists(name=name))
```

**Relevant logs** (large JSON http responses ...._truncated_....):
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /custom-cfn-ex-bigip-cluster/http_backport_template.json HTTP/1.1" 200 167969
Template has name: f5.http.backport.1.1.2 
DEBUG:f5.bigip.interfaces:IApp::template_exists called with args: () kwargs: {'name': u'uuid_f5.http.backport.1.1.2'}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): 52.3.11.221
iApp template 'f5.http.backport.1.1.2' exists : False 
DEBUG:requests.packages.urllib3.connectionpool:"GET /mgmt/tm/sys/application/template/~Common~uuid_f5.http.backport.1.1.2?$select=name HTTP/1.1" 404 140
DEBUG:f5.bigip.interfaces:IApp::create_template called with args: () kwargs: {'name': u'uuid_f5.http.backport.1.1.2', 'template': ...._truncated_....
DEBUG:f5.bigip.interfaces:IApp::template_exists called with args: () kwargs: {'folder': 'Common', 'name': u'uuid_f5.http.backport.1.1.2'}
DEBUG:requests.packages.urllib3.connectionpool:"GET /mgmt/tm/sys/application/template/~Common~uuid_f5.http.backport.1.1.2?$select=name HTTP/1.1" 404 140
Creating template 'f5.http.backport.1.1.2': True
DEBUG:requests.packages.urllib3.connectionpool:"POST /mgmt/tm/sys/application/template/ HTTP/1.1" 409 156
DEBUG:f5.bigip.interfaces:IApp::template_exists called with args: () kwargs: {'name': u'uuid_f5.http.backport.1.1.2'}
DEBUG:requests.packages.urllib3.connectionpool:"GET /mgmt/tm/sys/application/template/~Common~uuid_f5.http.backport.1.1.2?$select=name HTTP/1.1" 404 140
iApp template 'f5.http.backport.1.1.2' exists : False 
DEBUG:f5.bigip.interfaces:IApp::template_exists called with args: () kwargs: {'name': u'uuid_f5.http.backport.1.1.2'}
Template has name: uuid_f5.http.backport.1.1.2 
iApp template 'uuid_f5.http.backport.1.1.2' exists : False 
DEBUG:requests.packages.urllib3.connectionpool:"GET /mgmt/tm/sys/application/template/~Common~uuid_f5.http.backport.1.1.2?$select=name HTTP/1.1" 404 140
DEBUG:f5.bigip.interfaces:IApp::create_template called with args: () kwargs: {'name': u'uuid_f5.http.backport.1.1.2', 'template': ...._truncated_....
DEBUG:f5.bigip.interfaces:IApp::template_exists called with args: () kwargs: {'folder': 'Common', 'name': u'uuid_f5.http.backport.1.1.2'}
DEBUG:requests.packages.urllib3.connectionpool:"GET /mgmt/tm/sys/application/template/~Common~uuid_f5.http.backport.1.1.2?$select=name HTTP/1.1" 404 140
DEBUG:requests.packages.urllib3.connectionpool:"POST /mgmt/tm/sys/application/template/ HTTP/1.1" 200 578
DEBUG:f5.bigip.interfaces:IApp::template_exists called with args: () kwargs: {'name': u'uuid_f5.http.backport.1.1.2'}
Creating template 'uuid_f5.http.backport.1.1.2': True
DEBUG:requests.packages.urllib3.connectionpool:"GET /mgmt/tm/sys/application/template/~Common~uuid_f5.http.backport.1.1.2?$select=name HTTP/1.1" 200 38
iApp template 'uuid_f5.http.backport.1.1.2' exists : True

**Comment by zancas** [comment]
Hmmm...    this appears to be using the old version of the library.   @cmutzel what version are you using?

**Comment by pjbreaux** [comment]
@cmutzel:

You can now use the refactored version of this repo. You can install it by doing ```pip install git+https://github.com/F5Networks/f5-common-python.git``` or you could clone the repo and checkout the *0.1* branch. Refer to the main readme for examples on how to use it and the api docs.

I'm assigning this ticket back to you. Please close if you the refactored code works for you. Thanks.

**Comment by cmutzel** [comment]
Perfect, I will try the new stuff and check it out.  Since I won't get to that for a little while, I'll close for now and reopen later if necessary.
