### ISSUE TITLE
Code generation utilities need more docstrings and better (smaller) functionalization

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-common-python#247]
The functions/methods in the template_engine need docstrings and some of them are growing large. It might be better to functionalize the elements that are reusable in methods such as def _format_org_collection and def _format_resource_collection.

**Comment by pjbreaux** [comment]
OCCrawler should be renamed to ItemsCrawler

**Comment by pjbreaux** [comment]
Remove hard-coded IP, username, and password from crawler.py

**Comment by wojtek0806** [comment]
Issue Review: Requires change to source_engine.py as well as crawler.py

**Comment by caphrim007** [comment]
we do not auto generate classes. that's dangerous is most cases and there is plenty of existing work that can be copied and pasted around as necessary without needing to struggle with a custom code generator for an API that has no standards. closing
