### ISSUE TITLE
Net route functional tests remove routes/vlans/selfIPs on VE

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-common-python#254]
While running the functional tests against a VE in openstack, I had the test run stop at `net/test_route.py::TestRoute::test_CURDL PASSED` and then hang for a while. After which, I Ctrl+C the process and realized my connection the VE via the floating IP had died. After investigating the VE through the openstack remote terminal, I discovered no routes, vlans, or self IPs on the device, which were on there before the test ran.

**Comment by zancas** [comment]
I believe @swormke implemented this class.   I'm removing the "critical" label as I believe this is a test issue, not a f5-sdk functionality issue.

**Comment by zancas** [comment]
@pjbreaux   what's the status of this?

**Comment by wojtek0806** [comment]
Issue Review: This could be addressed by #427 when we are looking through syntax anyway. I will mark it as duplicate for now. Feel free to remove if you feel otherwise

**Comment by zancas** [comment]
Let's leave open-as-sufficiently-distinct.

**Comment by wojtek0806** [comment]
@pjbreaux @zancas what is the status of this?

**Comment by wojtek0806** [comment]
this issue will exist due to this:

````
def delete_resource(resources):
    for resource in resources.get_collection():
        resource.delete()

````
