### ISSUE TITLE
Fix error(s) in documentation

### ISSUE THREAD

**Issue by jputrino** [F5Networks/f5-common-python#261]
In the warning on http://f5-sdk.readthedocs.org/en/latest/userguide/endpoints/collection.html:
"When the Resource object’s type is plural (ends in an s), you need to add _s to the name when referring to the object." should be "When the Resource object’s type is plural (ends in an s), you need to add _s to the name when referring to the **collection**."

In the first paragraph on http://f5-sdk.readthedocs.org/en/latest/userguide/endpoints/subcollection.html:
fix the `:meth:~f5.bigip.resource.Collection.get_collection()` reference (it's broken across 2 lines).

In the python code example on http://f5-sdk.readthedocs.org/en/latest/userguide/endpoints/subcollection_resource.html:
`>>> member = pool.members_s.member.load(partition='Common', name='n1:80')` should be `>>> member = pool.members_s.members.load(partition='Common', name='n1:80')` 

In http://f5-sdk.readthedocs.org/en/latest/userguide/object_path.html#collection-section: 
"(in other words, we’re signed in to the BIG-IP and accessed the LTM module)" should be "(in other words, **we** signed in to the BIG-IP and accessed the LTM module)".

On http://f5-sdk.readthedocs.org/en/latest/userguide/object_path.html#resource-section:
Change **Example: Load a pools collection** to **Example: Load a pool resource**

in http://f5-sdk.readthedocs.org/en/latest/userguide/object_path.html#subcollection-resource-section:
In the example, change `member = members_s.members.load(partition='Common', name='m1')` to `member = members_s.members.load(partition='Common', name='m1:80')`

In the [coding example](http://f5-sdk.readthedocs.org/en/latest/userguide/ltm_pools_members_code_example.html#pools-and-members-code-example):
- "# We can also create the object and load the pool at the same time" should be "We can also skip creating the object and load the pool directly".
- `raise Exception("Object should have been deleted")` needs to be indented

Small nitpicky stuff:
- add (PDF) after each of the links on [Further Reading](http://f5-sdk.readthedocs.org/en/latest/userguide/further_reading.html) that triggers a download.

**Comment by zancas** [comment]
I'm getting flake8 warnings about the contents of 'f5-common-python/docs/conf.py'.   I talked to @swormke about it, and I think we're in agreement that the proper solution is to exclude the docs directory from flake8 checking in .travis.yml.   If necessary I can handle this, just assign a relevant issue to me.

**Comment by zancas** [comment]
OK, after chatting with @jputrino I've discovered that the docs directory is already excluded from the CI PEP8 checker targets.
