### ISSUE TITLE
Need support for  bigip.cm.sync-status

### ISSUE THREAD

**Issue by jlongstaf** [F5Networks/f5-common-python#271]
I'm attempting to use the F5 SDK to get the sync-status for a BIG-IP system. This is defined by the sync-status resource of the CM module. Here's the complete code from LBaaS v1 that I'm attempting to re-write using the SDK:

    def get_sync_status(self):
        """ Get the sync status description for the bigip """
        request_url = self.bigip.icr_url + '/cm/sync-status?$select=status'
        response = self.bigip.icr_session.get(request_url,
                                              timeout=const.CONNECTION_TIMEOUT)
        if response.status_code < 400:
            response_obj = json.loads(response.text)
            entries = response_obj['entries']
            status = entries['https://localhost/mgmt/tm/cm/sync-status/0']
            desc = status['nestedStats']['entries']['status']['description']
            return desc
        else:
            Log.error('sync-status', response.text)
            raise exceptions.ClusterQueryException(response.text)
        return None

**Comment by zancas** [comment]
I've implemented a cm/sync_status object.

I recommend we use its attributes to determine which state "sync-status" is in.   Please look in:

'test/functional/cm/test_sync_status.py'

for an example of querying the Python object to learn about the server configuration state.
