### ISSUE TITLE
Need support for POSTing command to bigip.cm

### ISSUE THREAD

**Issue by jlongstaf** [F5Networks/f5-common-python#272]
I need to implement sync methods for BIG-IPs using the SDK. Some of the methods require sending a POST to the cm resource. Here's an example from the LBaaS v1 code:

    def sync_local_device_to_group(self, device_group_name):
        """ Sync local device to group """
        request_url = self.bigip.icr_url + '/cm'
        payload = dict()
        payload['command'] = 'run'
        payload['options'] = [{'config-sync': 'to-group ' + device_group_name}]
        response = self.bigip.icr_session.post(
            request_url, data=json.dumps(payload),
            timeout=const.CONNECTION_TIMEOUT)
        if response.status_code < 400:
            return True
        else:
            Log.error('sync', response.text)
            raise exceptions.BigIPClusterSyncFailure(response.text)
        return False

**Comment by swormke** [comment]
@jlongstaf how long until this is a blocker for your work in F5Networks/f5-openstack-agent ?

**Comment by jlongstaf** [comment]
It's technically a blocker now, as this (sync_local_device_to_group) is the remaining piece for completing cluster management.

**Comment by swormke** [comment]
I am going to take this one and add a `sync()` method to CM, that does what @jlongstaf needs

**Comment by swormke** [comment]
@jlongstaf based on the way you would use this or others would use it do you think it makes sense to call it in which of the following two ways:

As a method on cm in which you pass in the device-group name

```
bigip.cm.sync('my_device_group')
```

As part of the device group itself:

```
device_group = bigip.cm.device_groups.device_group.load(partition='Common', name='my-group')
device_group.sync()
```

I implemented the first way, but as soon as I did that I wondered if it would be more useful as the latter.

**Comment by swormke** [comment]
maybe even both?

**Comment by jlongstaf** [comment]
Shawn,

The first way makes the most sense to me.

Jeff
