### ISSUE TITLE
pip install fails in python35

### ISSUE THREAD

**Issue by harishpokharel** [F5Networks/f5-common-python#273]
PS C:\Users\hpokhare\AppData\Local\Programs\Python\Python35-32\Scripts> .\pip.exe install f5-sdk
Collecting f5-sdk
  Using cached f5-sdk-0.1.1.tar.gz
Collecting eventlet (from f5-sdk)
  Using cached eventlet-0.18.4-py2.py3-none-any.whl
Collecting f5-icontrol-rest>=1.0.2 (from f5-sdk)
  Using cached f5-icontrol-rest-1.0.2.tar.gz
Collecting netaddr (from f5-sdk)
  Using cached netaddr-0.7.18-py2.py3-none-any.whl
Collecting pyopenssl (from f5-sdk)
  Using cached pyOpenSSL-0.15.1-py2.py3-none-any.whl
Collecting requests (from f5-sdk)
  Using cached requests-2.9.1-py2.py3-none-any.whl
Collecting suds>0.3 (from f5-sdk)
  Using cached suds-0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\hpokhare\AppData\Local\Temp\pip-build-2_n4t1pc\suds\setup.py", line 20, in <module>
        import suds
      File "C:\Users\hpokhare\AppData\Local\Temp\pip-build-2_n4t1pc\suds\suds\__init__.py", line 154, in <module>
        import client
    ImportError: No module named 'client'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\hpokhare\AppData\Local\Temp\pip-build-2_n4t1pc\s

**Comment by swormke** [comment]
Hi @harishpokharel is this Python 3 or 2?

**Comment by swormke** [comment]
@zancas now that we have removed the `pycontrol` module, I believe we can also remove the suds package from the `setup.py` and the `requirements*.txt` files

**Comment by harishpokharel** [comment]
@swormke - Python 3
PS C:\Users\hpokhare\AppData\Local\Programs\Python\Python35-32\Scripts> python
Python 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:16:59) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by zancas** [comment]
@harishpokharel this library is not Python3 compliant.   It's Python 2.6 and 2.7 compliant.
