### ISSUE TITLE
IOError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by harishpokharel** [F5Networks/f5-common-python#278]
Always getting the following error while printing the pool members using the example code in readme .
(BIG-IP 11.5.3 HF2)

Traceback (most recent call last):
  File ".\f5_sdk_pool.py", line 11, in <module>
  File "C:\Python27\lib\site-packages\f5\bigip\resource.py", line 403, in get_collection
  File "C:\Python27\lib\site-packages\f5\bigip\resource.py", line 281, in refresh
  File "C:\Python27\lib\site-packages\f5\bigip\resource.py", line 264, in _refresh
  File "C:\Python27\lib\site-packages\icontrol\session.py", line 271, in wrapper
  File "C:\Python27\lib\site-packages\icontrol\session.py", line 214, in _config_logging
  File "C:\Python27\lib\logging\__init__.py", line 905, in __init__
  File "C:\Python27\lib\logging\__init__.py", line 935, in _open
IOError: [Errno 24] Too many open files: 'C:\\Users\\hpokhare\\Desktop\\python27_Scripts\\logs\\iControlRESTSession\\145
8154715\\get'

**Comment by swormke** [comment]
This may actually be an issue in the underlying icontrol rest library, but lets take a look and figure out what is going on.

**Comment by swormke** [comment]
Hi @harishpokharel this is issue F5Networks/f5-icontrol-rest-python#59.  It has been resolved and we are going to spin a release for that project today with it in there.

**Comment by zancas** [comment]
Hi @harishpokharel this is a fixed issue in https://github.com/F5Networks/f5-icontrol-rest-python, however we have not yet updated the release with the fix.

We are in the process of updating the release now.   After we've updated the release you'll need to pip install the new version.

**Comment by swormke** [comment]
Hi @harishpokharel the updated release for the icontrol library that the f5-sdk uses has been updated and is posted to pypi.  Please update your install with the following:

```
pip install --upgrade f5-icontrol-rest
```

You should then have version 1.0.3 installed.

**Comment by swormke** [comment]
We are also updating the requirements for this package to ensure that it has the fix installed as part of it.

See issue #280

**Comment by swormke** [comment]
@harishpokharel 

@zancas is looking at this again after your update.  We have identified the area and are going to put in a fix and then rework the logging in F5Networks/f5-icontrol-rest-python which is where the problem is.  We will issue a new maintenance release with the interim fix and then create a new feature release with the rework for logging in it.

**Comment by swormke** [comment]
@harishpokharel we released the fix for the underlying library today.  To make sure you have the newest stuff can you please do the following

```
pip install --upgrade f5-icontrol-rest
pip install --upgrade f5-sdk
```

You should then have 1.0.4 for icontrol rest and 0.1.2 for f5-common ptyhon.

**Comment by himalayanBuddy** [comment]
@swormke 

the issue is fixed. But the message _**About to log pre_message**_. gets printed in each iteration as below. 

```
mailex-a-https-pool
About to log pre_message.
mswebmailex1a:18000
mswebmailex2a:18000
mailex-b-https-pool
About to log pre_message.
mswebmailex1b:18000
mswebmailex2b:18000
```
