### ISSUE TITLE
Make the codebase be Python3 compatible

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-common-python#287]
No reason not to do this now, while it's easy:

https://docs.python.org/3/howto/pyporting.html

**Comment by zancas** [comment]
@caphrim007 Good luck!

**Comment by pcloup** [comment]
still facing issues when trying to work with python3.4 and this lib. urlparse for example, seems to be urllib.parse in 3.4 and has slight differences which causes the py code using F5 icontrol REST module to fail

**Comment by caphrim007** [comment]
@zancas this PR implies that https://github.com/F5Networks/f5-icontrol-rest-python is also python 3 compat. So that compat will need to come before this one

**Comment by wojtek0806** [comment]
Issue Review: This will also require turning on v3.0 on Travis. Looks like this is in hand

**Comment by zancas** [comment]
@caphrim007 how's this going?

**Comment by zancas** [comment]
This is partially completed (see https://github.com/F5Networks/f5-common-python/issues/650 ).

**Comment by wojtek0806** [comment]
is this completed with the latest PR?  @caphrim007 if so lets close this

**Comment by caphrim007** [comment]
@wojtek0806 there is one more PR that I need to send today. then it will be
