### ISSUE TITLE
Support stats for resource objects

### ISSUE THREAD

**Issue by swormke** [F5Networks/f5-common-python#293]
Feature request asked for by @sebastianmaniak Resource objects have a statistics URI associated with them.  For example a get to: `https://host-vm-15/mgmt/tm/ltm/virtual/~Common~test-vserver/stats` will return JSON with the statistics.

We need to decide how to support this, but there are a few options.
1. Add a `get_stats()` function for the base resource object that returns the json from GET.
2. Make it a proper object that would be called like vserver.stats.<mystat>

**Comment by zancas** [comment]
I lean towards a class.

**Comment by wojtek0806** [comment]
Issue Review: I think the above would warrant a method on VS class resource. One of the reasons is the way you have this working in TMSH, to display VS stats you issue the command:

tmsh show ltm virtual exampleserver raw

Of course the "raw" keyword means that the values are not converted into any units. See below output from TMSH help:

```
show ltm virtual blah ?
Options:
  all-properties              Display all properties for the specified items
  default                     Units are determined based on current values
  detail                      Include statistics for all related items
  exa                         All values are displayed in exa-units
  field-fmt                   Show statistics in field format for the specified items
  gig                         All values are displayed in giga-units
  ip-intelligence-categories  IP Intelligence white and black lists categories.
  kil                         All values are displayed in kilo-units
  meg                         All values are displayed in mega-units
  peta                        All values are displayed in peta-units
  port-misuse                 Port misuse policy statistics
  raw                         No conversions are made to any values
  tera                        All values are displayed in tera-units
  yotta                       All values are displayed in yotta-units
  zetta                       All values are displayed in zetta-units
```

Another argument for this being virtual.py method is that we recently implemented command-mixin which allows us to run 'reset-stats' command on the virtual resource.

**Comment by wojtek0806** [comment]
Adding to the above, We could make this a resource method as you can utilize it in pool stats too:

GET to the following /mgmt/tm/ltm/pool/~Common~examplepool/stats

Returns:

"kind": "tm:ltm:pool:poolstats"

Which has its reflection in TMSH:

show ltm pool examplepool raw

And consequently you can run reset-stats command against this resource.

**Comment by wojtek0806** [comment]
This looks like a bigger job, there are more modules than we currently have but even for those that we already have its impressive, i think gradual implementation of those would be the answer, ill start with pool/vs and snat and take it from there.

https://gist.github.com/wojtek0806/8f784a0884cfa2781e942702b55a2f6f

Implementing both resetting stats command and stats should go hand in hand

**Comment by wojtek0806** [comment]
Looking at the output of GET i think going with class was a good idea:

VS:

```
{"kind":"tm:ltm:virtual:virtualstats","generation":28384,"selfLink":"https://localhost/mgmt/tm/ltm/virtual/~Common~stats_test/stats?ver=11.6.0"
```

Pool:

```

{"kind":"tm:ltm:pool:poolstats","generation":28393,"selfLink":"https://localhost/mgmt/tm/ltm/pool/~Common~stat_pool/stats?ver=11.6.0","entries":{"activeMemberCnt":{"value":0},

```

**Comment by wojtek0806** [comment]
Ok so the first prototype will look something like this:

https://gist.github.com/wojtek0806/b98e4c00081474b40da1c507b6cd21f2

The output is ugly. Doing this a bit differently, we can make the stats a part of VS object attribute:

https://gist.github.com/wojtek0806/76fd1c934e2ccb151cded9acfb7033a7

I think we should go with a separate class/mixin that is tied into the virtual object, sort of like sub collection.

**Comment by wojtek0806** [comment]
We could do something like this too:

```
class Stats_s(Collection):
    def __init__(self, Virtual):
        super(Stats_s, self).__init__(Virtual)
        self._meta_data['allowed_lazy_attributes'] = [Stats]
        self._meta_data['attribute_registry'] = {
            'tm:ltm:virtual:virtualstats': Stats}


class Stats(Resource):
    def __init__(self, Stats_s):
        super(Stats, self).__init__(Stats_s)
        self._meta_data['required_json_kind'] = \
            'tm:ltm:virtual:virtualstats'
        self._meta_data['required_load_parameters'] = set()
```

This would allow doing something like this:

```
t = mr.tm.ltm.virtuals.virtual.load(name='testy')
a = t.stats_s.stats.load()
a.entries['syncookie.accepts']['value']

```

If we wanted to have 'syncookie.accepts' as a lazy attribute, it would have to be converted to use an underscore instead of a '.' in its name. Not sure if there is need to do this tho, any opinions? The first proposal would just return json and let the caller deal with processing that json.

**Comment by wojtek0806** [comment]
I found a solution but need assistance in incorporating this mixin into the bigger picture

**Comment by wojtek0806** [comment]
I have got a working prototype, it will allow doing something like this:

```
>>> from f5.bigip import ManagementRoot
mr = ManagementRoot('ltm5', 'admin', 'admin')
vs = mr.tm.ltm.virtuals.virtual.load(name='testy')
stat = vs.stats.load()

(...)

stat.clientside_pktsOut.values()
[None]

```

While I was considering this earlier to have values for counter accessible like this:

```
stat.clientside_pktsOut.value
None

```

Adding additional code just for that might not be worth the effort, since we only have one value per counter, so accessing the values using stat.clientside_pktsOut.values() should be sufficient.

Commit ID to look at code: 

https://github.com/wojtek0806/f5-common-python/commit/d99137f3f1d7c96053a415e152c1c244cc1726aa

**Comment by wojtek0806** [comment]
I would love to do something like this:

```
stat.clientside_pktsOut.value
```

but means to do it are ugly...so if we want accessing the stats values like this i would need some assistance

**Comment by wojtek0806** [comment]
@swormke @zancas

**Comment by pjbreaux** [comment]
I am a +1 for a class as well, and I'm interested to hear arguments for why we shouldn't create it like the stats resource above. Having said that, I also like being able to have a JSON blob of stats to reference. Is it crazy to allow both. Accessing stats the way @wojtek0806 defined above (without the call operator, after a load is done), as well as stashing the raw JSON blob some where to be able to dump it if need be.

**Comment by swormke** [comment]
There are a few ways to think about this and since you can't really CUDE these things it make make more sense to just have an accessor type function.  Probabably want to approach it from the user's point of view.

I would think that if I was going to access it I would do it in two ways:

``` python
my_stats = mgmt.tm.ltm.pools.pool.stats()
my_stat = my_stats.stat_a
```

or

``` python
my_stat = mgmt.tm.ltm.pools.pool.stat_a
```

The first one to me makes the most sense because it will always return the most recent set of stats.  It can probably return a `Stat` object though that you could access via the dotted notation. This also goes with the rule of _if you see a () it is a call to the BIG-IP_. Otherwise you will always have to be updating the object to do it the second way.

**Comment by pjbreaux** [comment]
So we hide the '.value' of each stat, which is what I assume the JSON structure looks like?

**Comment by wojtek0806** [comment]
@swormke @pjbreaux 

I want to do something like this:

https://gist.github.com/wojtek0806/339d3a55de3f66171d62735acae0462c#file-example

This way we can give users of SDK a choice. I was thinking this over and I got eureka moment so it would not be so hard to implement as I first thought

**Comment by wojtek0806** [comment]
Ok I have had some thought and I will modify this a bit:

https://gist.github.com/wojtek0806/eddd8a9bb96af542db5ffe4894e41d76

**Comment by wojtek0806** [comment]
https://github.com/wojtek0806/f5-common-python/commit/2e4282cf6fd4570370002a1bd394aeebc41977a5

**Comment by wojtek0806** [comment]
@pjbreaux @zancas @swormke @caphrim007

**Comment by pjbreaux** [comment]
I like the latest proposal. The callable follows along with what @swormke indicated above. I'd like to see what others think. And I like the raw output. That's awesome. What commands other than 'reset-stats' are supported for stats?

Also, I'd like to hear your thoughts about dropping the stat's value attribute and just having it as vs.stats.clientside_curConns. It seems like something @zancas would be against, and that's why I like it!

**Comment by wojtek0806** [comment]
@pjbreaux : Only reset-stats are supported as it globally resets the stats for the object.

We can drop .value so calling the vs.stats.clientside_curConns. would return a dictionary for example:
{'value':'100'}

The problem i see is that this will be awkward from user's perspective and i think its much more elegant to access value as a property, the same way we access property for say: VirtualServer.

It is important to note that all of the values are Read only, and only way to modify them is to use reset-stats command which will basically reset them to zero or none.

**Comment by zancas** [comment]
Since stats don't support CUDE we shouldn't have it inherit from `Resource` but `PathElement` or `ResourceBase` might be appropriate.   My guess is `PathElement` then add stats specific functions in the form of methods per @swormke 's suggestion..    if I understood it correctly.

Another question, do stats need their own special `StatsCollection` container?

**Comment by wojtek0806** [comment]
This is what I did:

https://github.com/wojtek0806/f5-common-python/commit/8edd4659c198ef887a593adbb9de8e0e9e0fc4b2

**Comment by zancas** [comment]
Folks, we've implemented an `UnnamedResource` since the first drafts of this discussion.  It's now obvious that a `class Stats(UnnamedResource)` class is the right answer.

**Comment by pjbreaux** [comment]
What's your eta for this today?

**Comment by zancas** [comment]
Not sure.    No need for you to wait on it.
It'll be in a state where you can easily merge it by Monday.

**Comment by pjbreaux** [comment]
Ok cool. I'll keep watch. Thanks.
