### ISSUE TITLE
Autogenerated classes have 'allowed_lazy_attribute' elements of type string.

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-common-python#306]

**Comment by wojtek0806** [comment]
Issue Review: Could this be folded under #247 as improvement and general refactor of that utility?

**Comment by zancas** [comment]
I think they're sufficiently different leaving open removing `duplicate`.

**Comment by wojtek0806** [comment]
@zancas given that I have refactored those, are we actually using that tool anymore? since most of the time we code by hand given the increased number of versions that we currently write the code for, I am not sure this kind of tool makes sense anymore.

**Comment by caphrim007** [comment]
I personally don't use th3 auto generator and would be fine with removing it

**Comment by wojtek0806** [comment]
closing this issue as we have refactored the auto generated classes and it seems this tool is not used nowadays
