### ISSUE TITLE
Support for ltm.data-group

### ISSUE THREAD

**Issue by jasonrahm** [F5Networks/f5-common-python#315]
Writing some code with the new library, notices ltm.data-group was missing from the methods.

**Comment by zancas** [comment]
Hiya!  Thanks for opening this issue.

You are correct that we've not implemented the logic for this.

I notice that 'data-group' has 'collection' in the 'kind' JSON value returned by a GET against the URI, and I further notice that there're two resources that are contained under data-group, "internal" and "external".

Do you need more derived URIs than these?   For example I notice that "external" itself has "collection" in its "kind", should I assume you'll want to manipulate the "external" elements therein?

**Comment by jasonrahm** [comment]
Yes, long term would be to support both external and internal data group creation/modification, but short term internal would be fine.

**Comment by jasonrahm** [comment]
for full external data-group support, #346 is a dependency. Not so for internal data-group.

**Comment by zancas** [comment]
Note, support for file upload is now implemented and unittested.

**Comment by zancas** [comment]
OK @jasonrahm you're the official owner of this issue.   I'm happy to sync up with you for ~ 5. hours whenever you're ready.

**Comment by wojtek0806** [comment]
Issue Review: This requires creating data_group.py file, and data-group subcollection. Blocking issue for external data groups has been resolved. Should be easy to implement.
