### ISSUE TITLE
Developer Guide Documentation

### ISSUE THREAD

**Issue by swormke** [F5Networks/f5-common-python#318]
We need a way to explain to developers how they can create new `Collection` and `Resource` objects so that they can more easily contribute to the code base.

@jasonrahm

**Comment by wojtek0806** [comment]
@swormke: Can you advise what is the status of this issue?

Issue Review: I do not think I will add anything here other than it is in progress.

**Comment by jasonrahm** [comment]
I was making progress before some of the sdk was refactored. Now what I had has some broken stuff in it, so I'll need to re-evaluate when I free up some time. Been on PTO 2 of the last 3 weeks so I have quite a bit of cleanup/catchup to do.

**Comment by zancas** [comment]
I'm adding a list of patterns to README.rst.   This is a step in the right direction.

**Comment by wojtek0806** [comment]
i believe this is not resolved
