### ISSUE TITLE
Gather Information on Between Version Behavior

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-common-python#319]

**Comment by wojtek0806** [comment]
See attached, latest baseline test ran against v12 HF1 Unit.
[Test Results - Full_Test_Baseline.zip](https://github.com/F5Networks/f5-common-python/files/194388/Test.Results.-.Full_Test_Baseline.zip)

**Comment by wojtek0806** [comment]
Issue Review. I believe this can be closed as the test suite is more or less passing on V12. This issue will also be resolved by #379

**Comment by zancas** [comment]
OK.
