### ISSUE TITLE
Some Tests Have Hard-Coded Version Numbers

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-common-python#320]
@wojtek0806 
We need to make the version a passable parameter (like the bigip address).

Then tests with a hard-coded dependency on a particular version need to be either (a) upgraded to an abstract version number, or (b) marked with a pytest.fixture that makes that test only run when an appropriate version is specified.

**Comment by wojtek0806** [comment]
Added --release parameter to pytest, appended the test functions to amend parts of the hard-coded links with --release parameter value, set default paremeter value to 11.6.0.
