### ISSUE TITLE
Running test device group, reveals assertion error during assert d1.name == this_device.name. 

### ISSUE THREAD

**Issue by wojtek0806** [F5Networks/f5-common-python#329]
Running test device group, reveals assertion error during assert d1.name == this_device.name. 

> ```
>   assert d1.name == this_device.name
> ```
> 
> E       assert '/Common/v12a....labnet.local' == 'v12a-apm-ltm-....labnet.local'
> E         - /Common/v12a-apm-ltm-test.labnet.local
> E         ? --------
> E         + v12a-apm-ltm-test.labnet.local

Tested the metadata URIs for both objects d1. and this_device.name and found that the culprit seems to be the BIGIP returning different values:

Checking 2 requests using REST API web client:
1. Metadata URI: https://ltm1/mgmt/tm/cm/device-group/~Common~test-group/devices/~Common~v12a-apm-ltm-test.labnet.local/

Result: 

"name": "/Common/v12a-apm-ltm-test.labnet.local"
1. Metadata URI: https://ltm1/mgmt/tm/cm/device/~Common~v12a-apm-ltm-test.labnet.local/

Result: 
"name": "v12a-apm-ltm-test.labnet.local"

**Comment by wojtek0806** [comment]
Testing on v 11.6.0
1. URI: https://172.24.108.10/mgmt/tm/cm/device-group/~Common~SyncFail/devices/~Common~sea-fraczek-ltma.lab.local

Response:

"name": "/Common/sea-fraczek-ltma.lab.local"
1. URI: https://172.24.108.10/mgmt/tm/cm/device/~Common~sea-fraczek-ltma.lab.local

Response:

"name": "sea-fraczek-ltma.lab.local"

Was this test ever passing ?

**Comment by swormke** [comment]
@wojtek0806 Tests pass on our setup:
test/functional/cm/test_device.py::TestDevices::test_device_list PASSED
test/functional/cm/test_device.py::TestDevice::test_device_CURDL PASSED
test/functional/cm/test_device_group.py::TestDeviceGroup::test_device_group_CURDL PASSED
test/functional/cm/test_device_group.py::TestDeviceGroup::test_add_device PASSED
test/functional/cm/test_device_group.py::TestDeviceGroup::test_sync PASSED
test/functional/cm/test_device_group.py::TestDeviceGroup::test_cm_sync PASSED

**Comment by wojtek0806** [comment]
@swormke Can you tell me what is the exact build and platform this is tested against ? Also would you be able to give me output from similiar queries to above so I have some sort of comparison please ? :)
