### ISSUE TITLE
Add_To_Trust and Remove_From_Trust" classes needed

### ISSUE THREAD

**Issue by wojtek0806** [F5Networks/f5-common-python#336]
In version 12 we have the ability to setup device trust via TMSH, this is also possible with REST, need to add the functionality into SDK.

**Comment by pjbreaux** [comment]
@wojtek0806: Do you know if this functionality is available in version prior to 12.0?

**Comment by wojtek0806** [comment]
@pjbreaux This is a new functionality in 12.0 previous versions lack this functionality

**Comment by swormke** [comment]
@zancas and @pjbreaux do you think we should verify version for this and throw an appropriate exception if a user tries it on a version <12.0?

**Comment by pjbreaux** [comment]
Yeah. I tried to implement trust-domains last night (not knowing about this issue), and it caught me.

**Comment by wojtek0806** [comment]
There is an internal F5 ID for that. I will worry about the versioning once we get the command  mixin. There is a quite few usages of command: option. See icontrol rest api user guide section on Commands. I am fighting with that now.

**Comment by pjbreaux** [comment]
Ah, ok. The only other way I know to accomplish this is to deploy an iApp with the config commands. But that has the overhead of pushing an iapp template and deploying a service.

**Comment by zancas** [comment]
If a request is invalid, and we can check it before putting it on the wire, then we do.   Our policy is to protect the User from silly mistakes, and protect the network from useless traffic.   So, I'm +1 on checking versions and raising exceptions before anything goes on the wire.

**Comment by zancas** [comment]
There's another open issue:  https://github.com/F5Networks/f5-common-python/issues/357

that is a prerequisite for this one.

**Comment by zancas** [comment]
There's a `command` pattern that `Add_To_Trust` and `Remove_From_Trust` needs, wherein a 'command'='foo',  keyword-arg pair is added to the submitted JSON in a POST to the device.

e.g.:

https://github.com/F5Networks/f5-common-python/pull/356/files#diff-3e61f22b80d7378f3015da1c1b201798R58

This functionality will be implemented in the sole method of the CommandMixin class.   That method will start like this:
```
def exec_command(self, command, **kwargs):
    kwargs['command'] = command
    ...
```

**Comment by zancas** [comment]
I've moved the suggested form of the `CommandExecutionMixin.exec_command` method into #357.

**Comment by zancas** [comment]
I think version-checking needs its own issue.  Do we already have one?   We should put links to examples of version-checking in that issue.   That will greatly ease the process of designing a general approach....   unless its already designed!  ;)
