### ISSUE TITLE
Add file transfer

### ISSUE THREAD

**Issue by jlongstaf** [F5Networks/f5-common-python#346]
Need support for uploading files. See this DevCentral article for details and code examples for uploading files to BIG-IP:
https://devcentral.f5.com/articles/demystifying-icontrol-rest-part-5-transferring-files?adbsc=social_default55359446&adbid=666661582995255298&adbpl=tw&adbpr=8232052

**Comment by caphrim007** [comment]
Hey I wrote that code! It's totally bug free. "Trust Me" ;-)
