### ISSUE TITLE
Device Group functional tests broken with allowed_lazy_attributes error

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-common-python#364]
When running the the functional tests in test/functional/cm/test_device_group, we get:

```
container = <f5.bigip.cm.device_group.Device_Group object at 0x7f884fc7acd0>, name = 'devices_s'
...
E  LazyAttributesRequired: ('"allowed_lazy_attributes" not in', 'container._meta_data for class Device_Group')
```

After looking at the device_group.py module, I can see that:

`self._meta_data['attribute_registry'] = {
            'tm:cm:device-group:devices:devicescollectionstate': Devices_s
        }`

Which should allow devices_s to be accessed via device_group.

**Comment by pjbreaux** [comment]
Reassigning to @zancas

**Comment by wojtek0806** [comment]
@pjbreaux Can you check my docs page on the subject to see if it helps ?

https://docs.f5net.com/display/~wypior/Configuring+Basics+-+HA%2C+DNS%2C+NTP

**Comment by wojtek0806** [comment]
@pjbreaux @swormke @zancas 

Correct me if I am wrong but it seems you are not defining what device group you are attaching the devices sub-collection to. Devices is a sub-collection so the steps should be something like below:

```
# Load device group to add members
dg = bigip.cm.device_groups.device_group.load(name='Failover-Sync')
# Attach sub-collection resource
dg.devices_s.devices.create(name='ltm1.name', partition='Common')
```

Or in a single line it would look like so:

`bigip.cm.device_groups.device_group.load(name='Failover-Sync').devices_s.devices.create(name='ltm1.name', partition='Common')`

**Comment by pjbreaux** [comment]
Yes, I was not seeing the forest for the trees there. Thanks.

**Comment by wojtek0806** [comment]
can this be closed now ?

**Comment by pjbreaux** [comment]
Yes this can be closed. Closing, but opening a new issue related to functional test that I removed in the process of fixing this.
