### ISSUE TITLE
Add a new private method to Unnamedresourcemixin class

### ISSUE THREAD

**Issue by wojtek0806** [F5Networks/f5-common-python#369]
Currently unnamedresourcemixin class has this private method:

```
    def _get_meta_data_uri(self): 
        endpoint = self.__class__.__name__.lower()
        return self._meta_data['container']._meta_data['uri'] + endpoint + '/'
```

Sometimes the inheriting classes require replacement of underscore with hypens in the URI creation. This leads to a problem whereby the code for creating meta_data URI element is repeated in the child classes.

**Comment by wojtek0806** [comment]
Proposed new method would be something like this:

```
    def _get_meta_data_uri_hyphens(self): 
        endpoint = self.__class__.__name__.lower().replace('_', '-')
        return self._meta_data['container']._meta_data['uri'] + endpoint + '/'
```

**Comment by wojtek0806** [comment]
We could also just add "replace('_', '-')" to the exising method, and while I think it should not be a problem as URIs not containing "_" will just be processed as normal. The issue may arise if we would have "_" in a class name where we do not want to do substitution. For now I just deployed second private method, if somebody thinks otherwise let me know :)

**Comment by zancas** [comment]
I haven't thought about this carefully yet, but at first glance it seems like a nice enhancement.
