### ISSUE TITLE
Add version checking to some SDK elements

### ISSUE THREAD

**Issue by wojtek0806** [F5Networks/f5-common-python#379]
Some of the functionalities are not available in versions < 12.0, therefore they should not attempt to execute if utilized with BIGIP versions < 12

**Comment by wojtek0806** [comment]
@channel

I have been thinking about how do we implement this, and we could go with setting up icontrol version to: 12.0.0 similiar way have done so in FDB:

self._meta_data['icontrol_version'] = '12.0.0'

This however will not prevent the user to send the data over the wire, however in the Pythonic spirit we could implement error catching in the code, and deal with it accordingly. In this instance when we attempt to force unknown version we get 500 error message:

{"code":500,"message":"Can't find specified cli schema data for 12.0.0","errorStack":[]}

So we can either display informative warning or have code do something (the something yet to be determined). 

Another solution wis to upon first connection to the bigip, we determine its TMOS version and set a variable to specific value. Then we could manipulate some of the lazy attributes in organizing collections to either "show" or "hide" respective classes.

If anyone has any other  ideas I would like to hear them :)

**Comment by wojtek0806** [comment]
Issue Review: This issue will require changing v12 specific classes not to execute at all or catch exceptions from REST. Awaiting peer feedback re above comments

**Comment by zancas** [comment]
We should stick to the pattern of protecting the network from unnecessary traffic where possible.   This means we should _NOT_ use the "Ask Forgiveness Not Permission" pattern here.

I think a `self._meta_data['version'] = #` is the correct data structure.
There is a nice side-effect of sending a request during `ManagementRoot` construction, it makes the `()` _always_ send a request, when used in the SDK.   Currently `ManagementRoot` construction is the sole exception to that rule.

I don't like exceptions.   Please implement a request in the construction of the `ManagementRoot` that obtains the `version` of the device and assigns `self._meta_data['version']` to its value.

**Comment by zancas** [comment]
The scope of this issue is restricted to implementing the general mechanism as discussed above, and testing it in a few cases.    Implementing specific cases should be tracked in separate specific issues.

This is because many specific cases are likely part of classes that are not yet implemented at all.

**Comment by wojtek0806** [comment]
There is no way to get the version of the device upon first connection. You need to send a REST query to find that out, after connection has been established. Also Pythonic way is to allow and deal with exceptions which is what we need to do here

**Comment by zancas** [comment]
I agree that we should submit a request to the device during construction/instantiation of the `ManagementRoot` object, see my comment above:    https://github.com/F5Networks/f5-common-python/issues/379#issuecomment-220360062

Using exception handling is not relevant to this part of the design.

**Comment by wojtek0806** [comment]
So how do you want to get device's version? BIGIP will not send that kind of information to you. And querying a device for this each time we connect is inefficient

**Comment by wojtek0806** [comment]
and i was talking about exception handling at the class level not connection. The only way i see this working is if we keep track of version information per each host we connect, so even if we tear down connection we store it when connecting second time

**Comment by zancas** [comment]
Hmmm
Maybe a gist is the right thing...

**Comment by wojtek0806** [comment]
Ok I have been thinking about this further and there are 2 ways we can keep track: per instance or once per host and keep that information for "x" time. The first solution would require to grab the version each time we instantiate BIGIP object, regardless if this is the same host or not. Second solution is to keep a track of it in the superclass in the form of static variable and push it downstream to each instance for a given host. I am tied up into something else at the moment, I will try to put this into some code..but any thoughts on this would be welcome

**Comment by caphrim007** [comment]
The way I usually use the BigIP object is one per BIG-IP. Upon connecting to the BIG-IP (during authentication) one could extract the version from the selfLink as it's always populated. If no version is specified, it uses the default version of the BIG-IP. Otherwise it uses the specified one.

**Comment by wojtek0806** [comment]
The version in the selflink is a schema link, not the software link. Also @zancas said he is against any defaults. I have something done for this but I am trying a different approach. Lets discuss in chat.

**Comment by wojtek0806** [comment]
Regarding the selfLink I was also thinking about it but, given the fact that you can actually get a response like this from v12 unit:

"https://localhost/mgmt/tm/cm/device?ver=11.6.0

This occurs if you simply send GET like this:

https://localhost/mgmt/tm/cm/device?ver=11.6.0

For my second approach, where we just use iControl to connect to bigip and send a query to any object, utilizing ver= x.x.x.x would save us having to parse json, and just grab first self link reference.

**Comment by caphrim007** [comment]
That's an expected behavior because it allows applications that have not yet migrated to the newer version to be allowed to use this old version. BIG-IP will launch a different restjavad service to service the request.

**Comment by wojtek0806** [comment]
This is what i have so far:

```
class ManagementRoot(OrganizingCollection):
    """An interface to a single BIG-IP"""
    def __init__(self, hostname, username, password, **kwargs):
        timeout = kwargs.pop('timeout', 30)
        port = kwargs.pop('port', 443)
        icontrol_version = kwargs.pop('icontrol_version', '')
        if kwargs:
            raise TypeError('Unexpected **kwargs: %r' % kwargs)
        # _meta_data variable values
        iCRS = iControlRESTSession(username, password, timeout=timeout)
        # define _meta_data
        self._meta_data = {
            'allowed_lazy_attributes': [Tm, Cm, Shared],
            'hostname': hostname,
            'port': port,
            'uri': 'https://%s:%s/mgmt/' % (hostname, port),
            'icr_session': iCRS,
            'device_name': None,
            'local_ip': None,
            'bigip': self,
            'icontrol_version': icontrol_version,
            'tmos_version': None,
        }

    @property
    def hostname(self):
        return self._meta_data['hostname']

    @property
    def icontrol_version(self):
        return self._meta_data['icontrol_version']

    @property
    def version(self):
        mgmt_rt = self
        dvcs = mgmt_rt.tm.cm.devices.get_collection()
        for i in range(len(dvcs)):
            if str(dvcs[i].selfDevice) == 'true':
                ver = str(dvcs[i].version)
                self._meta_data['tmos_version'] = ver
```

I have done something using selfLink and iControl too:

```
    @property
    def _version(self):
        connect = self._meta_data['bigip']._meta_data['icr_session']
        base_uri = self._meta_data['uri']
        endpoint = 'tm/sys/'
        uri = base_uri + endpoint
        response = connect.get(uri)
        ver = response.json()
        version = str(ver['selfLink']).split('=')[1]
        self._meta_data['tmos_version'] = version
```

**Comment by zancas** [comment]
Let's move some of the proposed solutions into formats that can be linked here...   inline in the comments, gists?   Links to diffs of commits?   Whatever y'all prefer.

My 0.02 ETH is that using a call to a `version` property from the constructor of the `ManagementRoot` to store the software version is probably the right thing.    I like this for several reasons.  Chat me up if you're curious.

**Comment by wojtek0806** [comment]
https://gist.github.com/wojtek0806/946c003d8eb4f7cd05a5a556f7a0b235#file-gistfile1-txt

This is what i think would be best, given my understanding of property objects.

**Comment by wojtek0806** [comment]
Ok I have a prototype which works, applied it to 2 classes add_to_trust and remove_from_trust

https://github.com/wojtek0806/f5-common-python/commit/7fbff4ae0d8a19c3cf0112d86b56f67c04aeb85d#diff-22a5743c0945357e4ff7cb0fb5aa0a81R359

This is the cleanest solution I can think of, it will require defining self_.tmos_check()  in each class, however the upside is that we will have control over what API endpoints will be accessed on different versions. I have put the self._meta_data['supported_version'] in the ResourceBase as we could apply the same to Organizing collections and collections. (this would require moving self_.tmos_check() in the ResourceBase too) Let me know what you think and if all OK we can add that solution inside all of the SDK classes. Or if you can find a way so we DON'T have to do this on each class that's even better.

**Comment by wojtek0806** [comment]
The above will also fix the URI bug with add-to-trust and remove-from-trust classes #452

**Comment by wojtek0806** [comment]
@zancas @swormke @caphrim007 @pjbreaux

**Comment by caphrim007** [comment]
I'm ok with the last gist that @wojtek0806 proposed there.

I was originally concerned with what to do about attributes that are different between versions, but I realized that this is a case for the py.test decorators that @wojtek0806 used; not a case for the library itself as the library's primitives for the CRUD endpoints are already well handled.

**Comment by zancas** [comment]
@caphrim007 when you say "the last gist" do you mean the diff?

**Comment by wojtek0806** [comment]
new commit as per discussions with @za, and today with great mentoring from @swormke :+1: 
https://github.com/wojtek0806/f5-common-python/commit/c0efd072f1913a1b27b6e2a52fe96535295423dc
