### ISSUE TITLE
Trust_Domains and Trust_Domain should be supported in the cm/trust module

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-common-python#385]
We need to be able to get a list of trusted peers on any given device. This would at least require a load call. The load then requires a trust domain name, such as 'Root'. Below is an example of that request.

`{
  "kind": "tm:cm:trust-domain:trust-domainstate",
  "name": "Root",
  "fullPath": "Root",
  "generation": 4,
  "selfLink": "https://localhost/mgmt/tm/cm/trust-domain/Root?ver=11.6.0",
  "caCert": "/Common/dtca.crt",
  "caCertBundle": "/Common/dtca-bundle.crt",
  "caDevices": [
    "/Common/host-10-0-0-162.openstacklocal"
  ],
  "caKey": "/Common/dtca.key",
  "status": "standalone",
  "trustGroup": "/Common/device_trust_group"
}`

**Comment by wojtek0806** [comment]
@pjbreaux 

I take it this is for v 11.6.0 ?
