### ISSUE TITLE
Sync to group in cm failing to sync

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-common-python#386]
Here's me issuing the command:

> > > from f5.bigip import BigIP
> > > b = BigIP('10.190.20.202', '<un>', '<pw>')
> > > b.refresh()
> > > b.cm.sync('test')

And the BigIP sync status does not update, nor does the 'Last Sync Time' on the device group. My proposed change is based on some info I found in a devcentral question. The suggested command to run to sync is as follows:  `curl -sk -u admin:admin -H "Content-Type: application/json" -X POST -d '{"command":"run","utilCmdArgs":"config-sync to-group pair-group-name"}' https://x.x.x.x/mgmt/tm/cm`

I will implement that and also implement the `config-sync from-group' command as well. I have this change locally and it's working well.

**Comment by zancas** [comment]
@wojtek0806 @tar do y'all have colliding code?  @pjbreaux can you open a PR for this immediately?  Is it tested?

**Comment by pjbreaux** [comment]
So this method (cm.sync) no longer exists in the sdk. It is done via cm.exec_cmd. I believe this is no longer an issue.

**Comment by zancas** [comment]
OK, I'm fine with closing it.

**Comment by pjbreaux** [comment]
Let me double check and I'll close.

**Comment by pjbreaux** [comment]
@caphrim007 or @wojtek0806: is there such a thing as a sync on the mgmt/cm uri? I didn't see it documented anywhere in the rest API references.

**Comment by caphrim007** [comment]
I'm not sure. Reach out to sme-management

**Comment by wojtek0806** [comment]
@pjbreaux : Are you referring to performing config sync to group or from group?

Cause if you do this will be an equivalent to the following tmsh:

run cm config-sync ?

Options:
  from-group    Sync configuration from specified device group.

  recover-sync  Resets the local device configuration and restores trust domain, device, and device-group information to default settings.

  to-group      Sync configuration to specified device group.

**Comment by pjbreaux** [comment]
Sync to group and from group is taken care of by an exec_cmd, but recover-sync is interesting. I'm looking for what is possible at the mgmt/cm uri. Not sure if that is recover-sync?

Thanks

**Comment by pjbreaux** [comment]
Ok so this issue is fixed by the commit: https://github.com/F5Networks/f5-common-python/commit/ae5fc172a8ddf94da4bd6df82c7a409c8a69c8de

This is also a duplicate of issue #404 

The tests that exist for the uri mgmt/cm are those that are related to file transfer and software uploads. If there is a sync at that uri, then the test will be handled there.
