### ISSUE TITLE
Clustering is needed for creating a device service group cluster of multiple BigIPs

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-common-python#400]
We need this feature for several customers. Given multiple BigIP objects, the cluster will perform the following operations:
- Make the BigIPs trusted peers of one another in preparation for clustering
- Create a device service group (or device group in the SDK) to sync failover objects
- Ensure each BigIP device is in the state that we expect it to be in after the previous steps

**Comment by wojtek0806** [comment]
Issue Review: This looks like progressing. The mentioned issues could be folded into this one

**Comment by zancas** [comment]
Please see #208 for some relevant information.
