### ISSUE TITLE
Profile - OCSP- Stapling - Attributes

### ISSUE THREAD

**Issue by wojtek0806** [F5Networks/f5-common-python#401]
So we have this OCSP Stapling LTM profile, and interestingly it has the following required attributes:

proxyServerPool, dnsResolver, trustedCa

The problem is that 2 of them: 'proxyServerPool, dnsResolver' are mutually exclusive ONLY when another parameter 'useProxyServer' has a value of 'enabled'. When that value is set to 'disabled', both parameters can exist together. 

I was thinking in order to fix this we just make 'useProxyServer' as a required attribute, and stick 'proxyServerPool, dnsResolver' into ExclusiveAttributesMixin.

**Comment by wojtek0806** [comment]
Issue Review: This is just a question on implementation #349. This can be closed as it is resolved

**Comment by zancas** [comment]
Interesting.  I'll take this as a reminder to focus on during review.

**Comment by wojtek0806** [comment]
should be closed as PR merged
