### ISSUE TITLE
Functional tests needed for device_groups.device_group.sync()

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-common-python#404]
The api call for this is likely to change to device_groups.device_group.sync_[to | from]_group to be in line with the calls to tm.cm.sync_xx_group.

**Comment by zancas** [comment]
What issue does this duplicate?   Which URIs are affected?

**Comment by zancas** [comment]
Which URIs is this work likely to affect?

**Comment by zancas** [comment]
Where is `class Device_Groups`?  Or does it not yet exist?

**Comment by pjbreaux** [comment]
It should totally exists in ManagementRoot.tm.cm

**Comment by zancas** [comment]
OK, so this issue touches:

`tm/cm/device_group.py`

and potentially:

`cm/device_group.py`

Correct?

**Comment by zancas** [comment]
Anything else?

**Comment by pjbreaux** [comment]
I believe that is it.

**Comment by zancas** [comment]
And it may duplicate #386, but that's also @pjbreaux 's so let's leave it open.

@wojtek0806 @tar do either of you see other code that could/should be touched?   Do either of you intend to touch either of the above modules?  <-- We can return to this question when we look at your issues.   I don't know of any need for me to touch them.

**Comment by zancas** [comment]
OK, I've not heard any other input so I'm now going to label this issue `synced`, and let's move to the next.

**Comment by pjbreaux** [comment]
Duplicate of issue #386. Tests already exists and they were amended by me.
