### ISSUE TITLE
Change the TCP profile for an existing virtual

### ISSUE THREAD

**Issue by kmunson1973** [F5Networks/f5-common-python#406]
I am attempting to change the default TCP profile on an existing virtual  I would like to change it to the won-tcp-wan-optimized.  I am running into an issue with the REST API,  the only way I can accomplish this is by doing a PATCH to https://mgmtip/mgmt/tm/ltm/virtual/~Common~APITest/ with a payload of: {"profiles":["/Common/tcp"]}.  The issue I run into is that is immediately removes all other profiles http, ssl, etc.    What appears to be the issue is you can’t really delete the default tcp profile from the vip if you do a DELETE to https://10.105.157.200/mgmt/tm/ltm/virtual/~Common~APITest/profiles/~Common~tcp it immediately puts it back.  I am hoping through the SDK you guys have a work around for this, otherwise we have to capture the assigned profiles prior to changing the TCP profile then reapply.

**Comment by caphrim007** [comment]
@kmunson1973 

You can only do this with a transaction. The reason is as follows.

As you saw when you tried to delete TCP, BIG-IP re-created it. Then when you tried to add wom-tcp... it rejected it saying it already exists.

Putting it in a transaction lets BIG-IP figure it out correctly, see below example.

```
from f5.bigip import BigIP
from f5.bigip.contexts import TransactionContextManager

# Connect to the BigIP
bip = BigIP("localhost", "admin", "admin", port='10443')

# Create a transaction
tx = bip.transactions.transaction

# Perform the next set of operations from within the above transaction
with TransactionContextManager(tx) as api:

    # select the virtual I want to modify
    virt = api.ltm.virtuals.virtual.load(name='virtual-1')

    # Get a reference to its profiles
    profiles = virt.profiles_s.profiles

    # Load the TCP profile so I can delete it
    tcp = profiles.load(name='tcp')

    # Delete said profile
    tcp.delete()

    # The delete operation changes the list of profiles internally
    # so re-get the list of profiles. Note, this may be a bug with our
    # SDK...so I'll investigate
    profiles = virt.profiles_s.profiles

    # Create the new profile
    profiles.create(name='wom-tcp-wan-optimized')
```

When the Transaction context finishes, the transaction will commit and you'll get the desired behavior. Note that it's kinda similar to what you're doing with PATCH, it's just that with the Transaction method you don't need to keep track of what currently is there. Just remove what you dont need and create what you do.

Hope that helps.

**Comment by kmunson1973** [comment]
@caphrim007 Thank You!!! This worked like a charm. For anyone else that needs to do this over REST here is what I did:
1. POST https://10.105.157.200/mgmt/tm/transaction
   This will return
   {"transId":1463018081826087,"state":"STARTED","timeoutSeconds":120,"asyncExecution":false,"validateOnly":false,"executionTimeout":300,"executionTime":0,"failureReason":"","kind":"tm:transactionstate","selfLink":"https://localhost/mgmt/tm/transaction/1463018081826087?ver=12.0.0"}
2. DELETE https://10.105.157.200/mgmt/tm/ltm/virtual/~Common~APITest/profiles/tcp
   Add the following header with the transId from above
   X-F5-REST-Coordination-ID : 1463018081826087
3. POST https://10.105.157.200/mgmt/tm/ltm/virtual/~Common~APITest/profiles
   Add the following header with the transId from above
   X-F5-REST-Coordination-ID : 1463018081826087

Add the payload of the profile you would like to use.
{
  "context": "all",
  "name": "tcp-lan-optimized"
}
1. PUT https://10.105.157.200/mgmt/tm/transaction/1463018081826087
   With this payload

{
  "state": "VALIDATING"
}

**Comment by zancas** [comment]
Awesome!   I'd like to move to the newer method of:

`from f5.bigip import ManagementRoot` in place of `from f5.bigip import BigIP`

This imports a class that is responsible for the actual `mgmt` root uri.

So the pattern to access `tm` resources would look like this:

``` Python
from f5.bigip import ManagementRoot
bigip = ManagementRoot(ADDRESS, USERNAME, PASSWORD, PORT=NUMBER)
tx1 = bigip.tm.transactions.transaction....
```
