### ISSUE TITLE
Add software update api

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-common-python#425]
The API for specifying Software update checking is not in the SDK. Add it.

**Comment by wojtek0806** [comment]
Issue Review: Looks like this is well in hand

**Comment by zancas** [comment]
Which URIs are relevant to this issue?

**Comment by caphrim007** [comment]
@zancas https://devcentral.f5.com/Wiki/iControlREST.APIRef_tm_sys_software_update.ashx
