### ISSUE TITLE
Tidy up test suite to promote new correct syntax

### ISSUE THREAD

**Issue by wojtek0806** [F5Networks/f5-common-python#427]
Look through functional tests and correct the coding to reflect recent ManagementRoot changes. Also would be good if the tests were made in line with new testing method as discussed in slack

@zancas Do we know exactly what we need for that new testing method ?

**Comment by zancas** [comment]
Obviously, all the tests that were passing before have to pass afterward.

If I were doing this I'd do something like the following.

Replace:

``` Python
from f5.bigip import BigIP

bigip = BigIP(ADDRESS, NAME, PASSWD)
```

with

``` Python
from f5.bigip import ManagementRoot

mgmt_rt = ManagementRoot(ADDRESS, NAME, PASSWD)
bigip = mgmt_rt.tm
```

**Comment by wojtek0806** [comment]
Issue Review: This requires rewriting the functional tests to promote new syntax. We could also tie this into refactoring of testing suite to utilize new method of testing as mentioned by @zancas

**Comment by zancas** [comment]
@caphrim007 @pjbreaux @swormke @wojtek0806 
We're supporting the old syntax `bigip.ltm.FOO` for backwards compatibility.   I want to also maintain the current passing tests that use the old syntax.    They provide us with an assurance that the old syntax is stable.   Let's leave the current tests with the old syntax, but use the new syntax in all new tests going forward.

**Comment by zancas** [comment]
@szakeri @pskergan Please read the above.

If you think this policy is fine, or don't care please give a +1 or +0.   If you don't like it indicate how much with [-.1, -1] and say why, and suggest an alternative that's addresses your concern.

**Comment by zancas** [comment]
This issue can be closed when all the votes are in and concerns are addressed.

**Comment by zancas** [comment]
In the interest of efficiency I reserve the right to act autocratically.

**Comment by wojtek0806** [comment]
i think we can close this one. I am all for new tests using symbols just need some walkthrough how to use them :)

**Comment by wojtek0806** [comment]
closing this as we have #614 opened and engaged on
