### ISSUE TITLE
Partition Issues to Prevent Effort Duplication

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-common-python#429]
StakeHolders:

@zancas

Each issue should have an explicit scope of work ideally mentioning modules-packages-files-directories that will be touched.

Once the scope of work is sufficiently well defined someone needs to curate issues to makes sure no 2 issues define the same effort.

If more than 1 issue describes the same effort the duplicate effort needs to be removed.  If all of the effort is duplicated in more than 1 issue then duplicate issues should be closed during the deduplication process.

Tasks For This Issue:
1. read each open issue
    -  If you know information is missing, add information about which parts of the codebase will be touched.
    -  Remember if effort was duplicated in some previous issue and #mention the duplicating issue in this issue, add the "duplicating!" label to this issue and that issue.
2. Once you've performed 1., remove yourself from the "StakeHolders" list, and assign this issue the next StakeHolder.

DO NOT CLOSE ANY ISSUES.   DO NOT SPEND MORE THAN 5 MINUTES ON ANY ONE ISSUE.

**Comment by wojtek0806** [comment]
Completed review, passing to @pjbreaux

**Comment by pjbreaux** [comment]
Passing to @zancas

**Comment by zancas** [comment]
Got it.
