### ISSUE TITLE
Make trust-domain conditionally RESTful in cluster for v12.0 and greater

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-common-python#431]
These operations are only supported in 12.0 onwards and should be done via REST, instead of iApps.

**Comment by pjbreaux** [comment]
Update the docstring in cluster/**init**.py Cluster after implementing this change.

**Comment by wojtek0806** [comment]
Issue Review: This is a duplicate of #379.

**Comment by pjbreaux** [comment]
Tis a dupe of #379

**Comment by zancas** [comment]
I think #379 is a general mechanism, that is a prerequisite to correctly handling version skew in specific cases.   I think this issue is about the specific case of handling version skew in `clustering`.   I am therefore leaving this issue open.  And removing `duplicating!`.

**Comment by zancas** [comment]
@pjbreaux you need to understand @wojtek0806 's work on #379 to know how to correctly implement the code for this issue.  #379 is a blocking issue.

**Comment by zancas** [comment]
OK @pjbreaux which modules/code do you think this will affect?

**Comment by pjbreaux** [comment]
tm.cm.trust_domains at least.

**Comment by zancas** [comment]
I don't think so.
I think the scope of this issue will be conditionals in how code in the `cluster` package "decides" to call into the `bigip` package.

**Comment by pjbreaux** [comment]
My mistake. You are correct.

**Comment by zancas** [comment]
I believe implementing v12.0 and greater Resource type concrete subclasses, should be tracked in a separate issue.  So I think implementing `tm.cm.trust_domain` shouldn't be considered in the scope of this issue.

**Comment by zancas** [comment]
Since the code that _will_ be touched is all in `multi_device` which is currently exclusively @pjbreaux 's domain, I'm marking this issue as `synced` and moving on.
