### ISSUE TITLE
Allow File and SSL Resource Naming

### ISSUE THREAD

**Issue by mac-reid** [F5Networks/f5-common-python#435]
First off, thanks for creating this! It really helps out.

When creating SSL Certificate/Keys and SSL Profiles, the name of the resource is always set to `certname[:-4]`. See [here](https://github.com/F5Networks/f5-common-python/blob/0.1/f5/bigip/tm/sys/crypto.py#L76-L80), [here](https://github.com/F5Networks/f5-common-python/blob/0.1/f5/bigip/tm/sys/crypto.py#L52-L56), and [here](https://github.com/F5Networks/f5-common-python/blob/0.1/f5/bigip/tm/ltm/profile.py#L59-L62).

I'd like to be able to name of these resources at creation. This is possible from the API and I'd much rather not have to run a modified version just to create the SSL resources with arbitrary names.

**Comment by zancas** [comment]
Thanks @mac-reid!   We're aware of this bug, and have a fix.   It'll be the default in the next release. (This Friday.)   If you need it before then you can pull off the development branch `0.1` where the updated version should land in the next day or two.

**Comment by zancas** [comment]
@wojtek0806 what remains to be done for this?

**Comment by wojtek0806** [comment]
The config element needs some rework later, in conjunction with other improvements of doing BIGIP backups via REST. Another thing on to do list i guess

**Comment by wojtek0806** [comment]
@zancas See my PR that will address this. I removed custom methods install_cert to be in line with the usage of exec_cmd method. We can always keep those methods if you want to.
