### ISSUE TITLE
Allow naming of ssl certificates on import

### ISSUE THREAD

**Issue by waffie1** [F5Networks/f5-common-python#442]
Please allow a name parameter to be passed to tm.sys.crypto.certs.install_cert and tm.sys.crypto.keys.install_key instead of setting the name to certificate filename - last 4 characters.

**Comment by wojtek0806** [comment]
@waffie1 Thanks for that, however this has been reported in #435 . We will address it there :)

**Comment by caphrim007** [comment]
@wojtek0806, this is relevant to a PR that @waffie1 is working on to create an ansible module for the f5-ansible repo.

I'd be happy to review the PR you mentioned to get this in

**Comment by wojtek0806** [comment]
fixed in 0.1.7
