### ISSUE TITLE
Refeactor profile tests so they pass on 11.6

### ISSUE THREAD

**Issue by wojtek0806** [F5Networks/f5-common-python#448]
Refactor some of tests so they are either skipped or passed in 11.6

**Comment by zancas** [comment]
Let's do the right thing and fully implement version support!

**Comment by wojtek0806** [comment]
This has nothing to do with version support, same profiles on two different version can have different attributes. So for example fix protocol profile on 11.6.0 does not have property description, whereas in 12.x this has been added. I had to refactor few of the tests to utilize common properties in v12 and v11.6. Only 3 profiles out of over 50ish are not implemented in 11.6.0. Version support is next in line after the 2 PRs are incorporated
