### ISSUE TITLE
Add upload buffer method to bigip.shared.file_transfer.uploads

### ISSUE THREAD

**Issue by jlongstaf** [F5Networks/f5-common-python#454]
The f5-sdk currently supports file upload to BIG-IP systems (bigip.shared.file_transfer.uploads.upload_file(). We need an interface that supports uploading an in-memory buffer. With the current implementation of f5-sdk we first must write our in-memory buffer to a temporary file and then call upload_file. We need an interface that allows us to pass in a buffer and write the buffer directly to the REST API, preventing a temporary file copy.

**Comment by caphrim007** [comment]
@jlongstaf the current implementation is used to read a file from a disk or disk-like location. You're asking for a way to send data after you have already read it from disk?

**Comment by jlongstaf** [comment]
@caphrim007 We don't read our data (certificates and keys in this case) from the file system -- we get that data directly from a certificate manager via a REST API, so it's all in memory. We'd like to keep it in memory instead of writing to a tmp file.

**Comment by caphrim007** [comment]
@jlongstaf if we changed the function to accept a file-like object, could you put your data in a StringIO object? https://docs.python.org/2/library/stringio.html

**Comment by jlongstaf** [comment]
@caphrim007 That would definitely work for us.
