### ISSUE TITLE
Cannot load an object created by an iApp

### ISSUE THREAD

**Issue by erjac77** [F5Networks/f5-common-python#468]
I would like to know how to load an object (for example a pool) created by an iApp? My understanding is that all the objects created by an iApp are stored in a [apllication_service_name].app folder. The URL to load a pool should look like this :
https://[ip_address]/mgmt/tm/ltm/pool/~TEST_PARTITION~TEST_APP.app~TEST_APP_pool
Actually, this works in on my lab VE LTM (v11.6).

If I put the application service name (using "/" or "~" as delimiter) in the name or partition attribute of the F5 Python SDK's load function, I get an illegal character error:
pool = mgmt.tm.ltm.pools.pool.load(name='TEST_APP.app/TEST_APP_pool', partition='TEST_PARTITION')
pool = mgmt.tm.ltm.pools.pool.load(name='TEST_APP.app~TEST_APP_pool', partition='TEST_PARTITION')
pool = mgmt.tm.ltm.pools.pool.load(name='TEST_APP_pool', partition='TEST_PARTITION/TEST_APP.app')
pool = mgmt.tm.ltm.pools.pool.load(name='TEST_APP_pool', partition='TEST_PARTITION~TEST_APP.app')

Thank you for your help.

**Comment by pjbreaux** [comment]
I was able to deploy an iapp which creates a virtual in a partition called 'test'. I was then able to access that virtual by doing:

```
virtual = b.tm.ltm.virtuals.virtual.load(name='vs', partition='test')
>>> virtual.raw
{u'policiesReference': {u'isSubcollection': True, u'link': u'https://localhost/mgmt/tm/ltm/virtual/~test~vs/policies?ver=12.0.0'}, u'generation': 20, u'enabled': True, u'serviceDownImmediateAction': u'none', u'connectionLimit': 1, u'mirror': u'disabled', u'vlans': [u'/Common/data1'], u'vsIndex': 6, u'source': u'0.0.0.0/0', u'destination': u'/test/10.3.3.13:8000', u'profilesReference': {u'isSubcollection': True, u'link': u'https://localhost/mgmt/tm/ltm/virtual/~test~vs/profiles?ver=12.0.0'}, u'gtmScore': 0, u'translatePort': u'enabled', u'appServiceReference': {u'link': u'https://localhost/mgmt/tm/sys/application/service/~test~test.app~test?ver=12.0.0'}, u'vlansReference': [{u'link': u'https://localhost/mgmt/tm/net/vlan/~Common~data1?ver=12.0.0'}], u'autoLasthop': u'default', u'appService': u'/test/test.app/test', u'rateLimitDstMask': 0, u'nat64': u'disabled', u'sourceAddressTranslation': {u'type': u'automap'}, u'synCookieStatus': u'not-activated', u'sourcePort': u'preserve', u'ipProtocol': u'tcp', u'fullPath': u'/test/vs', u'addressStatus': u'yes', u'kind': u'tm:ltm:virtual:virtualstate', u'name': u'vs', u'translateAddress': u'enabled', u'partition': u'test', u'mask': u'255.255.255.255', u'cmpEnabled': u'yes', u'vlansEnabled': True, u'rateLimit': u'disabled', '_meta_data': {'attribute_registry': {'tm:ltm:virtual:profiles:profilescollectionstate': <class 'f5.bigip.tm.ltm.virtual.Profiles_s'>}, 'container': <f5.bigip.tm.ltm.virtual.Virtuals object at 0x7f57d52b2950>, 'exclusive_attributes': [], 'allowed_commands': [], 'read_only_attributes': [], 'allowed_lazy_attributes': [<class 'f5.bigip.tm.ltm.virtual.Profiles_s'>], 'uri': u'https://10.190.20.202:443/mgmt/tm/ltm/virtual/~test~vs/', 'required_json_kind': 'tm:ltm:virtual:virtualstate', 'bigip': <f5.bigip.ManagementRoot object at 0x7f57d82de690>, 'icontrol_version': '', 'icr_session': <icontrol.session.iControlRESTSession object at 0x7f57d54d1b50>, 'required_load_parameters': set(['name']), 'required_creation_parameters': set(['name']), 'creation_uri_frag': '', 'creation_uri_qargs': {u'ver': [u'12.0.0']}}, u'mobileAppTunnel': u'disabled', u'rateLimitMode': u'object', u'rateLimitSrcMask': 0, u'selfLink': u'https://localhost/mgmt/tm/ltm/virtual/~test~vs?ver=12.0.0'}
```

**Comment by erjac77** [comment]
On my side, when I try to access the virtual without the "subPath" (.app), I get an 404 error:

vs = mgmt.tm.ltm.virtuals.virtual.load(name='TEST_APP_vs', partition='TEST_PARTITION')

iControlUnexpectedHTTPError: 404 Unexpected Error: Not Found for uri: https://[ip_address]:443/mgmt/tm/ltm/virtual/~TEST_PARTITION~TEST_APP_vs
Text: u'{"code":404,"message":"01020036:3: The requested Virtual Server (/TEST_PARTITION/TEST_APP_vs) was not found.","errorStack":[]}'

In fact, I believe the URL should be:
https://[ip_address]:443/mgmt/tm/ltm/virtual/~TEST_PARTITION~TEST_APP.app~TEST_APP_vs
instead of:
https://[ip_address]:443/mgmt/tm/ltm/virtual/~TEST_PARTITION~TEST_APP_vs

I'm running version 11.6.0.

**Comment by pjbreaux** [comment]
And with the subPath, it does work? And I mean the subPath as a named argument to the load call.

https://github.com/F5Networks/f5-common-python/blob/development/test/functional/tm/sys/test_folder.py#L37

**Comment by erjac77** [comment]
Unfortunately, no it doesn't work.

vs = mgmt.tm.ltm.virtuals.virtual.load(name='TEST_APP_vs', partition='TEST_PARTITION', subPath='TEST_APP.app')

TypeError: request() got an unexpected keyword argument 'subPath'

**Comment by pjbreaux** [comment]
Would you mind sharing the snippet of the iApp where this virtual is deployed? Thanks. I'd like to be able to reproduce this exactly.

**Comment by erjac77** [comment]
Sure, here the configuration of the iApp:

list sys application service TEST_APP.app/TEST_APP one-line
sys application service TEST_APP.app/TEST_APP { device-group /Common/SYNC_FAILOVER_DEV_GRP inherited-devicegroup true inherited-traffic-group true partition TEST_PARTITION tables { basic__snatpool_members { } net__snatpool_members { } optimizations__hosts { } pool__hosts { column-names { name } rows { { row { test-app.com } } } } pool__members { column-names { addr port connection_limit } rows { { row { /TEST_PARTITION/TEST_NODE_1 80 0 } } { row { /TEST_PARTITION/TEST_NODE_2 80 0 } } } } server_pools__servers { } } template /Common/f5.http traffic-group /Common/traffic-group-1 variables { client__http_compression { value "/#create_new#" } monitor__monitor { value "/#create_new#" } monitor__response { value "HTTP/1.1 200" } monitor__uri { value / } net__client_mode { value wan } net__server_mode { value lan } pool__addr { value 10.10.10.50 } pool__pool_to_use { value "/#create_new#" } pool__port { value 80 } ssl__mode { value no_ssl } ssl_encryption_questions__advanced { value no } ssl_encryption_questions__help { value hide } } }

and the resulting VS:

list ltm virtual TEST_APP.app/TEST_APP_vs one-line
ltm virtual TEST_APP.app/TEST_APP_vs { app-service /TEST_PARTITION/TEST_APP.app/TEST_APP destination 10.10.10.50:http fallback-persistence TEST_APP.app/TEST_APP_source-addr-persistence ip-protocol tcp mask 255.255.255.255 partition TEST_PARTITION persist { TEST_APP.app/TEST_APP_cookie-persistence { default yes } } pool TEST_APP.app/TEST_APP_pool profiles { TEST_APP.app/TEST_APP_http { } TEST_APP.app/TEST_APP_oneconnect { } TEST_APP.app/TEST_APP_optimized-caching { } TEST_APP.app/TEST_APP_tcp-lan-optimized { context serverside } TEST_APP.app/TEST_APP_tcp-wan-optimized { context clientside } TEST_APP.app/TEST_APP_wan-optimized-compression { } } source 0.0.0.0/0 source-address-translation { type automap } vs-index 934 }

**Comment by pjbreaux** [comment]
Sorry, I'm just getting back to this. Could you give me the actual iApp template you've defined?

**Comment by erjac77** [comment]
I used the default HTTP template provided by F5 (/Common/f5.http).

**Comment by pjbreaux** [comment]
@erjac77: Alrighty, I understand now. It's all in the way the iApp deploys that particular resource. The f5.http iApp deploys a virtual in the subpath of the iApp. I have tested with that template and I see that we now need the subPath to be an argument for any resource which can support one.

**Comment by erjac77** [comment]
@pjbreaux: Should you keep the "critical" label on this issue? F5 strongly recommends their customers to use iApps as much as possible (at least here, in Canada). For now, I use the f5-icontrol-rest API in "full_uri" mode as workaround, since 80% of our applications are deployed using iApps.

Thank you!

**Comment by pjbreaux** [comment]
Yes we can, but I believe this won't be resolved until the next release of f5-sdk.

**Comment by wojtek0806** [comment]
Looks lik this is fixed with iControl patch
