### ISSUE TITLE
get_collection method does not exist on profilesReference

### ISSUE THREAD

**Issue by krambone95** [F5Networks/f5-common-python#469]
Unlike with other subcollections like pool members, it seems I cannot easily access the subcollection or profiles attached to a virtual.

I posted this on dev central:
https://devcentral.f5.com/questions/f5-python-sdk-how-to-get-profiles-on-a-virtual

When I load a virtual object then try to load profilesReference, I cannot get back a collection of profiles. Instead, it only returns the self link.

Thanks!

**Comment by wojtek0806** [comment]
I have looked at the first response in that Devcentral thread and it is correct.  See the GIST link for example:

https://gist.github.com/wojtek0806/0ad62b3acd6c4a4cd7625c76f418e346#file-gistfile1-txt

In your example listed in devcentral you were capturing VS collection, and then looping over it, listing each VS attribute (in your case this was v.profilesReference)

```
    virtuals = srcf5.tm.ltm.virtuals.get_collection()
    for v in virtuals:
            profiles = v.profilesReference
```

For you to access subcollections you need to load a single individual resource and then run get_collection() on that resource attached subcollection. Have a look at the above example. It contains more than profile but it should give you an idea how to proceed.

**Comment by krambone95** [comment]
Thanks! That worked. Couldn't find another place to get help and my F5 rep suggested here. He was right!

```
virt = srcf5.tm.ltm.virtuals.virtual.load(partition="Common", name="my.vip.com")
profiles = virt.profiles_s.get_collection()
for p in profiles:
    print p.name
```
