### ISSUE TITLE
Device group attribute registery is wrong

### ISSUE THREAD

**Issue by szakeri** [F5Networks/f5-common-python#470]
It needs to be changed to tm:cm:device-group:device-groupstate

**Comment by szakeri** [comment]
It needs to be changed to tm:cm:device-group:device-groupstate

**Comment by caphrim007** [comment]
@szakeri is it like that on 11.x and 12.x?

**Comment by szakeri** [comment]
That's a good question. I am testing against 11.6. @pjbreaux do you see this issue on 12 as well?

**Comment by pjbreaux** [comment]
Yes:

> > > from f5.bigip import ManagementRoot as mr
> > > b = mr('<ip>', '<un>', '<pw>')
> > > b.tm.cm.device_groups.get_collection()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/root/common/f5/bigip/resource.py", line 550, in get_collection
> > >     raise UnregisteredKind(error_message)
> > > f5.bigip.resource.UnregisteredKind: u'tm:cm:device-group:device-groupstate' is not registered!

**Comment by caphrim007** [comment]
k. just wanted to make sure it wasn't one of those commands that received a name change during 11->12

**Comment by pjbreaux** [comment]
Setting this for the next release.

**Comment by zancas** [comment]
@szakeri what's the status of this issue?

**Comment by zancas** [comment]
This is fixed, see #579 .
