### ISSUE TITLE
loading existing cluster with devices fails

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-common-python#476]
When creating a cluster, and then instantiating a new ClusterManager object, the code fails with UnexpectedDeviceGroupDevices.

This is because the partition is not being taken in to consideration when creating the given_device_names list

**Comment by caphrim007** [comment]
@pjbreaux this is your world

**Comment by pjbreaux** [comment]
Ah yeah, this only happens on 12.0 right?

This is fixed as of PR #472 
@caphrim007

**Comment by caphrim007** [comment]
we were testing it on 12, yeah

**Comment by pjbreaux** [comment]
Ok cool. I ran all of the func tests yesterday against 11.6 and 12.0 and got all green. That is based on my latest change though. I think there was a difference in the way those devices were reported between 11.6 and 12.0. 11.6 gave back devices in the group by name exactly, and 12.0 gives them back as device names in a partition ('/Common/bigip1').

**Comment by pjbreaux** [comment]
Fixed by PR #471
