### ISSUE TITLE
Mutually exclusive attributes not enforced with resource creation

### ISSUE THREAD

**Issue by wojtek0806** [F5Networks/f5-common-python#481]
ExclusiveAttribute mixin does not prevent from sending mutually exclusive parameters when creating resource

**Comment by wojtek0806** [comment]
Need to think how to apply the fix globally so it covers all use cases. Another thing we can insert into path element i guess

**Comment by wojtek0806** [comment]
@zancas @caphrim007

**Comment by pjbreaux** [comment]
I can imagine something like _check_keys for outgoing requests to sanitize keys.

https://github.com/F5Networks/f5-common-python/blob/development/f5/bigip/resource.py#L219

**Comment by wojtek0806** [comment]
added to 0.1.8 closing
