### ISSUE TITLE
iControlRESTSession needs to support the token=true argument for token auth

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-common-python#487]
Starting with version 12.0 of TMOS token based authentication and authorization is supported by iControl REST.

BIG-IP remote-users access via iControl REST requires token based authorization. f5-common-python access to BIG-IP needs to support token authorization when access BIG-IP devices which are configured for remote-user support. This is a base requirement for all MSPs and most enterprises.

Use of token based authorization needs to be an option parameter for the connection as support for TMOS versions prior to 12.0 is also a requirement.

**Comment by lasko** [comment]
I'm surprised this hasn't been implemented yet. Is there any planned support for this to be implemented in the f5-common-python code?

**Comment by caphrim007** [comment]
@lasko yes. we will need to figure out what is required so that we can test and implement it.

**Comment by wojtek0806** [comment]
a good read that should point us in right direction, shows usage of POSTMAN but should help out with working on this issue: 
https://github.com/f5devcentral/f5-postman-collections/blob/master/F5%20Automation%20%26%20Orchestration%20-%20Introduction.pdf
