### ISSUE TITLE
Minimum version

### ISSUE THREAD

**Issue by alexonab** [F5Networks/f5-common-python#488]
Is 11.5.4 supported?  The error below is from f5-icontrol-rest-1.0.7 and f5-sdk-0.1.7.

> > > nodes = mgmt.tm.ltm.nodes.get_collection()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib/python2.7/site-packages/f5/bigip/mixins.py", line 113, in **getattr**
> > >     container._check_supported_versions(attribute)
> > >   File "/usr/lib/python2.7/site-packages/f5/bigip/mixins.py", line 124, in _check_supported_versions
> > >     raise UnsupportedTmosVersion(error)
> > > f5.bigip.mixins.UnsupportedTmosVersion: There was an attempt to access API which has not been implemented or supported in the device's TMOS version: 11.5.4

**Comment by wojtek0806** [comment]
I believe 11.6.0 is the minimum as a requirement. Unless there is a desire to change that, or decision has been made I am not aware of. For now we only support 11.6.0 or version 12.0.0.

**Comment by wojtek0806** [comment]
Added more verbose indication on what is supported in 0.1.8, therefore closing
