### ISSUE TITLE
Refactor ltm/ssl.py

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-common-python#49]

**Comment by zancas** [comment]
Hmmm....   @swormke  this seems like something we'll need sooner, than later.   I think I'll try to wrap it up before the release.

**Comment by zancas** [comment]
I'm implementing a different set of resources than those listed above because of:

https://devcentral.f5.com/articles/demystifying-icontrol-rest-part-5-transferring-files?adbsc=social_default55359446&adbid=666661582995255298&adbpl=tw&adbpr=8232052

**Comment by wojtek0806** [comment]
I am implementing profiles in the #349 why is the work being duplicated again?

**Comment by wojtek0806** [comment]
@zancas Sorry for reopening this but I looked at the code and I disagree with the way you have implemented it. You do not need to upload certificate to be able to create LTM Client SSL profile. 

The certs themselves are managed under System --> File Management --> Ssl certificate List. 
Proper way to deploy this would be to utilize file upload class to upload the certificate file. Then you can attach it to the profile. This is how it is done via GUI and this is how it is done via TMSH

**Comment by wojtek0806** [comment]
Issue Review: Partially duplicate, will be addressed by #349

**Comment by zancas** [comment]
I did upload and install cert and key via the SDK.    See classes in `share` and `cm`.
