### ISSUE TITLE
Fix the BigIP REST issue where ARPs in the tenant partition are unmanaged

### ISSUE THREAD

**Issue by richbrowne** [F5Networks/f5-common-python#495]
There is an error in the BigIP REST API for ARP objects.  Although I am able to create ARPs using the REST client in the Common and tenant partitions.  I cannot perform an existence test for ARP objects in the tenant partition, we see a HTTP 500 error.  I use a REST client, postman, to navigate to the ARP using the self-link, but it still fails.  This check works for objects in the Common partition though, so just testing that use case is not enough.  When I do a delete on an object that is not contained in the Common partition I get a 200 OK even though the arp was not successfully deleted.

We discussed using SOAP implementation to manage ARP objects as a possible solution.  I refer to the implementation of ARP management in the f5-openstack-agent in network_helper for functions:

add_fdb_entry() -- creates ARP if f5_populate_static_arps is True(default)
delete_arp() -- deletes an arp entry for a given partition and ip address.

@swormke @zancas @jlongstaf

**Comment by jgruber** [comment]
This is a blocker for migrating off of SOAP and the associated set_active_folder problems which are causing:

[https://github.com/F5Networks/f5-openstack-lbaasv1/issues/125](url)

**Comment by wojtek0806** [comment]
@mattgreene @jgruber 

Is there any chance you can clarify the issue, as you mention existence tests and deletion, I would like to sort this one out for you guys, but I am struggling to understand the issue. 

If you have reproduction steps that can be carried with SDK, I can get into this and think of workarounds (if this is REST API bug) or alternative SDK implementation.

**Comment by wojtek0806** [comment]
@mattgreene @jgruber 

can you update this please ?

**Comment by wojtek0806** [comment]
@mattgreene @jgruber any updates on this ?

**Comment by wojtek0806** [comment]
i believe this is now resolved
