### ISSUE TITLE
ltm pool tests are being skipped unnecessarily

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-common-python#508]
An errant "pytest.skip" is in there, but in my tests it works just fine. I think it's related to VLANs and not pools

**Comment by zancas** [comment]
What's the deal with this @caphrim007 ?

**Comment by caphrim007** [comment]
@zancas @wojtek0806 says that due to generation bugs it doesn't work on his metal version of bigip. It works fine on my VE instances
