### ISSUE TITLE
error using fdb on > 0.1.8

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-common-python#532]
I'm using the development branch of code and getting the following error when trying to access the network fdb
icontrol.exceptions.iControlUnexpectedHTTPError: 400 Unexpected Error: Bad Request for uri: https://10.1.1.2:443/mgmt/tm/net/fdbs/tunnel/~Common~vxlan-flannel-tun?ver=11.5.0
Text: u'{"code":400,"message":"Found unexpected URI tmapi_mapper/net/fdbs/tunnel/~Common~vxlan-flannel-tun.","errorStack":[],"apiError":1}'

Seems OK in previous versions.  But it's possible I'm not using it correctly.  

Here's the code:

```
            payload = {
                "partition": "Common",
                "name": vxlan_tunnel_name
            }
            tun_fdb = mgmt.tm.net.fdbs.tunnels.tunnel.load(**payload)
```

Would be useful to be able to populate the records as well..  Similar to what is documented at: view-source:https://support.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/tmos-implementations-12-0-0/9.html "manually populating L2 location records"

**Comment by zancas** [comment]
The URI in the error message is surprising.   "tmapi_mapper/" doesn't match a real URI path-element (as far as I know)...   @wojtek0806 am I wrong?

**Comment by zancas** [comment]
It's also possible there's an issue with an overly enthusiastic version checking algorithm, but I don't see the error I expect in that case.   What version of Python are you running @chen23 ?

**Comment by chen23** [comment]
@zancas running Python 2.7.6 on Ubuntu 14.04 w/ virtualenv.  I'm going to wipe-out the environment to make sure that I didn't pollute it with something that is triggering the issue.

**Comment by chen23** [comment]
@zancas I've tested this further and it works fine on 0.1.6 and does not work with 1.0.0 (as of 2dba23a).  Here's the code:

```

from f5.bigip import ManagementRoot

payload = {
    "partition": "Common",
    "name": 'vxlan-flannel-tun'
}
mgmt = ManagementRoot('10.1.1.2','admin','admin')
tun_fdb = mgmt.tm.net.fdbs.tunnels.tunnel.load(**payload)
payload = {
    "records": [
        {
        "endpoint": "10.1.20.101",
            "name": "1a:89:87:a3:10:4f",
        }
    ],
}

tun_fdb.update(**payload)
```

```
% python add_fdb_record.py
...
Traceback (most recent call last):
  File "add_fdb_record.py", line 9, in <module>
    tun_fdb = mgmt.tm.net.fdbs.tunnels.tunnel.load(**payload)
  File "/home/user/projects/test/0.1.9/local/lib/python2.7/site-packages/f5_sdk-1.0.0-py2.7.egg/f5/bigip/resource.py", line 833, in load
    return self._load(**kwargs)
  File "/home/user/projects/test/0.1.9/local/lib/python2.7/site-packages/f5_sdk-1.0.0-py2.7.egg/f5/bigip/resource.py", line 812, in _load
    response = refresh_session.get(base_uri, **kwargs)
  File "build/bdist.linux-x86_64/egg/icontrol/session.py", line 230, in wrapper
icontrol.exceptions.iControlUnexpectedHTTPError: 400 Unexpected Error: Bad Request for uri: https://10.1.1.2:443/mgmt/tm/net/fdbs/tunnel/~Common~vxlan-flannel-tun?ver=11.5.0
Text: u'{"code":400,"message":"Found unexpected URI tmapi_mapper/net/fdbs/tunnel/~Common~vxlan-flannel-tun.","errorStack":[],"apiError":1}'

```

vs. 0.1.6 no errors.

**Comment by zancas** [comment]
@pjbreaux check this out, look at the "unexpected URI" in the "message" of the exception.

I grepped for that "tmapi_mapper" it doesn't appear in the 1.0.0 codebase...   can you try to replicate, or hand it off to e.g. @wojtek0806 since you're helping him with `Stats`?  Thanks.

**Comment by zancas** [comment]
Or perhaps @szakeri could try to replicate?

**Comment by pjbreaux** [comment]
I believe the string 'api_mapper' was being written to the log somehow right after tm(api_mapper)/net

As for the failure, yes this is a bug, and we'll use this issue to fix it.

**Comment by chen23** [comment]
@zancas FYI changing from "Collection" to "OrganizingCollection" for the Fdbs class seems to "fix" this.  The generated URI for the object is incorrect:

/net/fdbs/tunnel/~Common~vxlan-flannel-tun

vs.

/net/fdb/tunnel/~Common~vxlan-flannel-tun

```

diff --git a/f5/bigip/tm/net/fdb.py b/f5/bigip/tm/net/fdb.py
index 9704718..6b778fd 100644
--- a/f5/bigip/tm/net/fdb.py
+++ b/f5/bigip/tm/net/fdb.py
@@ -33,7 +33,7 @@ from f5.bigip.resource import OrganizingCollection
 from f5.bigip.resource import Resource


-class Fdbs(OrganizingCollection):
+class Fdbs(Collection):
     '''A Collection concrete subclass docstring.'''
     def __init__(self, net):
         '''Auto generated constructor.'''
```

**Comment by pjbreaux** [comment]
@chen23: That does work, but it reveals an actual bug that the organizing collection of 'fdbs' is incorrectly named. It should be 'fdb'.

**Comment by zancas** [comment]
So, the correct class name is "Fdb" and the correct class type is "OrganizingCollection".   We'll have a fix on `development` by the end of the day.  I'll tag the correct version with a bugfix tag.  @chen23

**Comment by zancas** [comment]
@chen23 Thanks for reporting this!
