### ISSUE TITLE
Add tm/util subpackage

### ISSUE THREAD

**Issue by jasonrahm** [F5Networks/f5-common-python#538]
The cli diagnostic and system commands available to tmsh like:
- unix-mv
- unix-rm
- ping
- traceroute
- dig

and others are missing. The unix-rm especially is necessary for cleaning up files uploaded while importing iFiles/External Data-Groups via iControl REST.

**Comment by caphrim007** [comment]
@jasonrahm any idea if any work has gone into this?

**Comment by jasonrahm** [comment]
In my quest to learn git and clean up some mistakes, I blew away some work I had stashed. But I was planning on doing some work with this one after I land the datagroup tests.

Jason

**Comment by caphrim007** [comment]
k

**Comment by jasonrahm** [comment]
Looks like @jgruber's #455 PR has some of the code I was working on for this issue as well. It is tagged help wanted, so I'll pull his PR to my local box and start working on this issue later today.

**Comment by jasonrahm** [comment]
For discussion...please see https://github.com/F5Networks/f5-common-python/pull/671/ for details. Basically, these commands all return 200 whether successful to end-user intent or not. The commandResult field needs to be evaluated for success/failure. Is that something we should take on or leave to the end-user to solve? Note that the data in commandResult is just raw text. Thoughts appreciated.

**Comment by jasonrahm** [comment]
speaking of conventions @zancas, looking for direction on this front. Some of this conversation is in in general between @caphrim007 and me. Just not sure how I should handle providing errors to the users of the sdk since none of these commands return anything but a 200 response. The error information if present is in the commandResult field. Thanks for any advice, haven't found any similar issues pecking through the current state of the sdk.

**Comment by wojtek0806** [comment]
merged so closing
