### ISSUE TITLE
ssl profiles and parent profile inheritance

### ISSUE THREAD

**Issue by waffie1** [F5Networks/f5-common-python#564]
I've found what I believe to be a limitation to the current ssl profile implementation.  When I run update on a profile, it sets the custom flag to enable on all attributes, breaking the inheritance from the parent profile on options I did not intend to modify.

Example, take an existing ssl profile, which has the following configuration:

```
ltm profile client-ssl /Common/test {
    app-service none
    cert /Common/mycert.crt
    cert-key-chain {
        mycert_ca-bundle {
            cert /Common/mycert.crt
            chain /Common/ca-bundle.crt
            key /Common/mycert.key
        }
    }
    chain /Common/ca-bundle.crt
    defaults-from /Common/clientssl
    inherit-certkeychain false
    key /Common/mycert.key
    passphrase none
```

Now perform an update via the SDK

```
profile = mr.tm.ltm.profile.client_ssls.client_ssl.load(name='test', partition='Common')
profile.secureRenegotiation = 'require-strict'
profile.update()
```

The result will be that all options are 'checked' in the WebUI, and the resulting config now looks like this:

```
ltm profile client-ssl /Common/test {
    alert-timeout indefinite
    allow-dynamic-record-sizing disabled
    allow-expired-crl disabled
    allow-non-ssl disabled
    app-service none
    authenticate once
    authenticate-depth 9
    ca-file none
    cache-size 262144
    cache-timeout 3600
    .... shortened, you get the idea ...
```

I understand the REST interface doesn't have the inherited flag like SOAP, but you can just PUT the option you want to modify leaving the other options as is.  the update method apparently does a PUT on every option(having no reference to what was inherited and what was not), and thus removes the inherited flag.  This will really hamper the ability to use the update method and preserve parent profile inheritance.

Is there some other way to do this without breaking the inheritance on options I do not want to modify and need to continue to inherit from the parent profile?

Thanks

**Comment by caphrim007** [comment]
hmm. this is a head-scratcher. I need to ask the REST developers about this one as I dont think it's an sdk limitation.

**Comment by caphrim007** [comment]
@waffie1 what version of BIG-IP are you using??

**Comment by wojtek0806** [comment]
@waffie1 Upon reading the REST user guide, it can be concluded that PATCH should be used for such modifications. I will open an issue for that to have this method implemented:

From the REST guide:

https://devcentral.i131.f5.com/d/icontrol-rest-api-user-guide-version-1210

'''
Using the PATCH method, you can modify properties of a resource without affecting any other properties. 
'''

**Comment by caphrim007** [comment]
I can verify that according to our REST overlords, it is probably due to us not using PATCH. We'll address this

**Comment by waffie1** [comment]
I was testing using v12.1.    I can confirm with native REST(requests) that using PATCH only updates the parameters in the request.  

If I am reading the update code properly, it looks like it adds the entire object dictionary to the request(from the load method, minus collections and a few other things it removes prior to the request)   If you do this, it will still set the 'custom' flag and break inheritance.   For objects with inheritance like ssl profiles, you need to make sure only the options that have changed are part of the request, otherwise you will break the inheritance. 

Example:

Start with a ClientSSL Profile with Secure Renegotiation set to require, inherited from the parent clientssl.

```
s = requests.session()
r = s.get(baseurl + '/tm/ltm/profile/client-ssl/~Common~test')
```

r.json()['secureRenegotiation'] has a value of u'require'

Now PATCH the same value in.

```
data = {'secureRenegotiation' : 'require' }
s.patch(baseurl + '/tm/ltm/profile/client-ssl/~Common~test', data = json.dumps(data))
r = s.get(baseurl + '/tm/ltm/profile/client-ssl/~Common~test')
```

The value of r.json()['secureRenegotiation'] is still require, however it is no longer inherited, the check box is checked in the WebUI, and the option is explicitly set in the bigip.conf

We are going to need update to be a little smarter, or perhaps have another way to modify profile objects types that have inheritance.  Either that or I am wrong about how update works, in which case please correct me.

**Comment by caphrim007** [comment]
@waffie1 we've changed put to patch. Can you run development and see if it fixes your test? We should also add a test to the sdk for this

**Comment by zancas** [comment]
Let's use this issue, and as much of @waffie1 's example code as we can to track and implement the necessary functional test.

**Comment by waffie1** [comment]
Doesn't look like this fixes the problem.  Simply changing to PATCH isn't going to fix the problem.  

We need a method of updating that doesn't pass the entire loaded dictionary in the request, but only includes the variables that need modified(the ones the users specifies).  If you PATCH every single option, it will still unset the inheritance for everything.  See my last example above where patching an inherited value back in unsets the inherited flag.

I don't think var = value followed by update is going to work well for this, unless you want to diff the parent profile from the current to see what changed before the patch request.  I would suggest what was suggested earlier, a modify method that accepts a dictionary of what needs modified.

This is going to be required by every profile type that includes a parent and inheritance.

**Comment by zancas** [comment]
OK, folks after some consideration I'd like to propose that we make `update` behave as a targeted configuration operation.  In particular I'd like for a call to `update` to _ONLY_ submit the explicitly passed (kwarg) attributes in the PATCH json.    Concurrently we'll add a `replace` operation that does the thing that `update` used to do.

**Comment by zancas** [comment]
OK, I've opened a couple of issues that (in combination) should address this one:

https://github.com/F5Networks/f5-common-python/issues/608

AND

https://github.com/F5Networks/f5-common-python/issues/609

**Comment by swormke** [comment]
@zancas Not sure I am in favor of the proposed solution here.  You need to really think about this because you are going to break the API and force a bump in the major version again.  

Second you are going to break this functionality which is in use by your largest user of the SDK (OpenStack):

``` python
a.name = "new_name"
a.description = "new_description"
a.address = "192.168.1.1"
a.update()
```

**Comment by zancas** [comment]
@swormke 's point makes me think that the `update` == [HTTP PUT / replace the config], and `modify` == [HTTP PATCH / configure selected attributes] pattern is probably a better way to go.

**Comment by zancas** [comment]
OK @waffie1 install f5-sdk version 1.2.0 and retry your example with:

`profile.modify(secureRenegotiation='require-strict')`

Do you now get the required behavior?

**Comment by zancas** [comment]
I'm going to add a functional test based on this use-case.

**Comment by zancas** [comment]
OK @waffie1 we now have a functional test that verifies that your specific issue is fixed.

In order to selectively modify the value of `secureRenegotiation` without affecting other attributes do the following:

`profile = mr.tm.ltm.profile.client_ssls.client_ssl.load(name='test', partition='Common')`
`profile.modify(secureRenegotiation='require-strict')`

**Comment by waffie1** [comment]
Thanks everyone.  Everything looks to be working properly with my initial tests.

**Comment by zancas** [comment]
W000T!
