### ISSUE TITLE
During functional testing against 12.1.0, cm/device_group test fails with 'unexpected error'

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-common-python#573]
The test failure is in test/functional/cm/test_device_group.py::TestSyncFromGroup::test_cm_sync_from_group and the message is pretty clear that it is a change in behavior from previous versions to 12.1:

`iControlUnexpectedHTTPError: 400 Unexpected Error: Bad Request for uri: https://10.190.3.57:443/mgmt/tm/cm/
Text: u'{"code":400,"message":"01070734:3: Configuration error: In device group (/Common/test-group), pulling from the device group is not allowed until a push has been done first","errorStack":[],"apiError":3}'
`

**Comment by jasonrahm** [comment]
ok to close this @pjbreaux ?

**Comment by pjbreaux** [comment]
I think so.
