### ISSUE TITLE
During functional testing against 12.1.0, ltm/profile classification test fails with module not provisioned error

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-common-python#576]
One specific profile test, test/functional/tm/ltm/test_profile.py::TestClassification::test_RUL, fails to run with a message indicating that 'afm apm pem' are not provisioned. This may be a candidate for skipping if those modules are not specified in the py.test run command line. I'd like to see what is causing this profile to need those modules however first.

`
iControlUnexpectedHTTPError: 400 Unexpected Error: Bad Request for uri: https://10.190.3.57:443/mgmt/tm/ltm/profile/classification/classification
Text: u'{"code":400,"message":"One of the following features must be licensed/provisioned for the URI ltm/profile/classification : afm apm pem","errorStack":[],"apiError":1}'
`

**Comment by wojtek0806** [comment]
i think this is skipped for now in the tests with the reason for optional module anyway, can we close?

**Comment by wojtek0806** [comment]
this is no longer failing, shall we close ?
