### ISSUE TITLE
During functional testing against 12.1.0, ltm/profile smtp test fails with module not provisioned error

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-common-python#577]
The test fails in a similar way to #576, yet the module provision error is as follows:

`iControlUnexpectedHTTPError: 400 Unexpected Error: Bad Request for uri: https://10.190.3.57:443/mgmt/tm/ltm/profile/smtp/~Common~test.smtp
Text: u'{"code":400,"message":"One of the following features must be licensed/provisioned for the URI ltm/profile/smtp : asm","errorStack":[],"apiError":1}'
`

**Comment by caphrim007** [comment]
This test requires that the ASM module be provisioned. Do we have a convention for marking tests skipif for module provisioning?

**Comment by wojtek0806** [comment]
i think this is skipped for now in the tests with the reason for optional module anyway, can we close?

**Comment by wojtek0806** [comment]
this is no longer failing, shall we close ?

**Comment by pjbreaux** [comment]
Yes sir. Thanks.
