### ISSUE TITLE
SDK should support PATCH method

### ISSUE THREAD

**Issue by wojtek0806** [F5Networks/f5-common-python#578]
Lack of such support leads to issues like this : #564

Implementing a version of update method that uses PATCH would be a good approach.

**Comment by caphrim007** [comment]
So @zancas what do you think? Should we override this specific resource? Change the way the existing _update works? Create a new method called "change" or "modify"? Or something else?

Some food for thought

http://restful-api-design.readthedocs.io/en/latest/methods.html

**Comment by wojtek0806** [comment]
I think having modify() would be a good approach for resources that support both PUT and PATCH, it should be clearly marked in our docs the consequences of using one over the other

**Comment by zancas** [comment]
Can we gather data?   What's the delta in test results if we just switch `put` to `patch` in `_update`?   Basically, we've put a lot of effort into test, let's leverage it!
