### ISSUE TITLE
f5.bigip.tm.cm.device_group.Device_Groups has the wrong registry kind

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-common-python#579]
The correct kind to get a collection of device groups is :

```
'tm:cm:device-group:device-groupstate'
```

not

```
'tm:cm:device:device-groupstate'
```

**Comment by zancas** [comment]
Fixed by:  https://github.com/F5Networks/f5-common-python/commit/5e550055c75d68c027420ce3466d604ddf5c389c
