### ISSUE TITLE
The method formerly known as `update` should remain `update` and should revert to using `put`

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-common-python#608]
The operation supported by `update` needs to migrate to a newly named method (with the exact same logic) named `replace`.

We should also replace `patch` with `put` (the old version) within `replace`.

A global search-and-replace of `update` with `replace` and `patch` with `put` should be sufficient.

**Comment by zancas** [comment]
@jlongstaf @caphrim007 @pjbreaux 
@swormke 's concerns about breaking the interface make me think it's desirable to implement PATCH functionality in a different method...  perhaps `modify`?   Let's choose the right name here!

**Comment by caphrim007** [comment]
according to waffie, it needs to do more than just patch though.

**Comment by zancas** [comment]
@caphrim007 my understanding of @waffie1 's most recent issue is that the current implementation of `update` still submits an update to the `parent` attribute even though it's using HTTP PATCH.    My understanding of the fix is to implement a _selective_ modification of attributes.

**Comment by caphrim007** [comment]
@zancas yeah, but how does only changing that to patch fix things? We already changed to patch and it didn't

**Comment by zancas** [comment]
You're correct, only changing to PATCH didn't fix the issue.

@pjbreaux is implementing an new `modify` method that will use HTTP PATCH, and _only_ submit the dict it is provided in its `patch` parameter to the server.

**Comment by caphrim007** [comment]
@zancas what you just described is the behavior we want. I think i just misread the original issue
