### ISSUE TITLE
A new method named `modify` needs to be a selective operation.

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-common-python#609]
Along with resolution of #608 resolution of this issue is intended to resolve #564. 

The new method `replace` will replace the old update method.    The new `update` will be selective.

Instead of `put`ing the whole configuration object in a request to the server, `update` will only submit the explicitly specified parameters in its kwargs, in a `patch` request to the server.   This feature should be implemented _after_ #608.

Once this feature/issue, _AND_ #608 have successfully landed we should revisit #564.

**Comment by zancas** [comment]
In order to maintain backwards compatibility perhaps we should leave `update` unchanged, and make the new method be named `modify`.

**Comment by pjbreaux** [comment]
Do a sanity check before patch in modify to ensure the user did not submit read_only attributes.
