### ISSUE TITLE
The `bigip` fixture is deprecated.  It needs to be removed to reduce noise.

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-common-python#614]
This issue is in reference to the need to replace big.ip with mgmt_root in the test code; it's making tests fail.

**Comment by zancas** [comment]
Yo @jputrino we should use this issue thread to communicate about this issue.

**Comment by jasonrahm** [comment]
will you be cleaning up test code as well, converting those tests to ManagementRoot? Or will that be a separate effort?

**Comment by jputrino** [comment]
@jasonrahm: Yup, we'll be updating the test code. @zancas and I talked about this last week; I should have some bandwidth for it next sprint (starting next week).

**Comment by jasonrahm** [comment]
ok good deal.

**Comment by wojtek0806** [comment]
I think this was already mentioned and ignored by people here: #427 , i will close #427 to reduce duplication, but please check existing issues so we don't have dupes :)

**Comment by wojtek0806** [comment]
This has been removed somewheat, but the BigIP class is not removed as it would break compat. We have a new issue opened for tracking this, so closing this one
