### ISSUE TITLE
Version 11.5.4 Ipother appears to not support modification of `description` with PATCH, but does not raise an error when `description` is modified via PUT

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-common-python#620]
What's going on here?

**Comment by wojtek0806** [comment]
is it the same on v11.6 and v12?
This sounds like bug to me, can you paste the full stacktrace too ?

**Comment by wojtek0806** [comment]
The description parameter does not exist for IPother in 11.5.x, 11.6 and up have this parameter added only. if you do /example on the uri, it shows you that 'description; parameter is not present. I will close this issue as resolved as we narrowed this down.
