### ISSUE TITLE
Stats Resource Objects Are difficult to use without transformations.

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-common-python#628]
@wojtek0806 has already implemented extensive functionality for manipulating stats after they're obtained.

**Comment by zancas** [comment]
I recommend we pass Stats Resource objects (as defined in `resource.py`) _INTO_ `Stats(BaseHandler)` **init** 's as defined in `f5/utils/responses/handlers.py`.

**Comment by zancas** [comment]
This branch contains @wojtek0806 's DottedDict implementation, and tests, moved into `f5/utils/responses/`:

https://github.com/zancas/f5-common-python/tree/statsmodule3

**Comment by wojtek0806** [comment]
@zancas I am looking at this in tmsh and the more I dig into it, I am inclined to wait until we implement a module fully. i.e LTM with all its endpoints.

**Comment by wojtek0806** [comment]
given the amount of interest this feature generates, I will be doing this next week, watch this thread for updates
