### ISSUE TITLE
consistency for 'partition in required parameters

### ISSUE THREAD

**Issue by wojtek0806** [F5Networks/f5-common-python#640]
As in the title, this issue is created for discussion about the consistency in requirement of 'partition' parameter across the SDK, it seems that in majority of  cases we do not need 'partition' to create resource, however it would make sense to have this globally enforced when creating new resources from now, as a good practice. 

Sidenote: This could eliminate some naming inconsistency of the returned objects between versions.

Thoughts?

**Comment by jasonrahm** [comment]
Personally I'm not a fan of making optional parameters a requirement unless there is a compelling case to do so. For customers who only use the common partition, this is an unnecessary nuisance to configure. 

That said, whatever the decision, consistency is important.

**Comment by chen23** [comment]
Can the parameter be present but silently default to Common or a global parameter that can be changed?  I guess it would be useful to have two use-cases for cases when a default is good/bad and where being explicit is good/bad.  For me the simple use-case makes specifying a partition a nuisance, but the minute that you need to adapt the code for a multi-tenant environment it makes having a partition explicitly set imperative.

**Comment by jasonrahm** [comment]
I think the general decision on defaults was to avoid at all costs.

**Comment by caphrim007** [comment]
I am +1 on the reasonable defaults argument as @chen23 commented. Regardless of the desire to "avoid defaults at all costs", you also do not want to "alienate your user base at all costs".

Remember that people still need to use this tool. People who are not hardcore developers. There needs to be a fantastic user experience behind things like this, or else you'll face people refusing to use your product, and/or developing their own product.

Also, since there is no reasonable threat associated with assuming the Common partition here (unlike there would be if we, say, default the username and password to "admin") I dont think it's a big ask to make "Common" the default.

**Comment by jasonrahm** [comment]
I am +10 on your arguments, just the messenger for earlier understandings.

**Comment by caphrim007** [comment]
fwiw I also spoke to the guy that maintains the iControl REST icrd daemon and he too nodded in agreement at that common default. Customers that use partitions are already well accustomed to type "partition=xxxx" in everything they do. There's no good reason to impose that burden on customers who don't use partitions.

**Comment by wojtek0806** [comment]
ok so it is set then, where applicable we will use partition as required parameter from now on. @chen23 as per Dev Guide rules, we are avoiding defaults at all costs. The SDK must not guess for the user what they are trying to do. 

Any other concerns or we can close this one?
@caphrim007 @jasonrahm @zancas @jlongstaf

**Comment by wojtek0806** [comment]
I think i have changed my mind re: defaults in this case, as I have been reading through documentation and BIGIP supplies the Common as default to most if not all resources, so while we stay away from Defaults, in this case we can mimick BIGIPs behavior in the sense we fill in the partition blanks for them. I guess using something like defaultdict would help here? Or are we just simply going to insert "partition='Common'" into kwargs? The point where we insert that would have to be thought out carefully as some resources in some versions may/may not have "partition" attribute.

+1 for consistency :)

@zancas @caphrim007 @jasonrahm @jlongstaf

**Comment by wojtek0806** [comment]
@zancas @caphrim007 @jasonrahm @pjbreaux 

any further comments? or insights on how we should do it?

**Comment by wojtek0806** [comment]
closing this thread as there is no other responses. We will leave this as it is for now.
