### ISSUE TITLE
The SDK is being used against v 11.6.1 we need to add support to our CI for this.

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-common-python#647]
@caphrim007 if you add an `11.6.1` instance to our CI system I'll be responsible for handling the resultant test failures.

**Comment by caphrim007** [comment]
@za there is a HF1 release for that version. do you want that? or the vanilla release?

**Comment by caphrim007** [comment]
@zancas correction, HF not released yet, the directory is empty :-P

**Comment by zancas** [comment]
@caphrim007 in that case I vote for vanilla!  ;)

**Comment by caphrim007** [comment]
@zancas this is now in production, although there are already some breaking tests
