### ISSUE TITLE
add validateOnly support to TransactionContextManager

### ISSUE THREAD

**Issue by jasonrahm** [F5Networks/f5-common-python#653]
sometimes you just want to validate that a transaction will be successful, but not actually commit the transaction. This can be done by adding this to the patch payload:

`"validateOnly": true`

**Comment by vsnine** [comment]
Jason, did this always exist in the REST API or was it added in a recent version?

**Comment by caphrim007** [comment]
i dont see this in 11.6.1 and you see it in 12, so we're going to assume this is a "more recent" feature. I have a PR for it that I will submit soon
