### ISSUE TITLE
VCMP endpoints need to be added

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-common-python#666]
The VCMP endpoints should be added in the tm organizing collection. A VCMP has a collection of guests. We should be able to retrieve the vlan and management address for a particular guest as well.

The URI is as follows: https://localhost/mgmt/tm/vcmp

```
{
"kind": "tm:vcmp:guest:gueststate",
"name": "bigip-12.0",
"fullPath": "bigip-12.0",
"generation": 373,
"selfLink": "https://localhost/mgmt/tm/vcmp/guest/bigip-12.0?ver=12.0.0",
"allowedSlots":[
1,
2,
3,
4
],
"assignedSlots":[
1
],
"coresPerSlot": 2,
"hostname": "bigip-12.0",
"initialImage": "BIGIP-12.0.0.0.0.606.iso",
"managementGw": "10.190.0.1",
"managementIp": "10.190.5.187/21",
"managementNetwork": "bridged",
"minSlots": 1,
"slots": 1,
"sslMode": "shared",
"state": "deployed",
"virtualDisk": "bigip-12.0.img"
}
```

**Comment by caphrim007** [comment]
Do you if vcmp support exists on VE's? Or will we not be able to test these in the standard way?

**Comment by pjbreaux** [comment]
I'm not sure if it is. We have some Viprion chassis in the lab in Boulder and I am using that currently.
