### ISSUE TITLE
Add ASM specific resource classes

### ISSUE THREAD

**Issue by wojtek0806** [F5Networks/f5-common-python#701]
Resource and UnnamedResource classes need their ASM variation to accommodate for ASM endpoint proper functionality

**Comment by jasonrahm** [comment]
Is there a consistency among the other modules like AFM, APM, AAM with regards to the special cases, or are they all different in how the API is formulated for resource modification?

**Comment by wojtek0806** [comment]
never tested those, I am focusing on ASM, I would expect APM to differ as well, since both products have separate sections in the REST guides

**Comment by wojtek0806** [comment]
this has been merged
