### ISSUE TITLE
LBaaSv2 adding a tagged vlan not functioning using v12.1 and 11.6.1

### ISSUE THREAD

**Issue by thomsonjames** [F5Networks/f5-common-python#713]
I'm testing lbaasv2 with Mitaka, I have a network defined as type vlan with a subnet attached and attached to a router.
When I go to deploy a load balancing configuration. It seems like the vlan tagging code is missing something and not including the "tagMode" parameter in the json.

Attached are log files and neutron commands

[os-vlan-lbaas-bug.txt](https://github.com/F5Networks/f5-common-python/files/483679/os-vlan-lbaas-bug.txt)

**Comment by thomsonjames** [comment]
Let me know if you want this bug filed under the lbaas project since that is where I found it.  https://github.com/F5Networks/f5-openstack-lbaasv2-driver

**Comment by jgruber** [comment]
LBaaS network_helper.py create_vlan does NOT add the tagMode and stopped working when tagMode was added as a required attribute.

**Comment by pjbreaux** [comment]
I've identified the issue. It is here: https://github.com/F5Networks/f5-common-python/blob/development/f5/bigip/tm/net/vlan.py#L101

This fix is two-fold. The sdk should not require tagMode if the version of TMOS is 11.5.4. The other fix is in the agent. It is identified here: https://github.com/F5Networks/f5-openstack-agent/issues/325
