### ISSUE TITLE
Fix GTM tests for 12.1.0

### ISSUE THREAD

**Issue by wojtek0806** [F5Networks/f5-common-python#719]
GTM tests are failing for 12.1.0, will fix this along with #679

**Comment by wojtek0806** [comment]
Spotted issues with v12 and members subcollection:

On v12.0 getting 404 error if we do not specify partition, but object gets created, for pool members subcollection

On v12.1.0 we are getting 404 error even if we specify partition, but object gets created for pool members subcollection

Need to figure out how we get out of this pickle

**Comment by wojtek0806** [comment]
it is a known issue it seems affecting all of v12.x - ID610441

**Comment by jasonrahm** [comment]
wow, that's particularly ugly. Looks like you might need to overload the create method, and if 404, make another call to check that the object was created, and if so, return the object, otherwise, return the 404.

**Comment by wojtek0806** [comment]
already implemented :) just testing stuff before i set PR
