### ISSUE TITLE
Fix net fdb test cases

### ISSUE THREAD

**Issue by jasonrahm** [F5Networks/f5-common-python#733]

**Comment by wojtek0806** [comment]
Stacktrace:

https://gist.github.com/wojtek0806/9ffee29644fca45872f6dad5e3dab366

**Comment by wojtek0806** [comment]
Looks like this also failing in tmsh:

root@(restlab4)(cfg-sync Standalone)(Active)(/Common)(tmos)# modify net fdb tunnel http-tunnel records add { 02:00:00:00:00:01 }
01070734:3: Configuration error: The tunnel FDB record (/Common/http-tunnel 02:00:00:00:00:01) has an empty entry.

Checking docs as we seem to be missing something here

**Comment by wojtek0806** [comment]
looks like we need extra mandatory parameter:

tmsh  modify net fdb tunnel http-tunnel records add { 02:00:00:00:00:01 { endpoint 10.1.1.1}}

root@(restlab4)(cfg-sync Standalone)(Active)(/Common)(tmos)# list net fdb tunnel http-tunnel
net fdb tunnel http-tunnel {
    records {
        02:00:00:00:00:01 {
            endpoint 10.1.1.1
        }
    }
}
