### ISSUE TITLE
Fix sys ntp test cases

### ISSUE THREAD

**Issue by jasonrahm** [F5Networks/f5-common-python#734]

**Comment by wojtek0806** [comment]
This one is a false positive as when i went through it step by step 'servers' attribute was not present:

https://gist.github.com/wojtek0806/4ead7ea40c6fa1d55dd8fdfb08cb80c4

**Comment by wojtek0806** [comment]
https://gist.github.com/wojtek0806/86fc18e0b3b70ae0d21a470343f8e313
