### ISSUE TITLE
Examples on creating user accounts / delete  / modify

### ISSUE THREAD

**Issue by Mudpuppy12** [F5Networks/f5-common-python#746]
Is there any examples on how one would create user accounts / delete / modify? Is this functionality added to the SDK?

**Comment by caphrim007** [comment]
@Mudpuppy12 yes

`api.tm.auth.users.user.create(**params)`

can be used to create an account. For example, the following

```
name = "foo"
password = "secret"
api.tm.auth.users.user.create(name=foo, password=secret)
```

Modifying can be done by first loading the object, then changing parameters, and then calling `update()`

```
user = api.tm.auth.users.user.load(name="foo")
user.description = "bar"
user.update()
```

Deleting can be done by doing the aforementioned `load` and then calling `.delete()` on the object.

```
user = api.tm.auth.users.user.create(name="foo")
user.delete()
```

**Comment by Mudpuppy12** [comment]
Thank you very much. This clarifies how the sdk works for me in my mind. I just didn't know where to find the details of exactly what **parms are, naming, and what can be passed.

**Comment by caphrim007** [comment]
np.

if you have BIG-IP >= 12.0, you can view all the parameters by going to https://BIGIP/mgmt/toc

For earlier versions of BIG-IP, you'll need to refer to good intuition and the online REST docs.

**Comment by caphrim007** [comment]
@Mudpuppy12 we also have this Ansible module available to do many of the manipulations. Or I should say, "will" be available, as it requires version 13 due to some bugs that were fixed in BIG-IP

https://github.com/F5Networks/f5-ansible/blob/master/library/bigip_user.py

If that piques your interest.

**Comment by wojtek0806** [comment]
closing as resolved
