### ISSUE TITLE
Group functional/unit testing in the source trees

### ISSUE THREAD

**Issue by jasonrahm** [F5Networks/f5-common-python#765]
Moving functional tests from standalone folder into the folder structures close to the source. Tests will be broken into unit/ and functional/ subdirectories for each module.

**Comment by jasonrahm** [comment]
@caphrim007 or @zancas, feedback appreciated on these tests:

How would I classify the tests in [f5/utils/test](https://github.com/F5Networks/f5-common-python/tree/development/f5/utils/test)? I guess they are technically functional tests, but wanted to be sure before making that change.

Where would [test/functional/test/test__init__.py](https://github.com/F5Networks/f5-common-python/blob/development/test/functional/test/test__init__.py) move to? Same question for [test/functional/test_requests_params.py](https://github.com/F5Networks/f5-common-python/blob/development/test/functional/test_requests_params.py).

There doesn't seem to be anything in [test/functional_test_nat](https://github.com/F5Networks/f5-common-python/blob/development/test/functional_test_nat.py) that isn't already covered in the [test_nat functional test](https://github.com/F5Networks/f5-common-python/blob/development/test/functional/tm/ltm/test_nat.py)

**Comment by caphrim007** [comment]
@jasonrahm  f5/utils/test is unit tests.

here's the barometer I would use for judging.

http://stackoverflow.com/questions/2741832/unit-tests-vs-functional-tests

the test__init__.py and test_requests_params.py can hang off here

https://github.com/F5Networks/f5-common-python/tree/development/f5/bigip

test/functional_test_nat can be deleted in favor of the second you mentioned, because it looks za specific.

**Comment by jasonrahm** [comment]
merged today, closing this out.

**Comment by jasonrahm** [comment]
and re-opening..forgot I still have ASM tests to move once merged and cleanup of the test/ folder.

**Comment by wojtek0806** [comment]
@jasonrahm 
rebased and did some squashing on my PRs, moved my ASM tests now, you can remove the old tree after ASM is merged

**Comment by jasonrahm** [comment]
old tree removed in PR #777, closing this out.
