### ISSUE TITLE
device_group.py attribute_registry issue

### ISSUE THREAD

**Issue by pmaag** [F5Networks/f5-common-python#778]
Hi There,
Testing out OpenStack with an F5 HA pair running 12.1.1 and are receiving the following error:

2016-10-14 21:22:40.776 30112 ERROR neutron UnregisteredKind: u'tm:cm:device-group:device-groupstate' is not registered!

Looking at f5-common-python/f5/bigip/cm/device_group.py line #41, the following looks to be incorrect:

`self._meta_data['attribute_registry'] =\
            {'tm:cm:device:device-groupstate': Device_Group}`

Looking at the API reference it looks like it should be:

`self._meta_data['attribute_registry'] =\
            {'tm:cm:device-group:device-groupstate': Device_Group}`

Snip from a REST call to /mgmt/tm/cm/device-group/:

`"items": [
    {
      "kind": "tm:cm:device-group:device-groupstate",
      "name": "device_trust_group",`

**Comment by jasonrahm** [comment]
what version of the library are you using? The current release (1.5) appears to be correct:

https://github.com/F5Networks/f5-common-python/blob/v1.5.0/f5/bigip/tm/cm/device_group.py#L34-L40

**Comment by pmaag** [comment]
Yep, was looking at the master branch...Did not realize things are managed under tags.
