### ISSUE TITLE
Checking existence of LTM rule in 11.6.0 always returns true

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-common-python#790]
An LTM policy can have a rule or set of rules attached to it. When checking the existence of a rule in 11.5.4 and 12.1.0, the behavior is the same. If the rule exists, we return True (200 OK) from the exists() call, False otherwise. In 11.6.0 however, the device returns a 200 OK regardless of whether the rule exists or not. We can fix this in the concrete subclass by attempting a load on the rule before returning.

**Comment by pjbreaux** [comment]
The load also succeeds, regardless of whether the rule exists or not. So it looks like we'll have to use get_collection from the parent to implement this.

**Comment by wojtek0806** [comment]
closing as this is merged already
