### ISSUE TITLE
add actions API to sys/application/template

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-common-python#795]
This collection is not exposed to the API, but allows for getting the implementation, presentation, etc values from an iApp template

**Comment by wojtek0806** [comment]
@caphrim007 any update on this? need a hand ?

**Comment by caphrim007** [comment]
the apis do not expose all of the things that you can do with iapps, so i elected to just not use these apis and instead upload iapps and then use the Bash API to just do a template load.
