### ISSUE TITLE
add tm/gtm

### ISSUE THREAD

**Issue by dikshakaustubhi** [F5Networks/f5-common-python#797]
to support creating and manipulating like region, topology, wideip using the F5 SDK

**Comment by wojtek0806** [comment]
Thanks, as we discussed on Lync, I will take care of it, some of the features are already in. Let me know which that are missing you need first.

**Comment by dikshakaustubhi** [comment]
I need the following now so it would be great if you could start with them-
tm/gtm/region
tm/gtm/topology
tm/gtm/datacenter
tm/gtm/listener

Thanks for picking this.

**Comment by wojtek0806** [comment]
tm/gtm/datacenter - exists already, but I have added the rest of them.

Clone the following repository and test please:

https://github.com/wojtek0806/f5-common-python/tree/gtm_features

Mind you this is just a draft code, without any tests written yet. Once I have done them then you can pull our development branch and use that, until we do another release cycle.

@dikshakaustubhi

**Comment by wojtek0806** [comment]
@dikshakaustubhi i will have this ready for official 2.0.1 release as it did not make it this time around (for 2.0.0), for now please use my branch, ill let you know when I will have this merged into dev branch, and when it is released into official package

**Comment by dikshakaustubhi** [comment]
Thanks for doing this. I will test it and then use it in our in-house automation, once it is released.

**Comment by wojtek0806** [comment]
be aware that GTM regions might be disabled for 12.x due to a rather serious bug, but I am still contemplating this.

the bug ID501258

**Comment by wojtek0806** [comment]
there seems to be an issue with topology records, working on that now.
@dikshakaustubhi

**Comment by wojtek0806** [comment]
Blocking issue:

https://github.com/F5Networks/f5-icontrol-rest-python/issues/119

**Comment by wojtek0806** [comment]
I have submitted 3 PRs today, so once we get Jenkins fixed (need @caphrim007 for this) to start testing this should be merged.

@dikshakaustubhi

**Comment by wojtek0806** [comment]
closing as this has been merged
