### ISSUE TITLE
Absence of "policies" attribute in ASM class

### ISSUE THREAD

**Issue by ghost** [F5Networks/f5-common-python#828]
Please add support for "policies" sub collection (tm.asm OC).

```
In:
  policies = mgmt.tm.asm.policies
  print(policies.raw)

Out:
AttributeError: '<class 'f5.bigip.tm.asm.Asm'>' object has no attribute 'policies'
```
- Appears there's no class element for the "policies" reference URI yet (thus not supported)

```
In:
  asm = mgmt.tm.asm
  print(asm.raw)

Out:
...some output omitted...
[<class 'f5.bigip.tm.asm.attack_types.Attack_Types_s'>,
<class 'f5.bigip.tm.asm.file_transfer.File_Transfer'>, 
<class 'f5.bigip.tm.asm.signature_sets.Signature_Sets_s'>, 
<class 'f5.bigip.tm.asm.signature_statuses.Signature_Statuses_s'>, 
<class 'f5.bigip.tm.asm.signature_systems.Signature_Systems_s'>, 
<class 'f5.bigip.tm.asm.signature_update.Signature_Update'>,
<class 'f5.bigip.tm.asm.signatures.Signatures_s'>, 
<class 'f5.bigip.tm.asm.tasks.Tasks'>]
```

**Comment by jasonrahm** [comment]
thanks @hannesrapp.

**Comment by wojtek0806** [comment]
missing subcollections/sub-endpoints:

11.5.4:

see attached json

11.6.0:

see attached json

 11.6.1:
 
see attached json

12.0.0:

see attached json

12.1.0:

see attached json




[policies_json_dump.zip](https://github.com/F5Networks/f5-common-python/files/661488/policies_json_dump.zip)

**Comment by ghost** [comment]
O-la-la

Thanks for terrific work guys!

**Comment by wojtek0806** [comment]
ill reopen it as ill use this issue to track adding some of the subcollections to ASM policies :) so they are there but not 100% complete. I am hoping to sort this out beginning of Jan :)

**Comment by wojtek0806** [comment]
endpoint completed, merged
