### ISSUE TITLE
Invalid state when updating a node

### ISSUE THREAD

**Issue by erjac77** [F5Networks/f5-common-python#840]
**What did you do?**

Updated the description of a node.

**What did you expect to see?**

Node successfully updated.

**What did you see instead? Under which circumstances?**

I got an invalid property value error message for the state attribute.

```
Text: u'{"code":400,"message":"invalid property value \\"state\\":\\"checking\\"","errorStack":[]}'
```

**Steps to reproduce the issue**

```
from f5.bigip import ManagementRoot
mgmt = ManagementRoot("x.x.x.x", "admin", "admin")

mynode = mgmt.tm.ltm.nodes.node.create(name='mynode', partition='Common', address='11.11.11.11', monitor="/Common/icmp")
mynode.description = "my node"
mynode.update()

/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/f5/bigip/tm/ltm/node.py", line 82, in update
    return self._update(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/f5/bigip/resource.py", line 511, in _update
    response = session.put(update_uri, json=data_dict, **requests_params)
  File "/usr/local/lib/python2.7/dist-packages/icontrol/session.py", line 241, in wrapper
    raise iControlUnexpectedHTTPError(error_message, response=response)
icontrol.exceptions.iControlUnexpectedHTTPError: 400 Unexpected Error: Bad Request for uri: https://x.x.x.x:443/mgmt/tm/ltm/node/~Common~mynode/
Text: u'{"code":400,"message":"invalid property value \\"state\\":\\"checking\\"","errorStack":[]}'
```

As per the documentation, the only acceptable values for state are:
`state [user-down | user-up]`

The SDK should check if the returned value is valid before sending the rest call. If not, the state attribute can be omitted.

**Comment by wojtek0806** [comment]
@erjac77 

I think if you used modify() instead this would not happen, when we do update() we use PUT, which forces bigip to fill in the blanks for the rest of the values with defaults, which would probably lead to the issue. So what happens when you just use modify() ?

So that 'state:checking' was probably set by BIGIP internally, resulting in error.

**Comment by erjac77** [comment]
@wojtek0806, thank you for your response!

Using modify didn't help. I got a bad request:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/f5/bigip/resource.py", line 402, in modify
    self._modify(**patch)
  File "/usr/local/lib/python2.7/dist-packages/f5/bigip/tm/ltm/node.py", line 90, in _modify
    super(Node, self)._modify(**patch)
  File "/usr/local/lib/python2.7/dist-packages/f5/bigip/resource.py", line 394, in _modify
    response = session.patch(patch_uri, json=patch, **requests_params)
  File "/usr/local/lib/python2.7/dist-packages/icontrol/session.py", line 241, in wrapper
    raise iControlUnexpectedHTTPError(error_message, response=response)
icontrol.exceptions.iControlUnexpectedHTTPError: 400 Unexpected Error: Bad Request for uri: https://x.x.x.x:443/mgmt/tm/ltm/node/~Common~mynode/
Text: u'{"code":400,"message":"one or more properties must be specified","errorStack":[]}'
```

You are right, 'state:checking' was set by the BIP-IP. However, the sdk blindly returned that value during update, even if it was an invalid state. Maybe it is the desired behavior, since I read in the README that "The SDK is stupid" and "The SDK never interprets responses".

But I think checking the returned value would make sense in this case (at least for nodes and pool members). If the state returned by the BIG-IP system is not 'user-down' or 'user-up', the attribute can be omitted.

**Comment by wojtek0806** [comment]
@erjac77 , we have no way of controlling of what BIGIP fills in as the 'said' blanks, as this is done internally.

The only thing I think we can do is to start enforcing update and modify parameters that should be provided to BIGIP on some endpoints, similarly to the way we check for required creation parameters. In your case this method would check for existence of 'state' attribute.

**Comment by wojtek0806** [comment]
@erjac77 I have tested this with REST client against 11.5.4 unit and I can do both PUT or PATCH. What version were you testing this against?

**Comment by wojtek0806** [comment]
I believe i found the problem inside SDK, will work on a fix now

**Comment by wojtek0806** [comment]
This is how we deal with node in bigip, when we set it on Enabled (and there are no monitors attached):

- enabled:

session: user-enabled, 
state: unchecked

- disabled:

session: user-disabled
state: unchecked

-  forced offline:

session: user-disabled
state: user-down

We also disable the node by setting 'state' to user-down, this will set the state as Forced Offline and we see this in GUI:  Offline (Enabled) - Forced down, REST call will return the following values:

  session: user-enabled
  state: user-down
  
The state can be set to user-up, to bring back the node


When we have health monitor attached, the session value will be as follows:

session: monitor-enabled
state: checking (this state will change automatically, so it could be up, or down too)

- disabled:

session: user-disabled
state: unchecked/up/down etc.

-  forced offline: (sending those 2 parameters would cause the monitor to be removed from the node in 12.1.0, need to prevent users from doing this)

session: user-disabled
state: user-down 

We also disable the node by setting 'state' to user-down, this will set the state as Forced Offline and we see this in GUI:  Offline (Enabled) - Forced down, REST call will return the following values:

  session: monitor-enabled
  state: user-down

**Comment by wojtek0806** [comment]
@erjac77 

The error for your modify method is because we need you to provide **kwargs , unlike update() method, modify, does not allow doing something like so:
```
node.description = 'testing this'
node.modify()
```

Correct way is:
```
node.modify(description='testing this')
```
The reason behind it is that modify is used to change a small number of parameters, usually 1 or 2, hence the need for **kwargs.

For this reason modify() method only sends the contents of **kwargs in the json payload. While update(), sends the entire object \_\_dict\_\_ (minus _meta_data)

I hope this clarifies the difference.

I might speak with rest of the guys if we wanna change update() behavior to only accept **kwargs. However, I am against this change,  as update() uses HTTP PUT and it might lead to situations where if we have an existing object on bigip with some configured values, and we issue update() and not provide those values in the json payload the bigip might substitute this with its own internal defaults, leading to undesired configuration changes on the object.

**Comment by erjac77** [comment]
Sorry, for the late response.

@wojtek0806, thank you for the clarifications about the update/modify methods. Very interesting!

I'll test #974 against my setup shortly. I'll let you know.

**Comment by erjac77** [comment]
It seems to work seamlessly for nodes now, but not for pool members...

**Comment by wojtek0806** [comment]
please open a separate issue for pool members, and post some example errors and I will look at it :)

**Comment by wojtek0806** [comment]
@erjac77

**Comment by wojtek0806** [comment]
new issue opened, ill look into this, but it would be great if you provided me with some example stack-traces output/repro steps in the new issue #985 

@erjac77
