### ISSUE TITLE
Creating snat with description is not possible

### ISSUE THREAD

**Issue by bens95** [F5Networks/f5-common-python#863]
Line 90 of snat.py
`if len(rcp - required_singles) != (pre_req_len - 1):`
seems to force the acceptance of only 4 arguments. Since there are 4 required arguments (name, partition, origins,automap/snatpool/translation), optional arguments including description can not be added. The following code will fail:

```
from f5.bigip import ManagementRoot
mgmt = ManagementRoot('10.128.1.145', 'admin', 'admin')


newSnat = mgmt.tm.ltm.snats.snat.create(name='test',partition='Common',description='this will fail', origins=('2.2.2.2','3.3.3.3'),translation='1.1.1.1')
```

bypassing this if statement allows correct creation of the SNAT

**Comment by caphrim007** [comment]
I can verify this behavior, and I have a patch incoming to address it. thanks for the report @bens95

**Comment by caphrim007** [comment]
@bens95 if you have a moment, can you look at the changed files here

https://github.com/F5Networks/f5-common-python/pull/864

and have a go at applying them in your environment?

thanks

**Comment by bens95** [comment]
Yep, looks good.
