### ISSUE TITLE
install requires dependencies should have upper bounds

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-common-python#915]

**Comment by wojtek0806** [comment]
@zancas has this been fixed with #950 ?

**Comment by ssorenso** [comment]
This can be done in the `setup_requirements.txt` file.  The proper means to input this is:
module<version
So Example:
`python-six<2.0.0`

You can short-case this to `<2`; thus, truncating the '0.0' out.  However, there is additional logic to address this, thus, you're depending on that additional logic to work.  More moving parts, and all that.

**Comment by wojtek0806** [comment]
closing as merged
