### ISSUE TITLE
Error when pulling stats from Virtual in Python 3.x

### ISSUE THREAD

**Issue by KDaveC** [F5Networks/f5-common-python#926]
I'm using Python 3 and trying to get stats from a Virtual Server without any luck. I can get the print raw but everything else throws an error. Any help would be appreciated. Code snippet looks like this.
vip = bigip.ltm.virtuals.virtual.load(name='TEST-VIP100')
stat = vip.stats.load()
print (stat.raw)   - WORKS FINE
print (stat.clientside.bitsIn) - ERROR

ERROR:
Traceback (most recent call last):
  File "C:\python\virtstat.py", line 16, in <module>
    print (stat.syncookieStatus)
  File "C:\Users\dave\AppData\Local\Programs\Python\Python36-32\lib\site-pack
ages\f5\bigip\mixins.py", line 118, in __getattr__
    raise LazyAttributesRequired(error_message)
f5.bigip.mixins.LazyAttributesRequired: ('"allowed_lazy_attributes" not in', 'co
ntainer._meta_data for class Stats')

**Comment by wojtek0806** [comment]
only Raw is supported for stats. Stats transformation are on my to do list..see issue 
https://github.com/F5Networks/f5-common-python/issues/628

**Comment by KDaveC** [comment]
Ok thank you. At least I know it wasn't something I was doing wrong.

**Comment by wojtek0806** [comment]
closing as this is a known limitation
