### ISSUE TITLE
Adding LTM policy to a virtual server produces 404, but succceeds anyway

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-common-python#968]
Most of the content of this issue is captured in the agent bug found [here](https://github.com/F5Networks/f5-openstack-lbaasv2-driver/issues/420). This failure seems to occur on BIG-IP 11.5.4, but the fix here will protect other BIG-IP versions as well.

When doing a POST to add a policy to a virtual server, the policy is actually added, but REST returns a 404.

```
{
"code": 404,
"message": "Object not found - /Project_0b6a552bae994078b3b3754b61747abe/test_policy",
"errorStack": [],
}
```

In addition to this, when trying to GET that policy after it has been added, this also fails. We need a workaround in the sdk, and we need new tests to check this behavior.

**Comment by wojtek0806** [comment]
duplicate #833 ?

**Comment by pjbreaux** [comment]
@wojtek0806: hah, good catch. I don't even remember last week half the time. Thanks.

**Comment by wojtek0806** [comment]
will keep this one open until we implement fix for #833

**Comment by wojtek0806** [comment]
11.5.4:

- We cannot get collection as the 'items' is nested inside policiesReference:
````
{
  "kind": "tm:ltm:virtual:policies:policiescollectionstate",
  "selfLink": "https://localhost/mgmt/tm/ltm/virtual/~Common~testy/policies?ver=11.5.4",
  "policiesReference": {
    "link": "https://localhost/mgmt/tm/ltm/virtual/~Common~testy/policies?ver=11.5.4",
    "isSubcollection": true,
    "items": [
      {
        "kind": "tm:ltm:virtual:policies:policiesstate",
        "name": "bugtest",
        "partition": "Common",
        "fullPath": "/Common/bugtest",
        "generation": 102,
        "selfLink": "https://localhost/mgmt/tm/ltm/virtual/~Common~testy/policies/~Common~bugtest?ver=11.5.4"
      }
    ]
  }
}
````
- GET to the selfLink results in 404

Fix for this should more or less follow this logic:

- Overwrite get_collection() method to handle the above peculiarity
- Create the subcollection as normal
- Intercept the 404 error that comes back
- Since GET to selfLink also breaks, issue get_collection() and iterate through list of 'items' 
looking for the 'name' attribute that would match the object we created. This is necessary as we will probably have more than item in there
- Modify load() method for virtual.policys_s.policys object so it utilizes get_collection() mechanism as described above.

**Comment by wojtek0806** [comment]
I have a gripe with the way this was not tested and some of the syntax for class names you used, i.e not following plural or _s ending for collections and singular for resource. As this is inconsistent with most of the class names. We will have to address this (among other classes that are also breaking this naming convention) in next major release as it will probably break compatibility.

I will add more testing for this once I implement this fix

@pjbreaux @zancas

**Comment by pjbreaux** [comment]
@wojtek0806 Thanks for taking a look at this. The names should only be reflective of the uri. So if the uri calls tm/ltm/virtual/~partition~vs_name/policies, then we add an '_s' to the collection name. We will never break away from what the REST api dictates. If policy is singular when viewing tm/ltm/policy, then we can suggest the change to the REST team.

**Comment by wojtek0806** [comment]
well I have seen this implementation different. I would strip any s from resource names, but leave collections with either s or _s. This is how most of the latest endpoints were implemented

**Comment by wojtek0806** [comment]
i have had this argument with @caphrim007 last year and @zancas and they both told me that we always make the resource singular..

**Comment by pjbreaux** [comment]
We've always been at the mercy of the REST api, and our naming conventions have been pretty standardized. It may be ugly to some, but it is consistent, which I believe is worth sacrificing some beauty. Anyway, if you don't have the inclination or bandwidth to fix this issue, I can tackle it. Thanks again for jumping on it. I didn't even notice the get_collection issue until you mentioned it.

**Comment by wojtek0806** [comment]
nah ill fix it, when you need it by? :) I was just making an observation that we write one thing in dev guide and follow another :)

**Comment by pjbreaux** [comment]
Probably by the next release. So whenever is convenient. I would say a week.

**Comment by wojtek0806** [comment]
Fixed
