### ISSUE TITLE
This codebase should contain an f5-common base exception that is the parent of all specific exceptions raised in this library

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-common-python#98]
For consumers of this library, it would be nice to be able to import f5.common.exceptions in order to catch errors appropriately. The consumer would then not need to know how requests are performed in this library or how exceptions can occur. The consumer would be able to catch all exceptions with the parent f5-common.exceptions.base_exception or catch something more specific with f5-common.exceptions.ObjectUpdateException.

**Comment by zancas** [comment]
Fixed.
