### ISSUE TITLE
RPM/DEB build automation

### ISSUE THREAD

**Issue by ssorenso** [F5Networks/f5-common-python#980]
This issue is to address the creation of automation around building .rpm and .deb packages natively within the different operating systems that are supported.  This automation is to auto-handle the:

- The resolution of dependencies
  - stdeb.cfg (.deb building)
  - setup.cfg (.rpm building)
- Building of the packages
- The Testing of the packages

As such, this new solution should include a means by which to make a 'one source of truth' source file for all dependencies for a project.

Since this automation is a heavy lift, this automation should also be...

- Transferable to other projects and other github repos
- Modifiable and future proof

**Comment by ssorenso** [comment]
Added the `enhancement` label with the assistance of Matt.

Will be committing against this ticket here shortly with branch `feature.packaging_enhancement_980`

**Comment by wojtek0806** [comment]
@ssorenso 
we have the following issue open, that may/may not relate to this change, let me know which one of them is relevant or not please:

https://github.com/F5Networks/f5-common-python/issues/915
https://github.com/F5Networks/f5-common-python/issues/849
https://github.com/F5Networks/f5-common-python/issues/596

I would very much like to clean up the stuff here so we don't have duplication and old stuff hanging out there for too long

**Comment by ssorenso** [comment]
@wojtek0806 
You're right, all of these are likely related... I did not realize that what I was working on was so split up into several different tickets.  I will be working with @zancas and others here on the team to try and iron out a review.

**Comment by ssorenso** [comment]
Keeping the commits under this ticket as it's so interconnected.  Different pieces are not easily broken out from the rest; however, things are generic enough that they can be easily portable to other github repos for F5's development, at least for OpenStack.  Other requirements that I'm not aware of may be needed individually on a per-repo basis; however, this should allow for those changes to be uniquely made at each repo's unique `setup_requirements.txt` file.  Other required changes may need to be made; however, these can be documented as such whereas this can allow for a 'blanket' standard.
