### ISSUE TITLE
ensure that apis for ASM policies are in the SDK

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-common-python#986]
There was an ask from bizdev that we have the following in the sdk

"ASM policy Add/Change/Remove"

Whatever that means.

Since that's clearly a large ask, use your best judgement and consider what the common ASM policy use cases are. Based off of what you deem to be the "common" uses, ensure that APIs for those exist to do the CRUD ops on them. Reach out to support or whoever to get feedback on the above.

**Comment by wojtek0806** [comment]
issue already opened for it, adding sub-collections gradually #828

**Comment by wojtek0806** [comment]
changes merged
